import { renderEncuentros, fechaCumpleanos } from './vida-social-ui';
import { viviendaDe, NPCS_PUEBLO, EDIFICIOS_PUEBLO } from './pueblo-datos';
import { VIDA_PUEBLO, DIAS_SEMANA, horaPueblo, atencionServicio, ubicacionAldeano, puedeConversar, esRegalo, aldeanoDef, type Conversacion } from './aldeanos';
import { tiempoDia, lluviaRiega } from './clima';
import { obtenerObjeto } from './objetos';
import { calidadPila } from './inventario';
import type { EstadoGranja } from './estado';

const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const retrato=(color:string)=>`<span class="vecino-retrato" style="--ropa:${color}" aria-hidden="true"><i></i></span>`;
function corazones(amistad:number){const n=Math.floor(amistad/250);return `<span class="vecino-corazones" aria-label="${n} de 10 corazones">${'♥'.repeat(n)}<span>${'♡'.repeat(10-n)}</span></span>`;}
const resguardado=(s:EstadoGranja)=>lluviaRiega(tiempoDia(s.tiempo,s.jornada.diasCompletados));
export function renderVecinos(s:EstadoGranja,x:number,z:number){
 const dia=s.jornada.diasCompletados;return `<button class="btn" data-do="abrir-viviendas">Ver las viviendas del pueblo</button><p class="small-text">${DIAS_SEMANA[dia%7]} · ${horaPueblo(s.jornada.minutos)}. Conversa y conoce sus gustos: un regalo por jornada, hasta dos por semana.</p><div class="vecinos-lista">${NPCS_PUEBLO.map(n=>{
  const r=s.pueblo.relaciones.find(r=>r.id===n.id)!,h=VIDA_PUEBLO[n.id],u=ubicacionAldeano(n.id,dia,s.jornada.minutos,resguardado(s))!,a=n.oficio?atencionServicio(n.oficio,dia,s.jornada.minutos):{abierto:false,descanso:dia%7===h.descanso,horario:horaPueblo(h.abre)+'–'+horaPueblo(h.cierra)},ed=EDIFICIOS_PUEBLO.find(e=>e.id===n.edificio)!;
  return `<article class="card vecino-card">${retrato(n.color)}<div><h3>${esc(n.nombre)}</h3><p>${esc(h.labor??ed.nombre)}</p>${corazones(r.amistad)}${fechaCumpleanos(s,n.id)}<p class="small-text">${esc(u.lugar)}<br>Hogar: ${esc(viviendaDe(n.id)?.nombre)}<br>${esc(a.horario)}${h.descanso!==null?' · Descansa: '+DIAS_SEMANA[h.descanso]:''}</p><span class="pill ${a.abierto?'gold':''}">${n.oficio?(a.abierto?'Atendiendo':a.descanso?'Día libre':'Fuera de horario'):(u.actividad==='hogar'?'Descansando':u.andando?'De paseo':'En el pueblo')}</span>${r.conocido?'<span class="pill">Ya se conocen</span>':''}<div class="buttons"><button class="btn small" data-do="hablar-vecino" data-id="${n.id}" ${puedeConversar(s,n.id,x,z,resguardado(s))?'':'disabled'}>Conversar</button></div></div></article>`;
 }).join('')}</div><p class="small-text">Acércate caminando para conversar. Los horarios siguen los días de tu partida; los menús pausan el reloj.</p>`;
}
export function renderConversacion(s:EstadoGranja,id:string,x:number,z:number,c:Conversacion|null){
 const n=aldeanoDef(id);if(!n)return '<p>Elige un habitante del pueblo.</p>';
 const h=VIDA_PUEBLO[n.id],r=s.pueblo.relaciones.find(r=>r.id===id)!,dia=s.jornada.diasCompletados,regalos=r.semanaRegalos===Math.floor(dia/7)?r.diasRegalos:[],cerca=puedeConversar(s,id,x,z,resguardado(s)),a=n.oficio?atencionServicio(n.oficio,dia,s.jornada.minutos):{abierto:false,descanso:dia%7===h.descanso,horario:horaPueblo(h.abre)+'–'+horaPueblo(h.cierra)};
 const pilas=s.casillasInventario.flatMap((p,i)=>p&&esRegalo(p.articulo)?[`<option value="${i}">${esc(obtenerObjeto(p.articulo)?.nombre??p.articulo)} · ${['Normal','Plata','Oro','Iridio'][calidadPila(p)]} · ×${p.cantidad}</option>`]:[]);
 const gustos=Object.entries(r.gustosDescubiertos).map(([id,g])=>`<li>${esc(obtenerObjeto(id)?.nombre??id)}: ${esc({encanta:'Le encanta',gusta:'Le gusta',neutral:'Le resulta indiferente',desagrada:'No le gusta'}[g])}</li>`).join('');
 return `<div class="vecino-saludo">${retrato(n.color)}<div><h3>${esc(n.nombre)}</h3>${corazones(r.amistad)}${fechaCumpleanos(s,n.id)}</div></div><div class="vecino-dialogo" role="status">${esc(c?.id===id?c.texto:'Acércate para conversar con este habitante.')}</div>${c?.id===id&&c.puntos?`<p class="small-text">Amistad ${c.puntos>0?'+':''}${c.puntos}</p>`:''}<div class="buttons"><button class="btn" data-do="hablar-vecino" data-id="${id}" ${cerca?'':'disabled'}>${r.ultimaCharla===dia?'Seguir conversando':'Conversar'}</button>${n.oficio!==null&&s.servicio===n.oficio?'<button class="btn" data-do="volver-mostrador">Volver al mostrador</button>':n.oficio!==null&&uTrabajo(s,id)&&a.abierto?`<button class="btn" data-do="visitar-servicio" data-id="${n.oficio}">Visitar su local</button>`:''}<button class="btn quiet" data-do="abrir-vecinos">Ver habitantes</button></div><div class="card"><h3>Un detalle de tu mochila</h3><p class="small-text">Regalos esta semana: ${regalos.length} / 2${regalos.includes(dia)?' · Ya recibió el de hoy':''}. Entregas una unidad de la casilla elegida.</p><label class="small-text" for="regalo-vecino">Elige un regalo</label><select id="regalo-vecino" ${pilas.length?'':'disabled'}>${pilas.join('')||'<option>No tienes regalos en la mochila</option>'}</select><button class="btn primary" data-do="regalar-vecino" data-id="${id}" ${cerca&&pilas.length&&regalos.length<2&&!regalos.includes(dia)?'':'disabled'}>Entregar regalo</button></div>${gustos?`<details class="card" open><summary>Gustos que has descubierto</summary><ul>${gustos}</ul></details>`:''}${renderEncuentros(s,id,x,z)}${!cerca?'<p class="small-text">Camina hasta el habitante para continuar.</p>':''}`;
}
function uTrabajo(s:EstadoGranja,id:string){return ubicacionAldeano(id,s.jornada.diasCompletados,s.jornada.minutos,resguardado(s))?.actividad==='oficio';}
