import type { EstadoGranja } from './estado';
import { COMPANEROS, TIPOS_COMPANIA, companiaDisponible, varianteCompania, type TipoCompania } from './compania';
import { estadoAnimal } from './cuidados';
import { efectosHabilidades } from './habilidades';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const boton=(texto:string,accion:string,datos:string,disabled=false)=>`<button class="btn small" data-do="${accion}" ${datos} ${disabled?'disabled':''}>${texto}</button>`;
export function renderCompania(s:EstadoGranja,tipo:TipoCompania='gato'){
 const d=COMPANEROS[tipo],libres=s.edificios.filter(b=>b.articulo===d.hogar&&!s.compania.animales.some(a=>a.edificioId===b.id)),tienda=s.zona==='pueblo'&&s.servicio==='animales';
 return `<p class="small-text">Cada compañero tiene su hogar y sus cuidados. Acércate para alimentarlo, acariciarlo o llenar su cuenco. El vínculo aumenta con cariño una vez por jornada y con agua al dormir.</p><div class="card"><h3>Adoptar un compañero</h3><label>Compañero<select id="comp-tipo">${TIPOS_COMPANIA.map(t=>`<option value="${t}" ${tipo===t?'selected':''}>${COMPANEROS[t].nombre}${companiaDisponible(s,t)?'':' · misión pendiente'}</option>`).join('')}</select></label><label>Variedad<select id="comp-variante">${d.variantes.map((v,i)=>`<option value="${i}" ${i>1&&!s.misionesCompletadas.includes('confianza')?'disabled':''}>${esc(v)}${i>1&&!s.misionesCompletadas.includes('confianza')?' · Manos que cuidan':''}</option>`).join('')}</select></label><label>Nombre<input id="comp-nombre" maxlength="32" value="${tipo==='caballo'?'Canela':tipo==='tortuga'?'Oliva':tipo==='gato'?'Michi':'Luna'}"></label><label>Hogar libre<select id="comp-hogar">${libres.length?libres.map((b,i)=>`<option value="${b.id}">${tipo==='caballo'?'Establo':'Hogar'} ${i+1} · ${b.x}, ${b.z}</option>`).join(''):'<option value="">Construye primero un hogar</option>'}</select></label>${boton(`Adoptar · ${d.precio} ◈`,'comp-adoptar','',!tienda||!libres.length||!companiaDisponible(s,tipo))}<p class="small-text">${tienda?'La carpintería vende establos; el taller permite fabricar hogares.':'Visita la tienda de animales del pueblo para adoptar.'}</p></div>${tienda?`<div class="card"><h3>Provisiones</h3>${boton('Alimento para mascotas · 20 ◈','comprar-provision','data-id="alimento_mascota"')}<p>Una ración para gatos, perros o tortugas. Los caballos comen heno.</p></div>`:''}${s.compania.animales.map(a=>{
 const b=s.edificios.find(b=>b.id===a.edificioId)!,d=COMPANEROS[a.tipo],salud=estadoAnimal(a.cuidado,s.ultimoTiempo),montada=s.compania.montada===a.id,otros=s.edificios.filter(b=>b.articulo===d.hogar&&!s.compania.animales.some(c=>c.edificioId===b.id));
 return `<article class="card companero-card" data-companero="${a.id}"><div class="caps">${d.nombre} · ${d.variantes[varianteCompania(a)]}</div><h3>${esc(a.nombre)}</h3><div class="compania-vinculo"><progress max="1000" value="${a.amistad}" aria-label="Vínculo con ${esc(a.nombre)}"></progress><span>${a.amistad} / 1000</span></div><p>${salud.enfermo?'Necesita al veterinario':salud.deprimido?'Necesita atención por depresión':salud.hambriento?'Necesita alimento':salud.triste?'Necesita cariño':'Sano y acompañado'} · ${a.posicion.zona.replace('_',' ')} (${a.posicion.x.toFixed(1)}, ${a.posicion.z.toFixed(1)})</p><div class="button-row">${['alimentar','acariciar','musica','cuento','cepillar'].map(m=>boton(({alimentar:'Dar alimento',acariciar:'Acariciar',musica:'Música',cuento:'Cuento',cepillar:'Cepillar'} as Record<string,string>)[m],'comp-cuidar',`data-id="${a.id}" data-metodo="${m}"`,!!s.compania.montada)).join('')}${salud.enfermo||salud.deprimido?boton('Veterinario · '+Math.round(60*(efectosHabilidades(s.habilidades).veterinario??1))+' ◈','comp-cuidar',`data-id="${a.id}" data-metodo="medico"`,!!s.compania.montada):''}${a.tipo==='caballo'?boton(montada?'Desmontar':'Montar',montada?'comp-desmontar':'comp-montar',`data-id="${a.id}"`,!!s.compania.montada&&!montada):boton(a.seguir?'Volver al hogar':'Acompañarme','comp-seguir',`data-id="${a.id}"`,!!s.compania.montada)}</div>${a.tipo==='caballo'?`<p class="small-text">Pasto del establo: ${Math.floor(b.pasto)} raciones. Come una ración cada 8 horas reales mientras espera en su patio.</p>${boton('Sembrar pasto · 4 semillas','pasto',`data-id="${b.id}"`,b.pasto>=64||!!s.compania.montada)}${boton('Jardinero · 25 ◈','jardinero',`data-id="${b.id}"`,b.pasto>=64||!!s.compania.montada)}`:''}${a.tipo!=='caballo'?`<p class="small-text">${a.carinoDia===s.jornada.diasCompletados?'Cariño de hoy recibido (+12 vínculo).':'Aún puede recibir el vínculo de cariño de esta jornada.'} ${a.aguaDia===s.jornada.diasCompletados?'Cuenco lleno.':'Cuenco seco.'}</p>${boton('Llenar cuenco con regadera','comp-agua',`data-id="${a.id}"`,a.aguaDia===s.jornada.diasCompletados||!!s.compania.montada)}`:''}${otros.length?`<label>Cambiar hogar<select id="comp-traslado-${a.id}">${otros.map(b=>`<option value="${b.id}">${a.tipo==='caballo'?'Establo':'Hogar'} · ${b.x}, ${b.z}</option>`).join('')}</select></label>${boton('Trasladar conservando vínculo','comp-trasladar',`data-id="${a.id}"`,!!s.compania.montada)}`:''}</article>`;
 }).join('')||'<div class="note">Aún no tienes mascotas ni caballos. Completa Un hogar entre la maleza para descubrir mascotas y El primer surco para construir un establo.</div>'}`;
}
