import { ARTICULOS, type Articulo } from './catalogo';
import type { EstadoGranja } from './estado';
import { costeObra, obraActiva, plazoObra, requiereObra, nivelEdificio, capacidadRefugio, type ObraTerminada } from './construccion';
const esc=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const boton=(label:string,action:string,id:string,desactivado=false)=>`<button type="button" class="btn" data-do="${action}" data-id="${esc(id)}" ${desactivado?'disabled':''}>${label}</button>`;
const nombre=(id:string)=>ARTICULOS.find(a=>a.id===id)?.nombre??id;
const materiales=(r:Record<string,number>)=>Object.entries(r).map(([k,v])=>`${v} ${k.replaceAll('_',' ')}`).join(' · ');
export function renderEncargos(s:EstadoGranja){const activa=obraActiva(s);return `<div class="section-label">La cuadrilla · ${s.obras.encargos.length} / 8 encargos</div>${s.obras.encargos.length?s.obras.encargos.map(o=>{
 const c=costeObra(ARTICULOS.find(a=>a.id===o.articulo)!,o.nivel),plazo=plazoObra(s,o),actual=activa?.id===o.id;
 return `<div class="card obra-card" data-obra="${o.id}"><h3>${esc(nombre(o.articulo))}${o.tipo==='mejora'?` · Nivel ${o.nivel}`:''}</h3><span class="pill">${!o.lugar?'Elige el terreno':actual?'En construcción':'En espera'}</span><p>${o.lugar?`${o.lugar.x}, ${o.lugar.z} · ${o.jornadas} / ${c.noches} noches de trabajo<br>Lista en ${plazo} ${plazo===1?'noche':'noches'} al dormir.`:'Pagado y reservado en la carpintería. Regresa a la granja para emplazarlo; el plazo empieza después.'}</p><progress max="${c.noches}" value="${o.jornadas}" aria-label="Noches trabajadas"></progress><div class="buttons">${!o.lugar?boton('Elegir terreno','emplazar-obra',o.id,s.zona!=='granja'||!!s.interior||!!s.servicio):''}${boton('Cancelar y recuperar materiales','cancelar-obra',o.id)}</div></div>`;
 }).join(''):'<p class="small-text">Sin encargos pendientes.</p>'}<p class="small-text">Una cuadrilla construye por orden de emplazamiento. Las obras avanzan una noche al dormir; el tiempo fuera del juego no las adelanta. Cancelar devuelve todas las monedas y los materiales con su calidad.</p>`;}
export function renderAmpliaciones(s:EstadoGranja){return '<div class="section-label">Ampliar refugios</div>'+s.edificios.filter(b=>b.especie).map(b=>{
 const n=nivelEdificio(b),c=n<3?costeObra(ARTICULOS.find(a=>a.id===b.articulo)!,n+1 as 2|3):null,pendiente=s.obras.encargos.some(o=>o.edificioId===b.id);
 return `<div class="card"><h3>${esc(nombre(b.articulo))}</h3><p>${b.x}, ${b.z} · Nivel ${n}<br>${s.animales.filter(a=>a.edificioId===b.id).length} / ${capacidadRefugio(b)} habitantes</p>${c?`<p>Nivel ${n+1} · ${n===1?8:12} plazas<br>${c.monedas} ◈ + ${esc(materiales(c.materiales))}<br>${c.noches} noches · Conserva animales, hábitat, incubadora y comedero.</p>${boton(pendiente?'Ampliación pendiente':'Encargar ampliación','ampliar-refugio',b.id,pendiente||s.servicio!=='carpinteria')}`:'<span class="pill gold">Refugio completo · 12 plazas</span>'}</div>`;
 }).join('');}
export function renderTaller(s:EstadoGranja,items:Articulo[],a:Articulo,cat:string){const qty=s.inventario['creacion_'+a.id]??0,obra=requiereObra(a),c=costeObra(a),enTaller=s.servicio==='carpinteria';
 return `<p class="small-text">Encarga edificios y ampliaciones en la carpintería del pueblo. Después regresa caminando a la granja para elegir el terreno.</p><label for="category">¿Qué quieres crear?</label><select id="category">${[['decoracion','Decoraciones'],['refugio','Refugios y hábitats'],['suelo','Caminos y suelos'],['valla','Vallas y portones'],['casa','Cabaña principal']].map(([v,n])=>`<option value="${v}" ${v===cat?'selected':''}>${n}</option>`).join('')}</select><label for="article">Pieza</label><select id="article">${items.map(x=>`<option value="${x.id}" ${x.id===a.id?'selected':''}>${esc(x.nombre)}</option>`).join('')}</select><div class="card" style="margin-top:14px"><h3>${esc(a.nombre)}</h3><span class="pill">${a.ancho} × ${a.fondo} m${a.corral?' + corral':''}</span>${obra?`<span class="pill">${c.noches} noches de construcción</span>`:`<span class="pill">${qty} disponibles</span>`}<p>${a.especie?'Refugio con interior, comedero y zona cercada. Empieza con 6 plazas y se amplía a 8 y 12.':a.id==='establo'?'Un establo con patio y pasto para un caballo.':a.id==='invernadero'?'Interior protegido con 36 bancales y riego instalable.':a.id==='caja_envio'?'Prepara tus productos para venderlos al dormir.':a.categoria==='suelo'?'Las piezas contiguas comparten bordes y textura.':'Elige el lugar y el giro; podrás moverlo después.'}</p><div class="cost">◈ ${a.precio} monedas${obra?' + materiales':''}</div><p>${esc(materiales(a.receta))}</p><div class="buttons">${obra?boton('Encargar construcción','encargar-obra',a.id,!enTaller||s.obras.encargos.length>=8):boton('Comprar','comprar-art',a.id,!enTaller)+boton('Fabricar','fabricar-art',a.id)}</div>${qty?boton(obra?'Colocar edificio guardado':'Colocar en la granja','colocar',a.id):''}</div>${renderEncargos(s)}${renderAmpliaciones(s)}<div class="note">Despeja árboles, piedras y maleza antes de emplazar una obra. El corral y su entrada quedan reservados. Los refugios ampliados se pueden mover conservando su nivel.</div>${enTaller?boton('Volver al mostrador','volver-mostrador',''):''}`;
}
export function renderObrasNoche(obras?:ObraTerminada[]){return obras?.length?'<div class="section-label">La carpintería terminó</div>'+obras.map(o=>`<p class="obra-terminada">✓ ${esc(nombre(o.articulo))}${o.tipo==='mejora'?` · Nivel ${o.nivel} · ${o.nivel===2?8:12} plazas`:' · Edificio listo para entrar'}</p>`).join(''):'';}
