import type { EstadoGranja, Resultado } from './estado';
import { ARTICULOS } from './catalogo';
import { cambiarCantidad, resumirCasillas, type Pila } from './inventario';
import { fechaValle } from './jornada';
export interface CartaDef {id:string;remitente:string;titulo:string;texto:string;diaMin:number;actividad?:string;encargo?:string;estacion?:'verano'|'otono'|'invierno';monedas:number;objetos:readonly Pila[]}
export const CARTAS:readonly CartaDef[]=[
 {id:'bienvenida',remitente:'Casa de los Oficios',titulo:'Una nueva página',texto:'Bienvenidos al valle. Al dormir guardarás la jornada y avanzarás las estaciones. En el pueblo encontrarás herramientas, vecinos y encargos. Este buzón acompaña a tu cabaña cuando la reorganices.',diaMin:0,monedas:0,objetos:[]},
 {id:'primera_manana',remitente:'La cuidadora',titulo:'Para tu primera mañana',texto:'Una reserva de heno ayuda a empezar el día. Alimenta a tus animales y acompáñalos con cariño. Las crías crecen cuando avanzas las jornadas al dormir.',diaMin:1,monedas:0,objetos:[{articulo:'heno',cantidad:3}]},
 {id:'primeras_semillas',remitente:'La mercader',titulo:'Una cosecha que cuidar',texto:'Ya recogiste tu primera cosecha. Mira la temporada y los días que necesita cada semilla antes de volver a plantar. Un cultivo maduro puede conservarse como decoración.',diaMin:1,actividad:'cosechar',monedas:25,objetos:[]},
 {id:'herramientas',remitente:'El herrero',titulo:'Un oficio con práctica',texto:'Despejar recursos te dará materiales para reparar la granja. Lleva tus minerales a la forja cuando quieras mejorar una herramienta; prepara otra actividad mientras está en el taller.',diaMin:2,actividad:'limpiar',monedas:0,objetos:[{articulo:'carbon',cantidad:2}]},
 {id:'primer_pez',remitente:'La pescadora',titulo:'Noticias de la orilla',texto:'Tu primera captura abre un mundo de aguas y estaciones. La hora, el tiempo y el cebo cambian lo que puedes encontrar. Guarda una comida para tus próximas salidas.',diaMin:1,actividad:'pescar',monedas:0,objetos:[{articulo:'pan',cantidad:1}]},
 {id:'corral_cuidado',remitente:'La veterinaria',titulo:'Alimento y compañía',texto:'La rutina de tu corral empieza a tomar forma. El cariño y el alimento ayudan a mantener la salud; consulta los cuidados cuando regreses. La edad de los animales solo avanza al dormir.',diaMin:1,actividad:'consentir',monedas:0,objetos:[{articulo:'heno',cantidad:2}]},
 {id:'taller_agradecido',remitente:'La carpintera',titulo:'Gracias por el taller',texto:'Tus materiales dejaron el taller listo. Acércate cuando quieras encargar una obra. Una cuadrilla trabaja por orden y avanza al dormir; conserva espacio para el acceso de la construcción.',diaMin:1,encargo:'pedido_roble',monedas:0,objetos:[{articulo:'madera',cantidad:5}]},
 {id:'un_recuerdo',remitente:'El archivero',titulo:'Un momento compartido',texto:'Los recuerdos que compartimos también forman parte de la vida del pueblo. Puedes consultar tus encuentros en la conversación con cada habitante y continuar conociendo sus gustos.',diaMin:1,actividad:'escenas_sociales',monedas:0,objetos:[]},
 {id:'primera_obra',remitente:'La carpintera',titulo:'Un nuevo rincón',texto:'La primera obra terminada ya forma parte de tu granja. Puedes reorganizarla después de completar los trabajos. Sus instalaciones y habitantes mantienen su identidad al moverla.',diaMin:1,actividad:'obras_terminadas',monedas:20,objetos:[]},
 {id:'envio_cobrado',remitente:'El almacén del pueblo',titulo:'Tu primera venta nocturna',texto:'Los productos de la caja se pagan al dormir. Puedes retirar una entrega antes de cerrar la jornada. Las siguientes ventas aparecerán en el resumen de la noche.',diaMin:1,actividad:'ingresos_envio',monedas:0,objetos:[]},
 {id:'verano',remitente:'El agricultor',titulo:'Llega el verano',texto:'Empieza una temporada nueva. Revisa el calendario y las semillas de verano antes de sembrar. Los frutales adultos y el invernadero tienen reglas propias.',diaMin:28,estacion:'verano',monedas:0,objetos:[]},
 {id:'otono',remitente:'La botánica',titulo:'Los colores del otoño',texto:'La cosecha y el jardín cambian con la estación. Deja espacio para los caminos, cuida tus plantones y guarda productos para las recetas del valle.',diaMin:56,estacion:'otono',monedas:0,objetos:[]},
 {id:'invierno',remitente:'La posadera',titulo:'Un invierno para preparar',texto:'El invierno invita a preparar la próxima primavera. Revisa tus reservas, visita a los vecinos y reúne materiales. Los días de la estación se conservan cuando cierras el juego.',diaMin:84,estacion:'invierno',monedas:0,objetos:[]},
];
export interface CartaRecibida {id:string;recibidaDia:number;leidaDia:number|null;reclamadaDia:number|null}
export interface EstadoCorreo {version:1;cartas:CartaRecibida[]}
export type AccionCorreo={tipo:'leer'|'reclamar';id:string};
export const crearCorreo=():EstadoCorreo=>({version:1,cartas:[{id:'bienvenida',recibidaDia:0,leidaDia:null,reclamadaDia:null}]});
export function entregarCorreo(s:EstadoGranja){for(const c of CARTAS){if(s.correo.cartas.some(r=>r.id===c.id)||s.jornada.diasCompletados<c.diaMin||c.actividad&&!(s.estadisticas[c.actividad]>0)||c.encargo&&!s.encargos.registros.some(r=>r.id===c.encargo&&r.fase==='completado')||c.estacion&&fechaValle(s.jornada.diasCompletados).estacion!==c.estacion)continue;s.correo.cartas.push({id:c.id,recibidaDia:s.jornada.diasCompletados,leidaDia:null,reclamadaDia:null});}}
export function posicionBuzon(s:EstadoGranja){const b=s.edificios.find(b=>b.id==='casa_inicial')??s.edificios.find(b=>ARTICULOS.find(a=>a.id===b.articulo)?.categoria==='casa');if(!b)return null;const a=ARTICULOS.find(a=>a.id===b.articulo)!;const h={ancho:b.giro%2?a.fondo:a.ancho,fondo:b.giro%2?a.ancho:a.fondo},p=b.giro===0?{x:b.x+h.ancho/2,z:b.z+h.fondo+.5}:b.giro===1?{x:b.x-.5,z:b.z+h.fondo/2}:b.giro===2?{x:b.x+h.ancho/2,z:b.z-.5}:{x:b.x+h.ancho+.5,z:b.z+h.fondo/2};const t=b.giro*Math.PI/2;return {x:p.x-1.6*Math.cos(t)+.3*Math.sin(t),z:p.z+1.6*Math.sin(t)+.3*Math.cos(t)};}
export function cercaBuzon(s:EstadoGranja,x:number,z:number){const p=posicionBuzon(s);return !!p&&s.zona==='granja'&&!s.interior&&!s.servicio&&!s.aventura.destinoActual&&Number.isFinite(x)&&Number.isFinite(z)&&Math.hypot(x-p.x,z-p.z)<=2.4;}
export function actuarCorreo(s:EstadoGranja,a:AccionCorreo,x:number,z:number):Resultado{
 const c=CARTAS.find(c=>c.id===a.id),r=s.correo.cartas.find(r=>r.id===a.id),mal=(mensaje:string)=>({ok:false,mensaje});if(!c||!r||!cercaBuzon(s,x,z))return mal('Acércate al buzón para consultar esta carta.');
 if(a.tipo==='leer'){if(r.leidaDia===null){r.leidaDia=s.jornada.diasCompletados;s.estadisticas.cartas_leidas=(s.estadisticas.cartas_leidas??0)+1;}return {ok:true,mensaje:'Carta abierta.'};}
 if(a.tipo!=='reclamar'||r.leidaDia===null||r.reclamadaDia!==null||!c.monedas&&!c.objetos.length)return mal('Lee primero la carta y recoge su adjunto una sola vez.');
 if(s.monedas+c.monedas>1e9)return mal('No cabe el adjunto en tu saldo.');let mochila=s.casillasInventario;for(const p of c.objetos){const copia=cambiarCantidad(mochila,p.articulo,p.cantidad,p.calidad);if(!copia)return mal('Libera espacio para recoger todos los adjuntos. La carta conserva su contenido.');mochila=copia;}
 s.casillasInventario=mochila;s.inventario=resumirCasillas(mochila);s.monedas+=c.monedas;r.reclamadaDia=s.jornada.diasCompletados;s.estadisticas.adjuntos_correo=(s.estadisticas.adjuntos_correo??0)+1;return {ok:true,mensaje:'Adjunto recogido y guardado.'};
}
export function correoValido(v:EstadoCorreo,dia:number){if(!v||v.version!==1||!Array.isArray(v.cartas)||v.cartas.length>CARTAS.length)return false;const ids=new Set<string>();for(const r of v.cartas){const c=CARTAS.find(c=>c.id===r?.id);if(!c||ids.has(r.id)||!Number.isInteger(r.recibidaDia)||r.recibidaDia<c.diaMin||r.recibidaDia>dia||r.leidaDia!==null&&(!Number.isInteger(r.leidaDia)||r.leidaDia<r.recibidaDia||r.leidaDia>dia)||r.reclamadaDia!==null&&(!Number.isInteger(r.reclamadaDia)||r.leidaDia===null||r.reclamadaDia<r.leidaDia||r.reclamadaDia>dia||!c.monedas&&!c.objetos.length))return false;ids.add(r.id);}return ids.has('bienvenida');}
