import type { CultivoDef, Estacion } from './catalogo';

/** Balance propio en horas reales; las temporadas indican cuándo se pueden sembrar. */
const primavera:Estacion[]=['primavera'],verano:Estacion[]=['verano'],otono:Estacion[]=['otono'],invierno:Estacion[]=['invierno'];
type Fila=[string,string,Estacion[],number,number,number,CultivoDef['forma'],string,number?,boolean?,CultivoDef['cosecha']?];
const filas:Fila[]=[
 ['chirivia','Chirivía',primavera,4,4,10,'raiz','#e9d6aa'],
 ['coliflor','Coliflor',primavera,12,12,42,'cabeza','#f0e5cd'],
 ['ajo','Ajo',primavera,4,6,17,'raiz','#e8dcc8'],
 ['judia','Judía verde',primavera,10,9,21,'vaina','#98b45d',3,true],
 ['col_rizada','Col rizada',primavera,6,8,24,'hoja','#6e956e',undefined,false,'guadana'],
 ['patata','Patata',primavera,6,6,22,'raiz','#b99a69'],
 ['ruibarbo','Ruibarbo',primavera,13,18,65,'hoja','#c87888'],
 ['arroz','Arroz',primavera,8,5,14,'cereal','#dfd5a3',undefined,false,'guadana'],
 ['tulipan','Tulipán',primavera,6,4,13,'flor','#d797a8'],
 ['jazmin_azul','Jazmín azul',primavera,7,6,18,'flor','#99aed6'],
 ['brocoli','Brócoli',otono,8,7,24,'cabeza','#7c9c67',4],
 ['arandano','Arándano',verano,13,12,18,'baya','#8496c5',4],
 ['melon','Melón',verano,12,12,48,'fruto','#aac386'],
 ['lombarda','Lombarda',verano,9,15,50,'cabeza','#ae85b0'],
 ['rabano','Rábano',verano,6,6,21,'raiz','#d78ba0'],
 ['pimiento','Pimiento',verano,5,6,17,'baya','#cf7766',3],
 ['lupulo','Lúpulo',verano,11,9,9,'vaina','#b1c47c',2,true],
 ['carambola','Carambola',verano,13,45,150,'fruto','#e7c563'],
 ['amapola','Amapola',verano,7,8,28,'flor','#da886b'],
 ['lentejuela_verano','Lentejuela de verano',verano,8,7,24,'flor','#d79cae'],
 ['girasol','Girasol',['verano','otono'],8,16,28,'flor','#e6c765'],
 ['calabacin_verano','Calabacín de verano',verano,6,8,27,'fruto','#e2c46e',3],
 ['amaranto','Amaranto',otono,7,9,34,'cereal','#b587b4',undefined,false,'guadana'],
 ['alcachofa','Alcachofa',otono,8,10,37,'cabeza','#91ae77'],
 ['remolacha','Remolacha',otono,6,6,23,'raiz','#b47799'],
 ['berenjena','Berenjena',otono,5,4,14,'fruto','#8970a7',4],
 ['bok_choy','Bok choy',otono,4,6,21,'hoja','#9fb681'],
 ['arandano_rojo','Arándano rojo',otono,7,25,21,'baya','#c58691',5],
 ['uva','Uva',otono,10,8,25,'baya','#a084b2',3,true],
 ['name','Ñame',otono,10,9,35,'raiz','#c19a7a'],
 ['rosa_hada','Rosa de hada',otono,12,22,62,'flor','#cba1cd'],
 ['girasol_lunar','Girasol lunar',otono,8,9,27,'flor','#b3a4ce'],
 ['melon_polvo','Melón de polvo',invierno,7,8,29,'fruto','#a9c8c2'],
 ['fruta_antigua','Fruta antigua',['primavera','verano','otono'],28,90,140,'fruto','#92b5be',7],
 ['fruta_dulce','Fruta dulce',otono,24,160,500,'fruto','#d6a672'],
 ['cafe','Café',['primavera','verano'],10,20,5,'baya','#947a64',2],
 ['te','Té',['primavera','verano','otono'],20,25,14,'hoja','#789c6b',4],
 ['cactus','Cactus',['primavera','verano','otono','invierno'],12,30,42,'cactus','#89ad83',3],
 ['pina','Piña',verano,14,35,74,'fruto','#d9ba71',7],
 ['taro','Taro',verano,10,8,28,'hoja','#8ba681'],
 ['jengibre','Jengibre',['primavera','verano','otono'],8,10,26,'raiz','#d6b38a'],
 ['fibra_cultivada','Fibra cultivada',['primavera','verano','otono','invierno'],7,4,8,'hoja','#88a578',undefined,false,'guadana'],
 ['calabaza_mantequilla','Calabaza mantequilla',otono,12,14,48,'fruto','#d6ae7d'],
 ['pepino','Pepino',verano,9,10,28,'fruto','#81a76c',4],
 ['zanahoria_dorada','Zanahoria dorada',primavera,10,24,75,'raiz','#e3c268'],
 ['fibra_ancestral','Fibra ancestral',['primavera','verano','otono'],16,28,65,'hoja','#93b3a0'],
 ['baya_vigor','Baya vigor',['primavera','verano'],9,16,38,'baya','#bc8fab',4],
 ['hortaliza_vigor','Hortaliza vigor',['verano','otono'],10,18,50,'cabeza','#a6b882'],
 ['fruta_monstruo','Fruta monstruo',otono,12,30,85,'fruto','#aa7b9d',5],
 ['hongo_monstruo','Hongo monstruo',['primavera','otono'],10,24,64,'hongo','#ba809f',4],
 ['salal','Salal',primavera,10,12,32,'baya','#9a8bac',4],
 ['baya_gelatina','Baya de gelatina',verano,8,15,39,'baya','#89b2a0',3],
 ['batata','Batata',otono,8,7,27,'raiz','#bd927b'],
 ['raiz_vacio','Raíz del vacío',invierno,12,30,90,'raiz','#8e80a7'],
];
export const CULTIVOS_ADICIONALES:CultivoDef[]=filas.map(([id,nombre,estaciones,horas,precio,valor,forma,color,rebroteHoras,enrejado,cosecha])=>({
 id,nombre,modelo:'',semilla:'semilla_'+id,producto:id==='cafe'?'grano_cafe':id==='te'?'hoja_te':id==='fibra_cultivada'?'fibra':id,
 estaciones,horas,precio,valor,forma,color,rebroteHoras,enrejado,cosecha:cosecha??'mano',
 climas:id==='raiz_vacio'?['sombrio']:id==='fibra_ancestral'||id==='hongo_monstruo'?['humedo']:id==='melon_polvo'?['polar','templado']:id==='cactus'?['mineral','volcanico']:['templado','humedo'],
 requiere:['fruta_antigua','fruta_dulce','fibra_ancestral','fruta_monstruo','hongo_monstruo','raiz_vacio','zanahoria_dorada'].includes(id)?'bosque_ancestral':undefined,
 fases:[.18,.27,.30,.25],cantidad:id.includes('arandano')?3:id==='fibra_cultivada'?5:1,
}));
