import { capacidadRefugio, nivelEdificio } from './refugios';
import { GANADO, leerHuevo, COSTE_INCUBADORA, COSTE_INCUBADORA_GRANDE } from './ganaderia';
import { fenotipo } from './genetica';
import { ESPECIES } from './catalogo';
import { calidadPila } from './inventario';
import type { EstadoGranja } from './estado';
import { puertaAbierta } from './rutinas-ganado';
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const boton=(texto:string,accion:string,id:string,extra='')=>`<button class="btn small" data-do="${accion}" data-id="${id}" ${extra}>${texto}</button>`;
export function renderIncubacion(s:EstadoGranja){const b=s.edificios.find(b=>b.id===s.interior),i=s.ganaderia.incubadoras.find(i=>i.edificioId===b?.id);if(!b?.especie||!GANADO[b.especie].incubacion)return '<p class="note">Entra caminando en un refugio de gallinas, patos, avestruces, dinosaurios, dragones o grifos para preparar su incubadora.</p><div class="section-label">Incubaciones en la granja</div>'+s.ganaderia.incubadoras.map(i=>{const h=i.huevo,e=h&&leerHuevo(h.articulo);return `<div class="card"><h3>${e?esc(h!.nombre):'Incubadora libre'}</h3><p>${e?`${ESPECIES[e.especie].nombre} · ${h!.dias} / ${GANADO[e.especie].incubacion} noches`:'Sin huevo'}</p></div>`;}).join('');
 const huevos=s.casillasInventario.flatMap((p,casilla)=>{const h=p&&leerHuevo(p.articulo);return p&&h&&h.especie===b.especie?[{p,h,casilla}]:[];}),ocupados=s.animales.filter(a=>a.edificioId===b.id).length;
 let html=`<div class="card"><h3>${ESPECIES[b.especie].nombre} · su siguiente generación</h3><p>${ocupados} habitantes${i?.huevo?' + 1 plaza reservada':''} / 6 plazas. La incubación avanza una noche al dormir; la ausencia real no adelanta la cría.</p></div>`;
 if(!i)return html+`<p class="note">Instala una incubadora. Los huevos de avestruz, dragón y grifo también necesitan ampliarla.</p>${boton('Instalar · '+COSTE_INCUBADORA.monedas+' ◈','instalar_incubadora',b.id)}<p class="small-text">15 maderas · 4 cobres · 2 vidrios</p>`;
 html+=`<div class="section-label">Incubadora ${i.grande?'grande':'básica'}</div>`;
 if(i.huevo){const h=i.huevo,e=leerHuevo(h.articulo)!;html+=`<div class="card"><h3>${esc(h.nombre)}</h3><p>${esc(fenotipo(e.especie,e.genoma).label)} · ${e.sexo==='hembra'?'♀':'♂'}</p><div class="bar"><span style="width:${h.dias/GANADO[e.especie].incubacion*100}%"></span></div><p>Faltan ${GANADO[e.especie].incubacion-h.dias} noches para nacer.</p>${boton('Retirar el mismo huevo','cancelar_incubacion',b.id)}<p class="small-text">Conserva genes y calidad. Retirarlo reinicia la incubación.</p></div>`;}
 else html+=`<label for="incubacion-nombre">Nombre de la cría</label><input id="incubacion-nombre" maxlength="32" placeholder="Su primer nombre"><div class="section-label">Huevos fértiles de la mochila</div>${huevos.length?huevos.map(({p,h,casilla})=>`<div class="card"><h3>${esc(fenotipo(h.especie,h.genoma).label)} · ${h.sexo==='hembra'?'♀':'♂'}</h3><p>${Object.values(h.genoma).map(p=>p.join('')).join(' · ')} · calidad ${calidadPila(p)} · ${p.cantidad} huevo(s)</p>${boton('Incubar este huevo','incubar',b.id,`data-casilla="${casilla}"`)}</div>`).join(''):'<p class="note">Los huevos comunes son alimento. Consigue un huevo fértil en la tienda de animales o cruzando una pareja adulta.</p>'}`;
 if(!i.grande)html+=`<div class="section-label">Huevos grandes</div>${boton('Ampliar · '+COSTE_INCUBADORA_GRANDE.monedas+' ◈','ampliar_incubadora',b.id)}<p class="small-text">20 maderas · 4 lingotes de hierro · 4 vidrios</p>`;return html;}
export function productoAnimal(especie:keyof typeof GANADO){return {recoger:'Recoger',ordenar:'Ordeñar',esquilar:'Esquilar',buscar_trufas:'Buscar trufas'}[GANADO[especie].metodo];}

export function renderRefugio(s:EstadoGranja,id:string){
 const b=s.edificios.find(b=>b.id===id);if(!b?.especie)return '';
 const animales=s.animales.filter(a=>a.edificioId===b.id),fuera=animales.filter(a=>a.rutina?.lugar==='corral').length,heno=b.henoReserva??0;
 const carga=Math.min(6,64-heno,s.inventario.heno??0);
 return `<div data-ganado-control><h3>${ESPECIES[b.especie].nombre} · Nivel ${nivelEdificio(b)} · ${capacidadRefugio(b)} plazas</h3><p>${fuera} en el corral · ${animales.length-fuera} dentro.<br>Puerta ${puertaAbierta(b)?'abierta':'cerrada'} · ${Math.floor(b.pasto)} porciones de pasto · ${heno} de heno guardadas.</p><div class="buttons">${boton(puertaAbierta(b)?'Cerrar puerta':'Abrir puerta','puerta_ganado',id)}${boton('Guardar '+carga+' henos','abastecer_refugio',id,`data-cantidad="${carga}" ${carga?'':'disabled'}`)}${heno?boton('Retirar heno','retirar_heno',id,`data-cantidad="${Math.min(6,heno)}"`):''}</div><p class="small-text">Salen con tiempo seco hasta las 17:00. Vuelven por lluvia o al anochecer; abre la puerta si alguno está esperando. El heno de reserva alimenta cuando se acaba el pasto, cada 8 horas reales.</p><div class="buttons">${boton('Plantar pasto','pasto',id)}${boton('Jardinero · 25 ◈','jardinero',id)}</div><div class="buttons">${boton('Cuidados y familia','abrir-animales',id)}${GANADO[b.especie].incubacion?boton('Incubadora','abrir-incubacion',id):''}${s.interior===b.id?boton('Salir al corral','salir',id):''}</div></div>`;
}
