import { HABILIDADES, NOMBRES_HABILIDAD, UMBRALES, PROFESIONES, progresoHabilidad, profesionesDisponibles, requisitoReceta, recetaAprendida, costeHerramienta, type EstadoHabilidades, type Habilidad, type Aprendizaje } from './habilidades';
import { RECETAS, obtenerReceta } from './objetos';
import { iconoInventario } from './inventario-ui';
import './habilidades-ui.css';
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const ICONOS:Record<Habilidad,string>={agricultura:'herramienta_azada',mineria:'herramienta_pico',recoleccion:'herramienta_hacha',pesca:'herramienta_cana',combate:'herramienta_espada'};
const ACCIONES:Record<Habilidad,string>={agricultura:'Cosechar plantas y frutas, recoger productos, criar y atender animales. El cariño y la comida dan experiencia una vez por animal y jornada.',mineria:'Destruir rocas y vetas. Los minerales difíciles aportan más experiencia.',recoleccion:'Derribar árboles y cortar maleza. Talar plantones no da experiencia.',pesca:'Capturar peces. Las especies raras aportan más experiencia; los peces que escapan no la dan.',combate:'Vencer criaturas. Los golpes sin derrotarlas no dan experiencia.'};
export function renderHabilidades(e:EstadoHabilidades){return `<section class="habilidades"><p class="hab-intro">Aprendes mientras trabajas y exploras. El nivel mejora tus herramientas al alcanzarlo; las recetas y las profesiones se reconocen al dormir. <strong>F</strong> abre este cuaderno.</p>${HABILIDADES.map(h=>{
 const v=progresoHabilidad(e,h),elecciones=profesionesDisponibles(e,h),elegidas=Object.values(e.profesiones[h]).filter(Boolean).map(id=>PROFESIONES.find(p=>p.id===id)!),pendientes=v.nivel>e.reconocidos[h],recetas=RECETAS.filter(r=>requisitoReceta(r).habilidad===h&&requisitoReceta(r).nivel>0),proximo=recetas.filter(r=>!recetaAprendida(e,r)).sort((a,b)=>requisitoReceta(a).nivel-requisitoReceta(b).nivel).slice(0,3),herramienta=ICONOS[h].slice(12) as Parameters<typeof costeHerramienta>[1],coste=costeHerramienta(e,herramienta,h==='pesca'?3:1);
 return `<article class="hab-card hab-${h}" data-habilidad="${h}"><header><span class="hab-icono">${iconoInventario(ICONOS[h])}</span><div><h3>${NOMBRES_HABILIDAD[h]}</h3><p>Nivel <strong data-hab-nivel>${v.nivel}</strong> / 10${pendientes?' · Aprendizajes pendientes para esta noche':''}</p></div></header><div class="hab-niveles" aria-label="Nivel ${v.nivel} de diez">${Array.from({length:10},(_,i)=>`<span class="${i<v.nivel?'ganado':''}${i===4||i===9?' especial':''}" title="Nivel ${i+1}: ${UMBRALES[i+1]} XP">${i+1}</span>`).join('')}</div><progress max="100" value="${v.porcentaje}" aria-label="Progreso de ${NOMBRES_HABILIDAD[h]}"></progress><p class="hab-xp" data-hab-xp>${v.xp.toLocaleString('es')} XP${v.nivel===10?' · Nivel máximo':` · Faltan ${v.faltan.toLocaleString('es')} XP para el nivel ${v.nivel+1}`}</p><p class="hab-accion">${ACCIONES[h]}</p><p class="hab-beneficio">${h==='agricultura'?'Aumenta la probabilidad de cosechas de calidad. ':h==='pesca'?`+${v.nivel} puntos de precisión. `:h==='combate'?`+${Math.floor(v.nivel/2)} de ataque. `:''}${h==='agricultura'?`Energía: azada <strong>${coste.toLocaleString('es')}</strong> · regadera <strong>${costeHerramienta(e,'regadera').toLocaleString('es')}</strong>.`:`Energía por ${h==='pesca'?'lanzamiento':'uso de '+(h==='combate'?'espada':h==='mineria'?'pico':'hacha')}: <strong>${coste.toLocaleString('es')}</strong>.`}</p>${elegidas.map(p=>`<div class="hab-elegida"><strong>✓ ${esc(p.nombre)}</strong><span>${esc(p.descripcion)}</span></div>`).join('')}${elecciones.length?`<div class="hab-profesiones"><h4>Elige tu profesión de nivel ${elecciones[0].nivel}</h4><p>La elección se guarda y abre su propia especialización al nivel 10.</p>${elecciones.map(p=>`<button type="button" data-hab-profesion="${p.id}"><strong>${esc(p.nombre)}</strong><span>${esc(p.descripcion)}</span></button>`).join('')}</div>`:!e.profesiones[h].nivel5?'<p class="hab-proxima">Profesión al nivel 5 · Especialización al nivel 10</p>':''}${proximo.length?`<details><summary>Próximas recetas</summary><ul class="hab-recetas">${proximo.map(r=>`<li><span>${iconoInventario(r.salida.articulo)}</span><div><strong>${esc(r.nombre)}</strong><small>Nivel ${requisitoReceta(r).nivel} y descanso${r.nivel?` · Herramienta ${r.nivel}`:''}${r.requisito?' · Descubrimiento en el mundo':''}</small></div></li>`).join('')}</ul></details>`:'<p class="hab-proxima">Todos los aprendizajes de esta habilidad reconocidos.</p>'}</article>`;
 }).join('')}<p class="hab-intro">Labrado, riego, mover objetos y repetir golpes sobre un recurso sin terminarlo no dan experiencia. Las estaciones, los materiales y los descubrimientos siguen siendo necesarios para fabricar.</p></section>`;}
export function renderAprendizajesNoche(aprendizajes:Aprendizaje[]=[]){if(!aprendizajes.length)return '';return `<section class="hab-noche"><h3>Lo que aprendiste hoy</h3>${aprendizajes.map(a=>`<div data-hab-noche="${a.habilidad}"><strong>${NOMBRES_HABILIDAD[a.habilidad]} · Nivel ${a.desde} → ${a.hasta}</strong>${a.recetas.length?`<p>Recetas: ${a.recetas.map(id=>esc(obtenerReceta(id)?.nombre??id)).join(', ')}.</p>`:''}${a.desde<5&&a.hasta>=5||a.desde<10&&a.hasta>=10?'<p>Al comenzar la mañana, abre Habilidades para elegir tu profesión.</p>':''}</div>`).join('')}</section>`;}
