import { renderCalendarioSocial } from './vida-social-ui';
import './vida-social-ui.css';
import { renderObrasNoche } from './construccion-ui';
import { renderAprendizajesNoche } from './habilidades-ui';
import { renderVentasNoche } from './envios-ui';
import { valorEnvios } from './envios';
import type { EstadoGranja } from './estado';
import { fechaValle, type ResumenJornada } from './jornada';
import './jornada-ui.css';
import { pronostico, TIEMPOS } from './clima';
import { renderPronostico, ayudaRiego } from './clima-ui';
const estaciones={primavera:'Primavera',verano:'Verano',otono:'Otoño',invierno:'Invierno'};
export const fechaJornada=(f:ReturnType<typeof fechaValle>)=>estaciones[f.estacion]+' · Día '+f.dia+' · Año '+f.ano;
const ACTIVIDADES:Record<string,string>={vender:'Productos vendidos',labrar:'Casillas labradas',plantar:'Semillas plantadas',regar:'Cultivos regados',riego_lluvia:'Cultivos regados por la lluvia',cosechar:'Cosechas recogidas',limpiar:'Recursos despejados',fabricar:'Productos fabricados',craftear:'Piezas creadas',pescar:'Peces capturados',nacimientos:'Crías nacidas',producto:'Productos animales',monstruos:'Criaturas vencidas',misiones:'Misiones completadas',huecos_rellenados:'Huecos reparados'};
const boton=(accion:string,label:string)=>'<button type="button" class="btn" data-jornada="'+accion+'">'+label+'</button>';
export function confirmarNoche(s:EstadoGranja){const hoy=fechaValle(s.jornada.diasCompletados),manana=fechaValle(s.jornada.diasCompletados+1);return '<div class="caps">Descanso en la cabaña</div><h2 id="jornada-titulo">¿Cerrar esta jornada?</h2><p>'+fechaJornada(hoy)+'</p><p class="clima-resumen">'+TIEMPOS[pronostico(s).hoy].icono+' '+TIEMPOS[pronostico(s).hoy].nombre+' · '+ayudaRiego(pronostico(s).hoy)+'</p><p>Despertarás a las 06:00 de '+fechaJornada(manana)+'. Los cultivos regados hoy avanzarán un día y recuperarás salud y energía.</p>'+(hoy.estacion!==manana.estacion?'<div class="note">Mañana empieza '+estaciones[manana.estacion]+'. Cambiará la oferta de semillas y las temporadas de siembra.</div>':'')+(valorEnvios(s.envios)?'<p>Los productos preparados en tus cajas se venderán por <strong>'+valorEnvios(s.envios).toLocaleString('es')+' ◈</strong>.</p>':'')+'<p class="small-text">El día y la temporada solo cambian al dormir. Los cultivos y las crías solo crecen al dormir. La cuadrilla avanza una noche de obra al dormir. La sequía y la salud usan horas reales.</p><div class="buttons">'+boton('cancelar','Seguir jugando')+boton('dormir','Dormir y guardar')+'</div>';}
export function resumenNoche(r:ResumenJornada,pendiente:boolean){const saldo=r.monedasFin-r.monedasInicio,filas=Object.entries(ACTIVIDADES).filter(([id])=>r.actividades[id]>0).map(([id,label])=>'<div class="jornada-fila"><span>'+label+'</span><strong>'+r.actividades[id]+'</strong></div>').join('');return '<div class="jornada-luna" aria-hidden="true">☾</div><div class="caps">Una jornada en el valle</div><h2 id="jornada-titulo">'+fechaJornada(r.fecha)+'</h2><p class="jornada-guardado">✓ Jornada guardada</p><div class="jornada-saldo"><span>Saldo de la granja</span><strong>'+r.monedasFin.toLocaleString('es')+' ◈</strong><small>'+(saldo>=0?'+':'')+saldo.toLocaleString('es')+' ◈ durante la jornada</small></div><div class="jornada-actividades">'+(filas||'<p class="small-text">Un día tranquilo también cuenta.</p>')+'</div>'+renderVentasNoche(r.envios)+renderAprendizajesNoche(r.aprendizajes)+renderObrasNoche(r.obras)+(r.cultivosAvanzados?'<p>'+r.cultivosAvanzados+' cultivos regados avanzaron durante la noche'+(r.cultivosMaduros?' · '+r.cultivosMaduros+' listos para cosechar':'')+'.</p>':'')+'<p class="jornada-manana">'+fechaJornada(r.fechaSiguiente)+' · 06:00</p><div class="buttons">'+boton(pendiente?'continuar':'cerrar',pendiente?'Comenzar la mañana':'Volver al valle')+'</div>';}
export function renderCalendario(s:EstadoGranja){return renderCalendarioSocial(s)+renderPronostico(s)+'<div class="card"><h3>'+fechaJornada(fechaValle(s.jornada.diasCompletados))+'</h3><p>Cada temporada tiene 28 días. La hora avanza mientras juegas; el día y la temporada solo cambian al dormir.</p><p>Al cerrar el juego o entrar en la casa y sus minijuegos se conserva la jornada. Al dormir se guarda una copia de recuperación de la mañana.</p></div><div class="note">El riego, el cariño, la salud animal y la producción automática siguen usando horas reales. No hacen crecer los cultivos ni las crías. Riega cada día de juego para que la cosecha avance al dormir.</div>'+(s.jornada.ultimaNoche?boton('ver-resumen','Ver la última jornada guardada'):'<p class="small-text">Acércate a la cabaña y elige Dormir para guardar tu primera jornada.</p>');}
