import type { EstadoGranja } from './estado';
import { CUMPLEANOS, cumpleHoy, ESCENAS, disponibleEscena } from './vida-social';
import { fechaValle } from './jornada';
import { aldeanoDef, puedeConversar } from './aldeanos';
import { lluviaRiega, tiempoDia } from './clima';
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function renderCalendarioSocial(s:EstadoGranja){const f=fechaValle(s.jornada.diasCompletados);return `<div class="card"><h3>Calendario del pueblo</h3><div class="calendario-social">${Array.from({length:28},(_,i)=>{const dia=i+1,c=CUMPLEANOS.find(c=>c.estacion===f.estacion&&c.dia===dia);return `<div class="calendario-dia ${f.dia===dia?'hoy':''}" ${f.dia===dia?'aria-current="date"':''}><strong>${dia}</strong>${c?`<span>🎂 ${esc(aldeanoDef(c.id)?.nombre)}</span>`:''}</div>`;}).join('')}</div><p class="small-text">Un regalo que no desagrade en su cumpleaños suma hasta 60 puntos adicionales de amistad. Se mantienen los límites diarios y semanales.</p></div>`;}
export function renderEncuentros(s:EstadoGranja,id:string,x:number,z:number){return ESCENAS.filter(d=>d.npc===id).map(d=>{const terminado=s.vidaSocial.escenas.find(e=>e.id===d.id),cerca=puedeConversar(s,id,x,z,lluviaRiega(tiempoDia(s.tiempo,s.jornada.diasCompletados)));return `<div class="card"><h3>${esc(d.titulo)}</h3>${terminado?`<p>Recuerdo compartido: ${esc(d.opciones[terminado.eleccion])}</p>`:`<p class="small-text">Requiere ${d.amistad} de amistad${d.pedido?' y su encargo completado':''}${d.actividad?' y actividad en la granja':''}.</p><button class="btn" data-do="social-iniciar" data-id="${d.id}" ${disponibleEscena(s,d.id)&&cerca?'':'disabled'}>Compartir un momento</button>`}</div>`;}).join('');}
export function renderEscena(s:EstadoGranja){const a=s.vidaSocial.actual,d=ESCENAS.find(d=>d.id===a?.id);if(!a||!d)return '<p>Encuentro completado. Puedes cerrar este panel.</p>';return `<div class="caps">${esc(aldeanoDef(d.npc)?.nombre)}</div><h3>${esc(d.titulo)}</h3><div class="vecino-dialogo" role="status">${esc(d.lineas[a.paso])}</div><p class="small-text">${a.paso+1} / ${d.lineas.length} · El reloj está en pausa.</p><div class="buttons">${a.paso<d.lineas.length-1?`<button class="btn primary" data-do="social-avanzar" data-id="${d.id}" data-paso="${a.paso}">Continuar</button>`:d.opciones.map((o,i)=>`<button class="btn" data-do="social-elegir" data-id="${d.id}" data-paso="${a.paso}" data-eleccion="${i}">${esc(o)}</button>`).join('')}<button class="btn quiet" data-do="social-cancelar" data-id="${d.id}">Dejar para otro momento</button></div>`;}

export function fechaCumpleanos(s:EstadoGranja,id:string){const c=CUMPLEANOS.find(c=>c.id===id);return c?`<p class="small-text">🎂 ${cumpleHoy(id,s.jornada.diasCompletados)?'<strong>Hoy es su cumpleaños</strong>':c.dia+' de '+({primavera:'primavera',verano:'verano',otono:'otoño',invierno:'invierno'}[c.estacion])}</p>`:'';}
