import { dormitorioDef, puertaDormitorio, puedeEntrarDormitorio, horaDormitorio, MUEBLES_DORMITORIO } from './dormitorios';
import type { EstadoGranja } from './estado';
import { VIVIENDAS_PUEBLO, viviendaInterior, visitaVivienda, NPCS_PUEBLO } from './pueblo-datos';
import { puedeConversar, ubicacionAldeano } from './aldeanos';
import { lluviaRiega, tiempoDia } from './clima';
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const nombres=(ids:readonly string[])=>ids.map(id=>NPCS_PUEBLO.find(n=>n.id===id)?.nombre??id).join(', ');
export function renderViviendas(s:EstadoGranja,x:number,z:number){return `<p>Las visitas son de 08:00 a 21:00. Camina hasta la puerta para entrar; cada vecino regresa a su domicilio.</p>${VIVIENDAS_PUEBLO.map(v=>`<article class="card"><h3>${esc(v.nombre)}</h3><p>${esc(nombres(v.ocupantes))}</p><p class="small-text">${v.edificio?'Vivienda anexa al comercio':'Barrio '+(v.z<0?'norte':'sur')} · Puerta: ${v.entrada.x}, ${v.entrada.z}</p><button class="btn" data-do="visitar-vivienda" data-id="${v.id}" ${s.zona==='pueblo'&&!s.interior&&!s.servicio&&visitaVivienda(s.jornada.minutos)&&Math.hypot(x-v.entrada.x,z-v.entrada.z)<=2.8?'':'disabled'}>Visitar vivienda</button></article>`).join('')}`;}
export function renderDentroVivienda(s:EstadoGranja,x:number,z:number){const v=viviendaInterior(s.interior);if(!v)return '';const d=dormitorioDef(s.interior);if(d)return `<div data-vivienda-control><div class="caps">Un espacio personal</div><h3>Dormitorio de ${esc(d.nombre)}</h3><p class="small-text">${horaDormitorio(s.jornada.minutos)?'Si está en casa, puedes conversar acercándote.':'Su ocupante sigue su rutina en la sala común o en el pueblo.'}</p>${Object.entries(MUEBLES_DORMITORIO).map(([id,m])=>`<button class="btn" data-do="inspeccionar-mueble" data-id="${id}" ${Math.hypot(x-m.x,z-m.z)<=1.8?'':'disabled'}>Consultar ${esc(m.nombre.toLowerCase())}</button>`).join('')}<p class="small-text">Camina hasta el escritorio o la biblioteca para consultar sus objetos.</p><button class="btn" data-do="salir">Volver a la sala común</button></div>`;const lluvia=lluviaRiega(tiempoDia(s.tiempo,s.jornada.diasCompletados)),presentes=v.ocupantes.filter(id=>ubicacionAldeano(id,s.jornada.diasCompletados,s.jornada.minutos,lluvia)?.actividad==='hogar'&&visitaVivienda(s.jornada.minutos)&&!horaDormitorio(s.jornada.minutos));return `<div data-vivienda-control><div class="caps">En casa de nuestros vecinos</div><h3>${esc(v.nombre)}</h3><p>${esc(nombres(v.ocupantes))}</p>${presentes.map(id=>`<button class="btn" data-do="hablar-vecino" data-id="${id}" ${puedeConversar(s,id,x,z,lluvia)?'':'disabled'}>Conversar con ${esc(NPCS_PUEBLO.find(n=>n.id===id)?.nombre)}</button>`).join('')||'<p class="small-text">Los habitantes están fuera o descansando.</p>'}<div class="buttons">${v.ocupantes.map(id=>{const r=s.pueblo.relaciones.find(r=>r.id===id)!;return `<button class="btn" data-do="entrar-dormitorio" data-id="${id}" ${puedeEntrarDormitorio(s,id,x,z)?'':'disabled'}>Dormitorio de ${esc(NPCS_PUEBLO.find(n=>n.id===id)?.nombre)} · ${r.amistad>=500?'Acércate a su puerta':'Requiere 2 corazones'}</button>`;}).join('')}</div><p class="small-text">Camina con WASD o flechas. Haz clic en quien esté en casa para conversar.</p><button class="btn" data-do="salir">Salir al barrio</button></div>`;}
