// Ronda 3 · ¿Cuánto me conoces? Uno contesta sobre sí mismo (en secreto) y el otro adivina.
// Con opciones se compara solo; las abiertas (sin opciones) las escribe cada uno y las califica el dueño de la respuesta.
import { type Categoria, idDe, type PConoce, type Rol } from './tipos';

type Fila = [texto: string, opciones: string[] | null, de?: Rol];
const de = (cat: Categoria, lista: Fila[]): PConoce[] =>
  lista.map(([t, o, quien]) => ({ id: idDe('conoce', t), tipo: 'conoce', cat, t, o, ...(quien ? { de: quien } : {}) }));

export const CONOCE: PConoce[] = [
  ...de('divertidas', [
    ['¿Qué hace {n} cuando está estresad{o|a}?', ['Come', 'Duerme', 'Habla sin parar', 'Se encierra en el celular']],
    ['¿Cuál es el color favorito de {n}?', ['Negro', 'Rosado', 'Azul', 'Morado']],
    ['¿Qué superpoder escogería {n}?', ['Volar', 'Teletransportarse', 'Leer mentes', 'Detener el tiempo']],
    ['¿Qué le da más miedo a {n}?', ['Las cucarachas voladoras', 'La oscuridad', 'Las alturas', 'Quedarse sin batería']],
    ['Si {n} se encuentra un millón de pesos, ¿qué hace?', ['Se lo gasta en comida', 'Lo ahorra', 'Le compra algo a {otro}', 'Busca al dueño']],
    ['¿Cuál es la peor maña de {n} al dormir?', ['Roncar', 'Robarse la cobija', 'Patear', 'Hablar dormid{o|a}']],
    ['¿Qué es lo primero que hace {n} al despertarse?', ['Mirar el celular', 'Ir al baño', 'Volverse a dormir', 'Escribirle a {otro}']],
    ['¿Qué película escogería {n} un domingo?', ['Terror', 'Comedia romántica', 'Acción', 'Una de Disney']],
    ['¿Cómo se pone {n} cuando tiene hambre?', ['Bravísim{o|a}', 'Triste', 'Dramátic{o|a}', 'Ni se le nota']],
    ['¿Qué materia odiaba más {n} en el colegio?', ['Matemáticas', 'Artística', 'Educación física', 'Química']],
    ['¿Qué aplicación abre más {n}?', ['WhatsApp', 'TikTok', 'Instagram', 'YouTube']],
    ['¿Qué animal sería {n}?', ['Un panda', 'Una pulga aventurera', 'Un perro lanudo', 'Un gato perezoso']],
    ['¿Qué le molesta más a {n}?', ['Que l{o|a} dejen en visto', 'Que mastiquen duro', 'La impuntualidad', 'Que le toquen la comida']],
    ['¿Cuál es el lugar favorito de {n} en la casa?', ['La cama', 'La cocina', 'El sofá', 'El baño (sí, el baño)']],
    ['¿Qué canción cantaría {n} en un karaoke?', ['Una de Shakira', 'Un vallenato', 'Un reguetón', 'Una de Disney']],
    ['¿Qué hace {n} si ve una cucaracha voladora?', ['Grita', 'Se va del país', 'La mata como guerrer{o|a}', 'Llama a {otro}']],
    ['¿Qué personaje de Disney sería {n}?', ['Una princesa', 'Stitch', 'Olaf', 'El genio de Aladino']],
    ['¿Qué emoji usa más {n}?', ['😂', '❤️', '🥺', '😒']],
    ['¿Qué hace {n} cuando pierde en un juego de mesa?', ['Pide revancha', 'Se ríe', 'Dice que hubo trampa', 'Se hace {el|la} que no le importa']],
    ['¿Qué música pone {n} para hacer aseo?', ['Reguetón', 'Vallenato', 'Salsa', 'Baladas para llorar']],
    ['¿Qué nunca le falta a {n} en el bolso o el morral?', ['El cargador', 'Algo de comer', 'Brillo de labios', 'Los audífonos']],
    ['¿Qué hace {n} apenas llega a una fiesta?', ['Busca la comida', 'Saluda a todo el mundo', 'Busca dónde sentarse', 'Se va a bailar']],
    ['¿Qué haría {n} si fuera invisible un día?', ['Comer gratis', 'Espiar a {otro}', 'Hacer bromas', 'Dormir sin que nadie moleste']],
    ['¿Qué hace {n} cuando está feliz?', ['Canta', 'Baila', 'Habla sin parar', 'Abraza a todo el mundo']],
    ['¿Qué le cuesta más a {n}?', ['Madrugar', 'Ahorrar', 'Decidir qué comer', 'Quedarse callad{o|a}']],
    ['Cuando {n} se enferma, es…', ['Un bebé', 'Un guerrero silencioso', 'Un drama total', 'Ni se le nota']],
    ['¿Qué haría {n} en un apocalipsis zombie?', ['Esconderse', 'Liderar al grupo', 'Ser el primero en caer', 'Salvar al perrito']],
    ['¿Qué videojuego escogería {n}?', ['Transformice', 'Mario Kart', 'Free Fire', 'Los Sims']],
    ['¿Qué hace {n} cuando no puede dormir?', ['Mira TikTok', 'Piensa en la vida', 'Come', 'Le escribe a {otro}']],
    ['¿Qué tan rápido contesta {n} un mensaje?', ['Al segundo', 'En una hora', 'Cuando se acuerda', 'Lo deja en visto']],
    ['¿Qué ropa prefiere {n} un día cualquiera?', ['Pijama', 'Sudadera', 'Algo elegante', 'Lo que esté limpio']],
    ['¿Qué haría {n} si viera un ratón en la cocina?', ['Gritar', 'Subirse a una silla', 'Atraparlo', 'Hacerse amig{o|a} de él, como en Transformice']],
    ['¿A qué hora se acuesta {n} normalmente?', ['Antes de las diez', 'Cerca de las doce', 'A la una', 'Cuando sale el sol']],
    ['¿Qué haría {n} si se ganara la lotería?', ['Comprar casa', 'Viajar por el mundo', 'Ayudar a la familia', 'Montar un negocio']],
  ]),
  ...de('romanticas', [
    ['¿Qué le gusta más a {n} de {otro}?', ['La sonrisa', 'Los ojos', 'Cómo l{a|o} cuida', 'Su humor']],
    ['¿Qué es lo primero que {n} notó de {otro}?', ['Su forma de hablar', 'Su inteligencia', 'Su sonrisa', 'Su paciencia']],
    ['¿Qué apodo le gusta más a {n} que le digan?', ['Mi amor', 'Su apodo de siempre', 'Bebé', 'Su nombre, dicho bonito']],
    ['¿Qué le encanta a {n} que {otro} le haga?', ['Cosquillas', 'Cariñitos en el pelo', 'Comida rica', 'Mensajes bonitos']],
    ['¿Qué haría feliz a {n} en cinco minutos?', ['Algo de comer', 'Un abrazo', 'Un detallito', 'Dejarl{o|a} dormir']],
    ['¿Cómo celebraría {n} su cumpleaños ideal?', ['Restaurante elegante', 'Fiesta grande', 'Un viaje', 'Plan tranquilo con {otro}']],
    ['¿Qué le daría más pesar a {n}?', ['Perder el celular', 'Quemar la comida', 'Ver triste a {otro}', 'Perder en un juego']],
    ['¿Qué haría {n} en un día libre sin {otro}?', ['Dormir todo el día', 'Ver series', 'Salir con amigos', 'Extrañar a {otro}']],
  ]),
  ...de('comida', [
    ['¿Cuál es la fruta favorita de {n}?', ['Mango', 'Fresa', 'Mandarina', 'Banano']],
    ['Si {n} solo pudiera comer una cosa toda la vida, sería…', ['Wafles', 'Pizza', 'Arepa con queso', 'Bandeja paisa']],
    ['¿Qué pide {n} en una heladería?', ['Fresa', 'Chocolate', 'Vainilla', 'Un poquito de cada uno']],
    ['¿Cómo se toma {n} el café?', ['Frappé', 'Tinto negro', 'Con leche', 'No toma café']],
    ['¿Cuál es la comida que menos le gusta a {n}?', ['Hígado', 'Brócoli', 'Sushi', 'Mondongo']],
    ['¿Cuál es el postre favorito de {n}?', ['Fresas con crema', 'Brownie', 'Torta de chocolate', 'Arroz con leche']],
    ['¿Qué parte del súper le encanta a {n}?', ['Los dulces', 'Las frutas', 'La panadería', 'Los congelados']],
    ['¿Qué cocina mejor {n}?', ['Huevos', 'Pasta', 'Arroz', 'Wafles']],
    ['¿Qué mecato compra {n} en la tienda?', ['Papitas', 'Chocolatina', 'Galletas', 'Gomitas']],
    ['¿De qué sabor pediría {n} un frappé?', ['Café', 'Oreo', 'Fresa', 'Caramelo']],
    ['¿Qué escoge {n} para una tarde de lluvia?', ['Cobija y película', 'Chocolate con pan', 'Dormir', 'Jugar algo']],
    ['¿Cuántos frappés se tomaría {n} en un día si pudiera?', ['Uno', 'Tres', 'Cinco', 'Todos los de la tienda'], 'el'],
    ['¿Qué haría {n} por un frappé extra?', ['Lavar los platos', 'Cantar una canción', 'Hacer un masaje', 'Lo que sea'], 'el'],
  ]),
  ...de('futuro', [
    ['¿A qué país viajaría {n} primero?', ['Países Bajos (¡tierra de los liefje!)', 'Japón', 'Estados Unidos', 'Italia']],
    ['¿Cuál sería el trabajo soñado de {n}?', ['Psicólog{o|a}', 'Chef', 'Influencer', 'Viajer{o|a} profesional']],
    ['¿Qué carro le gustaría tener a {n}?', ['Una camioneta', 'Un carrito rosado', 'Una moto', 'Le da igual']],
    ['¿Dónde le gustaría vivir a {n}?', ['Sopetrán', 'Bucaramanga', 'Medellín', 'Otro país']],
    ['¿Qué tipo de papá o mamá va a ser {n}?', ['Alcahuete', 'Estricto', 'Chistoso', 'Preocupón']],
    ['¿Qué le enseñaría {n} primero a la bebé?', ['A bailar', 'A contar', 'A comer wafles', 'A decir «te amo»']],
  ]),
  ...de('colombianas', [
    ['¿Qué plan escoge {n} para un sábado?', ['Ir al súper y cocinar', 'Rumbear', 'Maratón de series', 'Paseo a tierra caliente']],
    ['¿Qué serie vería {n} completa en un día?', ['Una de misterio', 'Una novela colombiana', 'Una de comedia', 'Un anime']],
    ['¿Qué diría {n} si se pega en el dedo chiquito del pie?', ['¡Ay, Dios mío!', '¡Ave María!', '¡Hijuepucha!', 'Nada: llora en silencio']],
    ['En una fiesta de diciembre, {n} es quien…', ['Prende la pólvora', 'Reparte la natilla', 'Baila con la tía', 'Se queda dormid{o|a}']],
  ]),
  ...de('picantes', [
    ['¿Qué le parece más coqueto a {n}?', ['Una mirada', 'Una sonrisa', 'Un perfume rico', 'Que l{o|a} hagan reír']],
    ['¿Dónde le gustaría más a {n} recibir un beso sorpresa?', ['En la frente', 'En el cachete', 'En la boca', 'En la mano, de caballero']],
  ]),
  ...de('recuerdos', [
    ['Según {n}, ¿quién se dio cuenta primero de que estaban enamorados?', ['Ella', 'Él', 'Los dos al tiempo', 'El perrito']],
    ['¿Qué es lo que más extraña {n} de las videollamadas de la pandemia?', ['Despertarse juntos', 'Estudiar juntos', 'Comer juntos', 'Todo']],
    ['¿Cuánto se demora {n} maquillándose para una salida especial?', ['Veinte minutos', 'Una hora', 'Dos horas', 'Una eternidad y media'], 'ella'],
    ['¿Qué producto de Yanbal no le puede faltar a {n}?', ['Labial', 'Perfume', 'Base', 'Pestañina'], 'ella'],
    ['¿Qué parte de su maquillaje le gusta más a {n}?', ['Los ojos', 'Los labios', 'Las cejas', 'El rubor'], 'ella'],
    ['Cuando {otro} intentó peinarla, ¿cómo calificaría {n} el resultado?', ['Desastre total', 'Medio desastre', 'Pasable', 'Peinado de revista'], 'ella'],
    ['Si {n} vuelve a ver un iPhone súper barato en internet, ¿qué hace?', ['Lo compra (otra vez)', 'Lo denuncia', 'Le pregunta a {otro}', 'Se ríe sola'], 'ella'],
    ['¿Qué materia explicaba mejor {n} para el ICFES?', ['Matemáticas', 'Física', 'Filosofía', 'Todas, obvio'], 'el'],
    ['¿Qué le gusta más a {n} de visitar a {otro} en Sopetrán?', ['Ir juntos al súper', 'Cocinar juntos', 'El calorcito', 'Todo'], 'el'],
    ['Cuando {n} le hizo las uñas a {otro}, ¿cómo quedaron?', ['Perfectas', 'Bonitas pero chuecas', 'Como pintadas por un niño', 'Mejor ni hablar'], 'el'],
  ]),
  // Abiertas: cada uno escribe y el dueño de la respuesta califica (exacto, casi o ni cerca)
  ...de('divertidas', [
    ['¿Qué palabra o frase dice {n} todo el tiempo?', null],
    ['Si {n} escribiera un libro sobre su vida, ¿cómo se llamaría?', null],
    ['¿Cuál es la canción que {n} canta en la ducha?', null],
    ['¿Cuál es la manía más rara de {n}?', null],
    ['¿Qué le pediría {n} al genio de la lámpara?', null],
    ['¿Qué famoso haría el papel de {n} en la película de su vida?', null],
    ['¿Qué haría {n} si fuera presidente de Colombia por un día?', null],
    ['¿Cuál es el momento más vergonzoso de {n} delante de {otro}?', null],
    ['¿Qué es lo que más le da risa a {n}?', null],
    ['¿Cómo se llamaría el restaurante de {n}?', null],
  ]),
  ...de('romanticas', [
    ['¿Qué canción le recuerda a {n} a {otro}?', null],
    ['¿Cuál es el recuerdo más bonito de {n} con {otro}?', null],
    ['¿Qué es lo que más extraña {n} cuando están lejos?', null],
    ['¿Qué apodo nuevo le pondría {n} a {otro}?', null],
    ['¿Cuál es la frase que más le dice {n} a {otro}?', null],
    ['¿Cuál fue el mejor regalo que ha recibido {n}?', null],
  ]),
  ...de('comida', [
    ['¿Qué pediría {n} como última cena de su vida?', null],
    ['¿Cuál es el antojo más raro que ha tenido {n}?', null],
    ['Si {n} fuera un postre, ¿cuál sería?', null],
    ['¿Cuál es el plato que mejor le queda a {n}?', null],
  ]),
  ...de('futuro', [
    ['¿Cuál es el sueño más loco de {n}?', null],
    ['¿Qué lugar del mundo quiere conocer {n} antes que cualquier otro?', null],
    ['¿Qué le gustaría aprender a {n} este año?', null],
    ['¿Qué nombre le pondría {n} a un segundo perrito?', null],
    ['¿Qué es lo primero que haría {n} al despertarse en la casa de los dos?', null],
    ['¿Qué le diría {n} a su versión de quince años?', null],
  ]),
  ...de('colombianas', [
    ['¿Qué tres cosas se llevaría {n} a una isla desierta?', null],
    ['¿Cuál es la serie o película favorita de {n}?', null],
    ['¿Qué haría {n} con un día libre sin responsabilidades?', null],
  ]),
];
