// Ronda 5 · Nuestra historia: preguntas de sus recuerdos de verdad (docs/cien-puertas.md y docs/la-pareja.md).
// Tienen respuesta correcta (`ok`, la posición en las opciones) y un datico que dice el presentador al revelarla.
// Lo difícil que han vivido se cuenta con ternura y nunca en chiste.
import { type Categoria, idDe, type PHistoria } from './tipos';

type Fila = [texto: string, opciones: string[], ok: number, dato: string];
const de = (cat: Categoria, lista: Fila[]): PHistoria[] => lista.map(([t, o, ok, dato]) => ({ id: idDe('historia', t), tipo: 'historia', cat, t, o, ok, dato }));

export const HISTORIA: PHistoria[] = [
  ...de('recuerdos', [
    ['¿En qué juego se conocieron?', ['Free Fire', 'Transformice', 'Minecraft', 'Club Penguin'], 1, 'Transformice: ratoncitos, queso… y amor del bueno.'],
    ['¿En qué parte de Transformice empezó todo?', ['En la villa, la que parece un barcito', 'En el mapa del queso gigante', 'En la tienda de sombreros', 'En una partida de chamanes'], 0, 'En la villa. El barcito más romántico de internet.'],
    ['¿Qué día se conocieron?', ['25 de octubre', '14 de febrero', '15 de septiembre', '31 de octubre'], 2, 'Un 15 de septiembre. Un día cualquiera… que dejó de serlo.'],
    ['¿Qué día se volvieron novios?', ['15 de septiembre', '25 de octubre', '24 de diciembre', '1 de noviembre'], 1, 'El 25 de octubre. Desde ahí, todo.'],
    ['¿Cuántos días pasaron del 15 de septiembre al 25 de octubre?', ['Treinta (según Él)', 'Cuarenta', 'Veinte', 'Cien'], 1, 'Cuarenta. El de las matemáticas contó mal… porque con ella el tiempo vuela.'],
    ['¿Qué quería hacer Ella al principio en la villa?', ['Pedirle el número', 'Estafarlo, un poquito', 'Enseñarle a jugar', 'Venderle un sombrero'], 1, 'Quería robarle las cositas del juego… y él le robó el corazón.'],
    ['¿Qué le dijo Él cuando le dio todas sus cosas del juego?', ['«Te las presto»', '«Estás como necesitada, así que ten»', '«Cásate conmigo»', '«Devuélvemelas mañana»'], 1, '«Estás como necesitada, así que ten». Un acto de caridad, dice Él.'],
    ['¿Quién se dio cuenta de la estafa en Transformice?', ['Nadie', 'Él, el primero y el único', 'El chamán', 'La mamá de Ella'], 1, 'Él, el primero y el único. Ella pensó: «este hombre es muy inteligente».'],
    ['¿De qué le habló Él esa primera noche?', ['De fútbol', 'De matemáticas y filosofía', 'De carros', 'De su ex'], 1, 'Matemáticas y filosofía. «La filosofía no sé. El filósofo, tal vez».'],
    ['¿Qué se les olvidó hacer esa primera noche en el juego?', ['Despedirse', 'Agregarse de amigos', 'Guardar la partida', 'Comer'], 1, 'No se agregaron de amigos. Al otro día ella lo buscó por todo el juego.'],
    ['¿Qué le dio Él cuando por fin se reencontraron?', ['Su contraseña del juego', 'Su número de teléfono', 'Un queso dorado', 'Su correo del colegio'], 1, 'Su número. «Punto para las matemáticas».'],
    ['¿Cómo era Él al principio, según Ella?', ['Un intenso', 'Un témpano de hielo', 'Un chistoso', 'Un poeta'], 1, 'Un témpano de hielo… que ella derritió poquito a poquito.'],
    ['En la pandemia, ¿cuánto duraban sus videollamadas?', ['Media hora', 'Dos horas', 'Casi 24 horas… o 24, según Ella', 'Solo los domingos'], 2, 'Dormían, estudiaban y comían juntos. Lo único bueno de la pandemia.'],
    ['¿Qué tareas le hacía Ella a Él en el colegio?', ['Las de matemáticas', 'Las de artística', 'Las de inglés', 'Ninguna'], 1, 'Las de artística. Y él… «casi todas» las de ella.'],
    ['¿Para qué examen estudiaron juntos?', ['El ICFES', 'El de la licencia', 'El de inglés', 'El de cocina'], 0, 'El ICFES: él explicaba y ella ponía lo más importante, las ganas de estar con él.'],
    ['¿En qué año estaban los dos en once?', ['2019', '2020', '2021', '2022'], 2, '2021: graduados el mismo año, como debía ser.'],
    ['¿Qué carrera estudia Ella?', ['Medicina', 'Psicología', 'Derecho', 'Diseño'], 1, 'Psicología, en la universidad que quería, donde quería.'],
    ['¿Qué día presentó Ella el examen de la universidad?', ['El día de su cumpleaños', 'El 25 de octubre', 'Un lunes festivo', 'En Navidad'], 0, 'El día de su cumpleaños… ¡y pasó! El mejor regalo.'],
    ['¿Qué quería Ella después de graduarse?', ['Viajar por Europa', 'Un año sabático', 'Casarse de una', 'Trabajar en un banco'], 1, 'Un año sabático. Él no paró hasta convencerla: persistente, no insistente.'],
    ['Según Él, ¿cómo es Él cuando quiere algo?', ['Insistente', 'Persistente', 'Intenso', 'Desesperado'], 1, '«Persistente, que es distinto». Ella sigue sin creerle.'],
    ['¿De qué empresa llegó a ser directora Ella?', ['Avon', 'Yanbal', 'Natura', 'Ésika'], 1, 'Directora de Yanbal: casi un año de trabajo y lo logró.'],
    ['¿Cuándo se cumplía la meta de directora?', ['En junio', 'En diciembre, justo antes de Cartagena', 'En su cumpleaños', 'En Halloween'], 1, 'En diciembre. A los dos días ya iban para Cartagena.'],
    ['¿Cuál fue su primer viaje de playa juntos?', ['Santa Marta', 'San Andrés', 'Cartagena', 'Coveñas'], 2, 'Cartagena: solo los dos, el mar y el castillo.'],
    ['La noche del problema con el vuelo, ¿dónde durmió Ella?', ['En un hotel cinco estrellas', 'En una banca de piedra del aeropuerto', 'Donde una tía', 'En un taxi'], 1, 'En una banca de piedra… mientras él dormía en un cinco estrellas. Todavía duele.'],
    ['¿Y dónde durmió Él esa noche?', ['En el aeropuerto con ella', 'En un hotel cinco estrellas que le dio la aerolínea', 'En el bus', 'No durmió'], 1, '«Te pensé toda la noche… desde la cama grandota». La próxima vez duerme él en la banca. Prometido.'],
    ['¿Qué alquilaron en Cartagena?', ['Una chiva', 'Una moto acuática', 'Un velero', 'Una bicicleta doble'], 1, 'Una moto acuática: salieron volando por el mar.'],
    ['¿Qué lugar de Cartagena la tenía mirando todo como niña chiquita?', ['El castillo', 'El acuario', 'Un centro comercial', 'El aeropuerto'], 0, 'El castillo. «Allá me sentí yo, contigo».'],
    ['¿Con quién hicieron los alumbrados de diciembre que fueron a ver en Medellín?', ['Marvel', 'Disney', 'Pokémon', 'Harry Potter'], 1, 'Con Disney. Él dice que solo veía cómo le brillaban los ojos a ella.'],
    ['¿En qué pueblo vive Ella?', ['Santa Fe de Antioquia', 'Sopetrán', 'Guatapé', 'Jardín'], 1, 'Sopetrán, tierra caliente y de gente linda.'],
    ['¿En qué ciudad vive Él?', ['Cúcuta', 'Bogotá', 'Bucaramanga', 'Medellín'], 2, 'Bucaramanga, la ciudad bonita.'],
    ['Según Ella, ¿cuántas horas hay de Sopetrán a Bucaramanga?', ['Cinco', 'Ocho… si el bus no para', 'Doce', 'Una por avión'], 1, 'Ocho, dice ella. Nueve, dice él. «El bus siempre para».'],
    ['¿Qué son ellos dos, según su recuerdo de la distancia?', ['Polos opuestos sin remedio', 'El complemento', 'Rivales de parqués', 'Vecinos lejanos'], 1, 'Lo que no tiene uno lo tiene el otro: el complemento.'],
    ['¿Cómo se visten siempre en Halloween?', ['De zombies', 'Elegantes', 'De superhéroes', 'De Transformice'], 1, 'Elegantes. Y ese vestido… «me derrite».'],
    ['¿Qué le dice Él cuando la ve en su vestido de Halloween?', ['«Te ves cansada»', '«Me derrite»', '«¿Ya nos vamos?»', '«¿Es nuevo?»'], 1, '«Me. De. Rri. Te». Ella siempre pide que lo repita.'],
    ['¿A dónde la llevó Él en su cumpleaños de reina?', ['A un restaurante de súper lujo', 'A un concierto', 'A cine', 'A la feria'], 0, 'Un restaurante de súper lujo. Ella la reina; él el rey… que pagó la cuenta.'],
    ['¿Qué dice Ella que es Él para ella?', ['Su mejor amigo de Transformice', 'Sus oraciones respondidas', 'Su profesor favorito', 'Su chofer'], 1, 'Sus oraciones respondidas. Hasta lo de las tareas.'],
    ['¿Qué final le pide Ella a su cuento de hadas?', ['Uno de terror', 'Uno de Disney', 'Uno abierto', 'Uno con dragones'], 1, 'Un final de Disney. «Eso déjamelo a mí», dijo Él.'],
    ['¿A dónde fueron la primera vez que Él fue a Medellín?', ['Al Parque Explora y su planetario', 'Al estadio', 'A Guatapé', 'Al metrocable'], 0, 'Al planetario. ¿Él vio alguna estrella o solo la miraba a ella?'],
    ['Cuando todo se pone difícil, ¿qué es Él para Ella?', ['Su pilar', 'Su descanso', 'Su abrazo', 'Su refugio'], 0, 'Su pilar. Y ella el hogar de él: por eso siempre vuelven a casa.'],
    ['¿Qué estaban comiendo la noche de la propuesta?', ['Pizza', 'Picada', 'Sushi', 'Wafles'], 1, 'Picada. El plan más de ellos posible.'],
    ['¿Cómo estaba vestida Ella cuando le propusieron matrimonio?', ['De gala', 'En pijama', 'Con disfraz', 'De deportes'], 1, 'En pijama y «toda desarreglada». Él dice que estaba perfecta.'],
    ['¿Qué pensó Ella que había en la cajita?', ['Unos aretes o una cadena', 'Un reloj', 'Un queso de Transformice', 'Plata'], 0, 'Aretes, una cadena… pero una vocecita le decía: es el anillo. Y era el anillo.'],
    ['¿Dónde estaba arrodillado Él en la propuesta?', ['En un restaurante', 'En la playa', 'En la cama', 'En el parque'], 2, 'En la cama, con ella sentada. Tan de ellos.'],
    ['¿Cuánto lloró Ella en la propuesta, según Ella?', ['Nada', 'Lo justo', 'Un río', 'Solo una lágrima'], 1, '«¡Lloré lo justo!» (Él dice que muchísimo).'],
    ['¿Cómo se va a llamar la bebé que sueñan?', ['Katherine o Lexy Katherine', 'Luna', 'Sofía', 'Valentina'], 0, 'Katherine… o Lexy Katherine. La pelea más bonita de la casa.'],
    ['¿De dónde sale el «Lexy» de Lexy Katherine?', ['De una novela', 'De Alexis, el segundo nombre de Él', 'De una cantante', 'De un personaje de Transformice'], 1, 'De Alexis, el segundo nombre de Él. Y con L por la tradición de la familia de Ella.'],
    ['¿Qué es lo que más ama Él de Ella?', ['Su cocina', 'Sus labios y su sonrisa', 'Su letra', 'Sus memes'], 1, 'Sus labios y su sonrisa: cada vez que sonríe, él se vuelve a enamorar.'],
    ['¿Cuál es el plan favorito de Ella?', ['Ir de rumba', 'Estar abrazados en camita sin hacer nada', 'Ir de compras', 'Madrugar a trotar'], 1, 'Abrazados en camita: plan perfecto para el resto de la vida.'],
    ['La primera vez que Él la vio, ¿cómo fue?', ['Como ver a la mujer más hermosa del mundo', 'Normal', 'No la reconoció', 'Se quedó dormido'], 0, '«Eras perfecta». — «¿Era?». — «Eres. Presente. Siempre presente».'],
    ['Cuando Ella viajó a Bucaramanga en los días difíciles, ¿qué pensaba?', ['«Ojalá el bus vuele»', '«Cuando lo vea, todo va a ser más fácil»', '«Le llevo algo rico»', '«Lo voy a abrazar fuerte»'], 1, 'Y así fue. Siempre es así.'],
  ]),
  ...de('comida', [
    ['¿Qué le encanta a Ella más que casi nada?', ['El sushi', 'Los wafles', 'La bandeja paisa', 'El tamal'], 1, 'Los wafles. Él le prometió hacérselos cada vez que quiera.'],
    ['¿Con qué recibe siempre Ella a Él después del trabajo?', ['Un tinto', 'Un frappé de café', 'Una aguapanela', 'Una pola'], 1, 'Un frappé de café. Amor en vaso con pitillo.'],
    ['¿Qué le mandó Él de sorpresa en Amor y Amistad?', ['Rosas', 'Fresas con crema gigantes con un wafle', 'Un peluche', 'Una torta'], 1, '…y ella no sabía que eran de él. «Eso fue este año, tú, pulelo».'],
    ['¿Qué hacen siempre que Él la visita en Sopetrán?', ['Ir al súper a comprar de todo para cocinar juntos', 'Ir a cine', 'Ir a misa', 'Dormir todo el día'], 0, 'Súper, carrito lleno y a cocinar juntitos. Por eso existe Súper Manía.'],
  ]),
  ...de('divertidas', [
    ['¿Qué intentó Él hacerle a Ella… y no salió bien?', ['Una torta', 'Las uñas y peinarla', 'Un tatuaje', 'Cortarle el pelo'], 1, 'Las uñas y el peinado. Ninguna de las dos. Pero con mucho amor.'],
    ['¿Qué marca de maquillaje usa siempre Ella?', ['Yanbal', 'Maybelline', 'MAC', 'La que esté en oferta'], 0, 'Yanbal, obvio: fue directora.'],
    ['¿Qué pasó cuando Ella quiso comprar un iPhone súper barato?', ['Le llegó perfecto', 'La estafaron', 'Le llegó un ladrillo de regalo', 'Se lo ganó en una rifa'], 1, 'La estafaron. La mejor guerrera de Dios… y protagonista de su propia novela.'],
    ['¿De qué ha saltado Ella, digna protagonista?', ['De un paracaídas', 'De carros en movimiento', 'De un puente', 'De una chiva'], 1, 'De carros en movimiento. No lo intenten en casa.'],
    ['¿Cómo era el mar el día que Ella se metió?', ['Una piscina', 'Con olas de diez metros', 'Congelado', 'Lleno de delfines'], 1, 'Olas de diez metros. Pulga aventurera de verdad.'],
    ['¿Qué pasa cuando pierden en los juegos de mesa?', ['Se dejan de hablar', 'Nunca se enojan', 'Rompen el tablero', 'Lloran una semana'], 1, 'Nunca se enojan. Drama de mentiras, sí; cariño de verdad, siempre.'],
    ['¿Qué significa «liefje», como le dice Ella a Él?', ['Gordito', 'Amorcito, en holandés', 'Pandita, en alemán', 'Perro lanudo, en sueco'], 1, 'Amorcito, en holandés (aunque él lo escriba «liefte»).'],
    ['¿Cómo le dice Él a Ella cuando le pasa de todo?', ['La protagonista', 'La despistada', 'La reina del drama', 'La salada'], 0, 'La protagonista… y la mejor guerrera de Dios.'],
  ]),
];
