// Ronda 2 · ¿Qué prefieres? Cada uno escoge por sí mismo y además adivina lo que escogió el otro.
import { type Categoria, idDe, type PPrefiere } from './tipos';

const de = (cat: Categoria, lista: [string, string, string][]): PPrefiere[] =>
  lista.map(([t, a, b]) => ({ id: idDe('prefiere', `${t}|${a}|${b}`), tipo: 'prefiere', cat, t, o: [a, b] }));

export const PREFIERE: PPrefiere[] = [
  ...de('divertidas', [
    ['¿Qué superpoder prefieres?', 'Volar', 'Teletransportarse'],
    ['¿Qué prefieres saber?', 'Todos los idiomas del mundo', 'Tocar todos los instrumentos'],
    ['¿Qué mascota prefieres?', 'Un perrito', 'Un gatico'],
    ['¿Qué película prefieres un viernes?', 'Terror con las luces apagadas', 'Comedia romántica con cobija'],
    ['Si pudieras viajar en el tiempo…', 'Al pasado', 'Al futuro'],
    ['¿Qué prefieres?', 'Una semana sin celular', 'Una semana sin dulce'],
    ['¿Qué prefieres?', 'Madrugar y aprovechar el día', 'Trasnochar hablando hasta las 3'],
    ['¿Qué prefieres?', 'Hablar con los animales', 'Leer la mente'],
    ['¿Qué prefieres?', 'Ser famoso', 'Ser millonario sin que nadie sepa'],
    ['¿Dónde prefieres vivir un año?', 'En un castillo embrujado', 'En una cabaña frente al mar'],
    ['En una película de miedo, prefieres…', 'Zombies', 'Fantasmas'],
    ['¿Qué plan prefieres un domingo?', 'Maratón de series en pijama', 'Paseo de olla al río'],
    ['¿Qué concierto prefieres?', 'Karol G', 'Carlos Vives'],
    ['En una fiesta, prefieres…', 'Cantar karaoke delante de todos', 'Bailar en la mitad de la pista'],
    ['¿Qué prefieres ser?', 'El que cuenta los chistes', 'El que se ríe de todo'],
    ['¿Qué prefieres?', 'Ducha bien caliente', 'Ducha fría en tierra caliente'],
    ['¿Qué juego prefieres?', 'Transformice otra vez', 'Parqués con toda la familia'],
    ['¿Qué prefieres?', 'Ganar siempre al parqués', 'Ganar siempre al Dados Party'],
    ['¿Qué prefieres encontrarte en la calle?', 'Un billete de cien mil', 'Un perrito perdido que te adopta'],
    ['¿Qué prefieres?', 'Que nunca se te descargue el celular', 'Que nunca se te acabe el internet'],
  ]),
  ...de('romanticas', [
    ['¿Cuál es la cita perfecta?', 'Picnic en el parque', 'Cena elegante con velas'],
    ['¿Qué regalo prefieres?', 'Algo hecho a mano', 'Algo que vio en una vitrina y supo que te iba a gustar'],
    ['¿Qué prefieres recibir?', 'Una carta de amor escrita a mano', 'Una canción dedicada'],
    ['¿Qué prefieres?', 'Un abrazo largo', 'Un beso largo'],
    ['¿Qué prefieres?', 'Que te digan «te amo»', 'Que te lo demuestren con detalles'],
    ['¿Qué sorpresa prefieres?', 'Desayuno en la cama', 'Cena sorpresa'],
    ['¿Qué prefieres ver juntos?', 'El atardecer', 'Las estrellas'],
    ['¿Qué prefieres?', 'Bailar lento en la sala', 'Cantar a dúo en el carro'],
    ['Estando lejos, prefieres…', 'Una videollamada de tres horas', 'Un audio de diez minutos'],
    ['¿Qué prefieres?', 'Una sorpresa planeada', 'Un plan improvisado'],
    ['¿Qué detalle prefieres?', 'Flores', 'Chocolates'],
    ['¿Qué recuerdo prefieres?', 'Una foto juntos en un mirador', 'Un video de los dos muertos de la risa'],
    ['Para el aniversario, prefieres…', 'Un viaje', 'Una cena en casa hecha por los dos'],
    ['¿Cómo prefieres que te llamen?', 'Por tu apodo', 'Por tu nombre, dicho bonito'],
    ['¿Cómo prefieres dormir?', 'Abrazados toda la noche', 'Cada uno en su lado, tomados de la mano'],
    ['¿Qué prefieres?', 'Una noche de juegos de mesa', 'Una noche de películas'],
  ]),
  ...de('futuro', [
    ['¿Dónde prefieres casarte?', 'En la playa', 'En una iglesia'],
    ['¿Qué luna de miel prefieres?', 'Europa', 'San Andrés'],
    ['¿Dónde prefieres vivir?', 'En la ciudad', 'En una finca'],
    ['¿Qué casa prefieres?', 'Una casa con jardín grande', 'Un apartamento con vista'],
    ['¿Qué prefieres en el futuro?', 'Un perro grandote', 'Un gatito y un perrito'],
    ['¿Qué carro familiar prefieres?', 'Una camioneta grande', 'Un carrito pequeño y ahorrador'],
    ['¿Qué prefieres?', 'Trabajar desde la casa', 'Trabajar en una oficina'],
    ['¿Qué prefieres?', 'Vivir en Colombia', 'Vivir en otro país'],
    ['¿Qué fiesta de matrimonio prefieres?', 'Grande, con toda la familia', 'Pequeña, con los más cercanos'],
    ['Para viejitos, prefieres…', 'Una casita frente al mar', 'Una finquita en el campo'],
    ['¿Qué vacaciones en familia prefieres?', 'Disney', 'El Eje Cafetero'],
    ['Para el cumpleaños de la bebé, prefieres…', 'Payasos y piñata', 'Princesas de Disney'],
    ['¿Qué cocina prefieres en la casa?', 'Abierta a la sala', 'Cerrada, con su puerta'],
    ['¿Qué decoración prefieres?', 'Colores pastel', 'Blanco y madera'],
    ['¿Qué prefieres?', 'Que la bebé saque los ojos de papá', 'Que saque la sonrisa de mamá'],
    ['¿Qué prefieres?', 'Viajar mucho antes de tener hijos', 'Tener hijos jóvenes y viajar con ellos'],
  ]),
  ...de('comida', [
    ['¿Qué desayuno prefieres?', 'Wafles con fresas', 'Arepa con queso y mantequilla'],
    ['¿Qué bebida prefieres?', 'Frappé de café', 'Chocolate caliente con queso'],
    ['¿Qué desayuno prefieres un domingo?', 'Calentado', 'Huevos pericos con arepa'],
    ['¿Qué almuerzo prefieres?', 'Bandeja paisa', 'Ajiaco'],
    ['¿Qué prefieres?', 'Empanada', 'Buñuelo'],
    ['¿Qué prefieres?', 'Pizza', 'Hamburguesa'],
    ['¿Qué prefieres?', 'Dulce', 'Salado'],
    ['¿Qué prefieres?', 'Sushi', 'Salchipapa'],
    ['¿Qué postre prefieres?', 'Fresas con crema', 'Brownie con helado'],
    ['¿Qué prefieres?', 'Mango biche con sal', 'Cholado'],
    ['¿Qué prefieres?', 'Tinto', 'Aguapanela'],
    ['¿Qué prefieres?', 'Comer en la calle', 'Cocinar juntos en la casa'],
    ['¿Qué prefieres?', 'Pollo asado', 'Lechona'],
    ['En diciembre, prefieres…', 'Natilla', 'Buñuelos'],
    ['¿Qué mecato de paseo prefieres?', 'Papitas', 'Chocorramo'],
    ['¿Qué pan prefieres?', 'Pandebono', 'Almojábana'],
    ['¿Qué prefieres?', 'Arroz con leche', 'Flan'],
    ['¿Qué prefieres?', 'Salsa de tomate', 'Mayonesa'],
    ['¿Qué helado prefieres?', 'Vainilla', 'Chocolate'],
    ['¿Qué fruta prefieres?', 'Mango', 'Fresa'],
  ]),
  ...de('colombianas', [
    ['¿Qué fiesta prefieres?', 'La Feria de las Flores', 'El Carnaval de Barranquilla'],
    ['¿Qué música prefieres?', 'Salsa', 'Vallenato'],
    ['¿Qué prefieres para bailar?', 'Reguetón', 'Champeta'],
    ['¿Qué playa prefieres?', 'Cartagena', 'Santa Marta'],
    ['¿Qué acento te parece más bonito?', 'El paisa', 'El santandereano'],
    ['¿Qué rumba prefieres?', 'Una chiva rumbera', 'Un yate en el mar'],
    ['¿Qué novela prefieres?', 'Betty la fea', 'Pasión de gavilanes'],
    ['¿Qué clima prefieres?', 'Tierra caliente, como Sopetrán', 'Templadito, como Bucaramanga'],
    ['En diciembre, prefieres…', 'Ver los alumbrados', 'Rezar las novenas'],
    ['¿Qué paseo prefieres?', 'El cañón del Chicamocha', 'La piedra de Guatapé'],
    ['¿Qué juego prefieres?', 'Tejo', 'Rana'],
    ['¿Qué prefieres probar?', 'Hormigas culonas', 'Chicharrón con arepa'],
    ['¿Qué prefieres ponerte?', 'Una ruana', 'Un sombrero vueltiao'],
    ['¿Cómo prefieres ver un partido de la Selección?', 'En el estadio', 'En la casa con mecato'],
  ]),
  ...de('picantes', [
    ['¿Qué prefieres?', 'Besos de piquito', 'Besos de película'],
    ['¿Qué prefieres?', 'Cosquillas', 'Masajes'],
    ['¿Qué te conquista más?', 'Una mirada coqueta', 'Una sonrisa coqueta'],
    ['¿Qué pijama prefieres?', 'De ositos', 'Elegante'],
    ['¿Qué prefieres?', 'Que te despierten a besos', 'Que te dejen dormir'],
    ['¿Cómo prefieres bailar?', 'Bien pegaditos', 'Separados haciendo payasadas'],
    ['¿Qué prefieres?', 'Un piropo al oído', 'Un piropo delante de todos'],
  ]),
  ...de('recuerdos', [
    ['Si pudieras volver a un lugar…', 'La villa de Transformice', 'Las playas de Cartagena'],
    ['¿Qué día repetirías?', 'El de la propuesta', 'El de la primera vez que se vieron'],
    ['¿Qué prefieres?', 'Videollamada de 24 horas', 'Visita de un fin de semana'],
    ['¿Qué prefieres?', 'Las luces de Disney en Medellín', 'El planetario del Parque Explora'],
    ['¿Qué Halloween prefieres?', 'Elegante, como siempre', 'De disfraces chistosos'],
    ['¿Qué prefieres?', 'La moto acuática', 'Un paseo tranquilo en lancha'],
    ['¿Qué prefieres?', 'Las tareas de artística', 'Las sesiones de estudio del ICFES'],
  ]),
];
