// Ronda 1 · ¿Quién es más probable? Los dos señalan en secreto a Él o a Ella; si coinciden, puntos para los dos.
import { type Categoria, idDe, type PQuien } from './tipos';

const de = (cat: Categoria, lista: string[]): PQuien[] => lista.map((t) => ({ id: idDe('quien', t), tipo: 'quien', cat, t }));

export const QUIEN: PQuien[] = [
  ...de('divertidas', [
    '¿Quién es más probable que se coma el último pedazo de torta a escondidas… y le eche la culpa al perrito?',
    '¿Quién se queda dormido primero viendo una película que escogió?',
    '¿Quién es más probable que se pierda aunque tenga el GPS prendido?',
    '¿Quién canta más duro en la ducha (y más desafinado)?',
    '¿Quién es más probable que le hable al perrito como si fuera un bebé?',
    '¿Quién deja la ropa en el piso «porque ahorita la recoge»?',
    '¿Quién es más probable que se ría en el momento más serio?',
    '¿Quién se pone más bravo cuando tiene hambre?',
    '¿Quién es más probable que compre algo que no necesita solo porque estaba en oferta?',
    '¿Quién es más probable que deje al otro en visto… estando en línea?',
    '¿Quién es más probable que se tropiece con algo que estaba quieto?',
    '¿Quién es más probable que diga «ya voy saliendo» cuando ni se ha bañado?',
    '¿Quién es más probable que llore con una película de Disney?',
    '¿Quién es más probable que gane una discusión sin tener la razón?',
    '¿Quién es más probable que haga trampa en un juego de mesa (y lo niegue)?',
    '¿Quién es más probable que se coma la comida del otro «solo para probar»?',
    '¿Quién es más probable que se duerma en el bus y se pase de la parada?',
    '¿Quién deja más platos «remojando» para no lavarlos?',
    '¿Quién es más probable que le invente una canción al perrito?',
    '¿Quién tiene la galería del celular más llena de capturas, memes y fotos borrosas?',
    '¿Quién es más probable que le dé like a una foto vieja por accidente mientras chismosea?',
    '¿Quién es más probable que hable dormido… y diga cosas sin sentido?',
    '¿Quién es más probable que pierda las llaves dentro de la misma casa?',
    '¿Quién es más probable que se ponga la ropa al revés y salga así a la calle?',
    '¿Quién es más probable que conteste «¿ah?» tres veces seguidas porque no estaba poniendo atención?',
    '¿Quién es más probable que se asuste con su propio reflejo de noche?',
    '¿Quién es más probable que se olvide del cargador en un viaje?',
  ]),
  ...de('romanticas', [
    '¿Quién se enamoró primero?',
    '¿Quién es más probable que planee una cita sorpresa?',
    '¿Quién es más detallista de los dos?',
    '¿Quién es más probable que llore en la boda?',
    '¿Quién escribe los mensajes más largos y bonitos?',
    '¿Quién guarda más recuerditos: tiquetes, servilletas, notas, empaques…?',
    '¿Quién da los abrazos que curan todo?',
    '¿Quién es más probable que se quede mirando al otro mientras duerme?',
    '¿Quién es más probable que mande un audio de cinco minutos diciendo «te amo» de mil formas?',
    '¿Quién dice primero «buenos días, mi amor» cada mañana?',
    '¿Quién es más probable que se aprenda una canción solo para dedicársela al otro?',
    '¿Quién es el más cursi de los dos?',
    '¿Quién se sonroja más fácil con un piropo?',
    '¿Quién es más probable que haga una carta de amor a mano?',
    '¿Quién es más probable que pida un abrazo «de esos largos» sin razón?',
  ]),
  ...de('futuro', [
    '¿Quién va a consentir más a la bebé?',
    '¿Quién va a cambiar más pañales (de verdad, no en promesas)?',
    '¿Quién va a ser el más estricto con las tareas de la niña?',
    '¿Quién va a llorar más el primer día de colegio de la bebé?',
    '¿Quién va a cocinar más en la casa de los dos?',
    '¿Quién va a decidir cómo se decora la casa?',
    '¿Quién va a querer tener más mascotas?',
    '¿Quién va a ganar la pelea del nombre: Katherine o Lexy Katherine?',
    '¿Quién va a ser el primero en levantarse cuando la bebé llore de noche?',
    '¿Quién va a manejar en los paseos familiares?',
    '¿Quién va a ser el abuelito más chocho?',
    '¿Quién le va a enseñar a la niña a jugar Transformice?',
    '¿Quién va a organizar las fiestas de cumpleaños de la bebé?',
    '¿Quién va a ser el más juicioso ahorrando para la casa?',
    '¿Quién va a querer irse más lejos a vivir?',
  ]),
  ...de('comida', [
    '¿Quién se come más wafles en un solo desayuno?',
    '¿Quién es más probable que pida un frappé aunque esté haciendo frío?',
    '¿Quién se roba las papitas del plato del otro?',
    '¿Quién es más probable que queme el arroz?',
    '¿Quién come más mecato a medianoche?',
    '¿Quién es más probable que se coma el postre antes del almuerzo?',
    '¿Quién es más cansón para escoger restaurante?',
    '¿Quién es más probable que pida lo mismo de siempre en el restaurante?',
    '¿Quién se antoja de lo que pidió el otro apenas llega el plato?',
    '¿Quién mete más cosas al carrito del súper que no estaban en la lista?',
    '¿Quién sería capaz de comerse unas hormigas culonas sin hacer caras?',
    '¿Quién le echa más ají a la empanada?',
    '¿Quién es más probable que se coma la fresa de encima del postre del otro?',
    '¿Quién hace mejor los huevos pericos?',
    '¿Quién es más probable que se acabe el queso de la nevera sin avisar?',
  ]),
  ...de('colombianas', [
    '¿Quién baila mejor salsa?',
    '¿Quién es más probable que se suba a bailar encima de una chiva rumbera?',
    '¿Quién dice más «¡ave María, pues!»?',
    '¿Quién habla más golpeado, estilo santandereano?',
    '¿Quién se sabe más vallenatos completos?',
    '¿Quién es más probable que llore cantando el himno en un partido de la Selección?',
    '¿Quién regatea mejor en la plaza de mercado?',
    '¿Quién es más probable que le diga «mijo» o «mija» a un desconocido?',
    '¿Quién reza la novena de aguinaldos con más juicio?',
    '¿Quién es más probable que se ponga el sombrero vueltiao en una fiesta?',
    '¿Quién aguanta más en una fiesta antes de pedir que se vayan?',
    '¿Quién es más tramposo en el parqués de diciembre?',
    '¿Quién se toma el tinto más cargado?',
    '¿Quién le tiene más miedo a la pólvora de diciembre?',
    '¿Quién es más probable que diga «¡qué pena con usted!» aunque no haya hecho nada?',
  ]),
  ...de('recuerdos', [
    '¿Quién se enamoró primero en la villa de Transformice?',
    '¿Quién tuvo la culpa de que no se agregaran de amigos esa primera noche?',
    '¿Quién se dormía primero en las videollamadas de 24 horas?',
    '¿Quién lloró más el día de la propuesta?',
    '¿Quién durmió mejor la noche del vuelo perdido a Cartagena?',
    '¿Quién estaba más nervioso la primera vez que se vieron?',
    '¿Quién hacía más tareas del otro en el colegio?',
    '¿Quién se quedó mirando más las estrellas en el planetario… y quién se quedó mirando al otro?',
  ]),
  ...de('picantes', [
    '¿Quién da los mejores besos?',
    '¿Quién es más celoso de los dos?',
    '¿Quién roba más la cobija en la noche?',
    '¿Quién empieza las guerras de cosquillas?',
    '¿Quién se pone más coqueto cuando quiere algo?',
    '¿Quién pide más besitos al día?',
    '¿Quién se pone más nervioso con una mirada del otro?',
    '¿Quién es más probable que le robe un beso al otro en plena fila del súper?',
  ]),
];
