// Ronda 4 · El termómetro: del 1 al 10. Uno dice la verdad sobre sí mismo y el otro adivina con el deslizador;
// entre más cerca, más puntos. `bajo` es lo que significa el 1 y `alto` el 10.
import { type Categoria, idDe, type PTermo, type Rol } from './tipos';

type Fila = [texto: string, bajo: string, alto: string, de?: Rol];
const de = (cat: Categoria, lista: Fila[]): PTermo[] =>
  lista.map(([t, bajo, alto, quien]) => ({ id: idDe('termo', t), tipo: 'termo', cat, t, bajo, alto, ...(quien ? { de: quien } : {}) }));

export const TERMO: PTermo[] = [
  ...de('divertidas', [
    ['¿Qué tanto odia {n} madrugar?', 'Le encanta', 'Lo odia con el alma'],
    ['¿Qué tan dormil{ón|ona} es {n}?', 'Se levanta con el sol', 'Hiberna como oso'],
    ['¿Qué tan desordenad{o|a} es {n}?', 'Todo en su sitio', 'Zona de desastre'],
    ['¿Qué tan dramátic{o|a} se pone {n} cuando se enferma?', 'Ni se queja', 'Escribe testamento'],
    ['¿Qué tan paciente es {n}?', 'Cero paciencia', 'Paciencia de santo'],
    ['¿Qué tan miedos{o|a} es {n} con las películas de terror?', 'Se ríe', 'No duerme en una semana'],
    ['¿Qué tan puntual es {n}?', 'Siempre tarde', 'Llega antes que nadie'],
    ['¿Qué tan competitiv{o|a} es {n} en los juegos de mesa?', 'Juega por jugar', 'Modo guerra'],
    ['¿Qué tan bien canta {n}?', 'Mejor que no cante', 'Para La Voz Kids… de grandes'],
    ['¿Qué tan gast{ón|ona} es {n}?', 'Ahorra todo', 'La tarjeta llora'],
    ['¿Qué tan friolent{o|a} es {n}?', 'Nunca tiene frío', 'Cobija a treinta grados'],
    ['¿Qué tan mimad{o|a} es {n}?', 'Independiente total', 'Bebé consentido'],
    ['¿Qué tan terc{o|a} es {n}?', 'Cede rapidito', 'Ni con grúa'],
    ['¿Qué tan cosquillos{o|a} es {n}?', 'Nada', 'Grita con solo mirarl{o|a}'],
    ['¿Qué tanto ronca {n}?', 'Silencio total', 'Moto sin silenciador'],
    ['¿Qué tan fiester{o|a} es {n}?', 'Casero total', 'Cierra la discoteca'],
    ['¿Qué tan rápido se enoja {n}?', 'Nunca se enoja', 'Fosforito'],
    ['¿Qué tan rápido se le pasa el enojo a {n}?', 'Días enteros', 'En segundos'],
    ['¿Qué tanto le gustan a {n} las sorpresas?', 'Las odia', 'Las ama'],
    ['¿Qué tan buen{o|a} es {n} guardando secretos?', 'Se le sale todo', 'Es una tumba'],
    ['¿Qué tan intens{o|a} es {n} por chat?', 'Mensajes cortitos', 'Cuarenta mensajes seguidos'],
    ['¿Qué tan cuidados{o|a} es {n} con sus cosas?', 'Todo se le pierde', 'Todo como nuevo'],
    ['¿Qué tan bien se le da a {n} armar muebles?', 'Le sobran tornillos', 'Profesional'],
    ['¿Qué tanto le gusta a {n} el chisme?', 'Nada', 'Le encanta el chisme'],
    ['¿Qué tanto se ríe {n} de sus propios chistes?', 'Serio total', 'Se ríe antes de terminarlos'],
    ['¿Qué tanto le gustan a {n} los planes improvisados?', 'Necesita agenda', '¡Vámonos ya!'],
    ['¿Qué tan perezos{o|a} es {n} los domingos?', 'Activo', 'No se mueve del sofá'],
    ['¿Qué tanto le gusta a {n} que le tomen fotos?', 'Las odia', 'Modelo profesional'],
    ['¿Qué tan nervios{o|a} se pone {n} hablando en público?', 'Tranquilísim{o|a}', 'Le tiembla hasta el alma'],
    ['¿Qué tanto le gusta a {n} hacer ejercicio?', 'Jamás', 'Todos los días'],
  ]),
  ...de('romanticas', [
    ['¿Qué tanto extraña {n} a {otro} cuando están lejos?', 'Poquito', 'Se muere de amor'],
    ['¿Qué tan cursi es {n}?', 'Cero cursi', 'Más que una telenovela'],
    ['¿Qué tan romántic{o|a} es {n}?', 'Témpano de hielo', 'Poeta'],
    ['¿Qué tan buen{o|a} es {n} dando abrazos?', 'Abrazo flojito', 'Abrazo que cura todo'],
    ['¿Qué tan buen{o|a} es {n} para subirle el ánimo a {otro}?', 'Lo intenta', 'Experto en sonrisas'],
    ['¿Qué tanto disfruta {n} los juegos de mesa con {otro}?', 'Poquito', 'Lo mejor de la semana'],
    ['¿Qué tan buen{o|a} es {n} dando consejos?', 'Mejor no', 'Psicólog{o|a} de profesión'],
  ]),
  ...de('comida', [
    ['¿Qué tanto le gusta el picante a {n}?', 'Nada', 'Se come el ají solo'],
    ['¿Qué tan buen{o|a} es {n} cocinando?', 'Quema el agua', 'Chef de restaurante'],
    ['¿Qué tanto le gustan los wafles a {n}?', 'Normal', 'Su razón de vivir'],
    ['¿Qué tanto ama {n} el frappé de café?', 'Le da igual', 'Más que a la vida'],
    ['¿Qué tanto le gusta a {n} ir al súper?', 'Lo odia', 'Su parque de diversiones'],
    ['¿Qué tanto le gusta a {n} la comida de mar?', 'Nada', 'Mariscos a diario'],
    ['¿Qué tanto le gustan a {n} las fresas con crema?', 'Normal', 'Gigantes, por favor'],
    ['¿Qué tan exigente es {n} con la comida?', 'Come de todo', 'Crítico de restaurante'],
    ['¿Qué tanto le gusta a {n} cocinar con {otro}?', 'Mejor que cocine el otro', 'Su plan favorito'],
  ]),
  ...de('colombianas', [
    ['¿Qué tan bien baila {n}?', 'Pies de plomo', '{Rey|Reina} de la pista'],
    ['¿Qué tanto le gusta el reguetón a {n}?', 'Nada', 'Perreo hasta el piso'],
    ['¿Qué tanto le gusta a {n} el calor de tierra caliente?', 'Lo sufre', 'Lo ama'],
    ['¿Qué tanto le gusta la Navidad a {n}?', 'Le da igual', 'Pone el árbol en octubre'],
    ['¿Qué tan buen{o|a} es {n} para el parqués?', 'Pierde siempre', 'Invict{o|a}'],
    ['¿Qué tan paisa (o santandereano) se pone {n} hablando cuando está bravo?', 'Ni se le nota', 'Acento al máximo'],
  ]),
  ...de('futuro', [
    ['¿Qué tan list{o|a} se siente {n} para cambiar pañales?', 'Sale corriendo', 'Expert{o|a}'],
    ['¿Qué tantas ganas tiene {n} de vivir con {otro} ya mismo?', 'Con calma', 'Ya tiene las maletas'],
    ['¿Qué tanto le gustaría a {n} viajar a Países Bajos, tierra de los liefje?', 'Nada', 'Ya tiene pasaporte'],
    ['¿Qué tanto le gustan a {n} los perritos?', 'Normal', 'Los adopta a todos'],
    ['¿Qué tan alcahuete va a ser {n} con la bebé?', 'Estrictísim{o|a}', 'Le da todo lo que pida'],
    ['¿Qué tan bien maneja {n} la plata?', 'Se le escapa', 'Banquer{o|a}'],
  ]),
  ...de('picantes', [
    ['¿Qué tan celos{o|a} es {n}?', 'Cero celos', 'Celos de telenovela'],
    ['¿Qué tan coquet{o|a} es {n}?', 'Nada', 'Demasiado'],
    ['¿Qué tanto le gustan a {n} los besos en público?', 'Cero', 'Ni le importa quién mire'],
    ['¿Qué tan buen{o|a} besando es {n}?', 'Necesita práctica', 'Nivel película'],
  ]),
  ...de('recuerdos', [
    ['¿Qué tanto le gusta a {n} maquillarse?', 'Lo justo', 'Es su terapia', 'ella'],
    ['¿Qué tan protagonista es la vida de {n} (le pasa de todo)?', 'Vida tranquila', 'Película de acción', 'ella'],
    ['¿Qué tan buena era {n} vendiendo cuando fue directora de Yanbal?', 'Le costaba', 'Vende hielo en el Polo Norte', 'ella'],
    ['¿Qué tanto disfruta {n} un mar con olas gigantes?', 'Solo la orilla', 'Se mete con olas de diez metros', 'ella'],
    ['¿Qué tanto se le antojan a {n} los wafles a medianoche?', 'Nunca', 'Todas las noches', 'ella'],
    ['¿Qué tanto le gustan las matemáticas a {n}?', 'Las odia', 'Las ama', 'el'],
    ['¿Qué tan bien explica {n}, estilo sesión de ICFES?', 'No se le entiende', 'Profesor estrella', 'el'],
    ['¿Qué tanto sufre {n} con el calor de Sopetrán?', 'Ni lo siente', 'Se derrite', 'el'],
    ['¿Qué tan insistente es {n} cuando quiere algo?', 'Se rinde rapidito', 'Persistente nivel experto', 'el'],
    ['¿Qué tan buen peluche para abrazar es {n}, el perro lanudo?', 'Flojito', 'Peluche certificado', 'el'],
  ]),
];
