// Ronda 6 · Final relámpago (el juego del zapato de las bodas): diez preguntas en treinta segundos.
// Cortitas, para leer de un vistazo: cada uno toca a Él o a Ella sin pensarlo mucho.
import { type Categoria, idDe, type PZapato } from './tipos';

const de = (cat: Categoria, lista: string[]): PZapato[] => lista.map((t) => ({ id: idDe('zapato', t), tipo: 'zapato', cat, t }));

export const ZAPATO: PZapato[] = [
  ...de('divertidas', [
    '¿Quién ronca más?',
    '¿Quién es más desordenado?',
    '¿Quién es más dormilón?',
    '¿Quién es más terco?',
    '¿Quién es más chistoso?',
    '¿Quién es más gastón?',
    '¿Quién canta peor?',
    '¿Quién es más puntual?',
    '¿Quién se ríe de sus propios chistes?',
    '¿Quién es más dramático?',
    '¿Quién tiene mejor memoria?',
    '¿Quién se enoja más fácil?',
    '¿Quién es más miedoso?',
    '¿Quién tiene la risa más contagiosa?',
    '¿Quién es más competitivo?',
    '¿Quién manda en la casa?',
    '¿Quién escoge la película?',
    '¿Quién se adueña del control remoto?',
    '¿Quién es más casero?',
    '¿Quién se levanta de mal genio?',
    '¿Quién es más cosquilloso?',
    '¿Quién se demora más en el baño?',
    '¿Quién usa más emojis?',
    '¿Quién manda más stickers?',
    '¿Quién es más intenso por chat?',
    '¿Quién es más aventurero?',
    '¿Quién es más protagonista?',
    '¿Quién es más perezoso los domingos?',
    '¿Quién se pierde más?',
    '¿Quién es más pegote?',
    '¿Quién trasnocha más?',
    '¿Quién tiene más ropa?',
    '¿Quién tiene más zapatos?',
    '¿Quién se toma más fotos?',
    '¿Quién se va a dormir primero?',
    '¿Quién gana las peleas de almohadas?',
    '¿Quién es más friolento?',
    '¿Quién explica mejor las cosas?',
    '¿Quién tiene la letra más bonita?',
    '¿Quién canta en el carro?',
  ]),
  ...de('romanticas', [
    '¿Quién es más romántico?',
    '¿Quién pide perdón primero?',
    '¿Quién es más detallista?',
    '¿Quién da mejores regalos?',
    '¿Quién dice «te amo» más veces al día?',
    '¿Quién es más consentido?',
    '¿Quién se ve más tierno dormido?',
    '¿Quién es más paciente con el otro?',
    '¿Quién da los mejores abrazos?',
    '¿Quién es más cursi?',
  ]),
  ...de('comida', [
    '¿Quién cocina mejor?',
    '¿Quién come más?',
    '¿Quién hace mejor los wafles?',
    '¿Quién hace mejor el frappé?',
    '¿Quién se come los dulces del otro?',
    '¿Quién gasta más en mecato?',
    '¿Quién es más loco por el súper?',
    '¿Quién come más rápido?',
  ]),
  ...de('futuro', [
    '¿Quién va a ser más alcahuete con la bebé?',
    '¿Quién quiere más al perrito?',
    '¿Quién va a madrugar con la bebé?',
    '¿Quién va a organizar la casa?',
    '¿Quién es más organizado con la plata?',
    '¿Quién va a llorar en la graduación de la niña?',
  ]),
  ...de('colombianas', [
    '¿Quién baila mejor?',
    '¿Quién es más fiestero?',
    '¿Quién es mejor en el parqués?',
    '¿Quién se emociona más en diciembre?',
    '¿Quién es más paisa de corazón?',
    '¿Quién es más berraco?',
  ]),
  ...de('picantes', [
    '¿Quién es más celoso?',
    '¿Quién es más coqueto?',
    '¿Quién da mejores besos?',
    '¿Quién se pone más nervioso con una mirada?',
    '¿Quién se maquilla mejor?',
    '¿Quién peina mejor?',
    '¿Quién hace mejor las uñas?',
    '¿Quién es más fotogénico?',
  ]),
  ...de('recuerdos', [
    '¿Quién habló primero en Transformice?',
    '¿Quién estaba más necesitado en la villa?',
    '¿Quién era el témpano de hielo?',
    '¿Quién era más juicioso en el colegio?',
  ]),
];
