import assert from 'node:assert/strict';import {transform} from 'esbuild';import {readFile} from 'node:fs/promises';
const modules=new Map();async function compile(url){if(modules.has(url.href))return modules.get(url.href);let {code}=await transform(await readFile(url,'utf8'),{loader:'ts',format:'esm',target:'es2022'});for(const m of [...code.matchAll(/from (["'])([^"']+)\1/g)]){const dep=m[2].startsWith('./')?await compile(new URL(m[2]+'.ts',url)):import.meta.resolve(m[2]);code=code.replace(m[0],'from '+JSON.stringify(dep));}const result='data:text/javascript;base64,'+Buffer.from(code).toString('base64');modules.set(url.href,result);return result;}
const load=f=>compile(new URL('../../src/granja-v3/'+f+'.ts',import.meta.url)).then(s=>import(s));

const {MotorGranja,validarEstado}=await load('motor'),C=await load('correo'),I=await load('inventario'),UI=await load('correo-ui');
let now=1800000000000,checks=0,failures=0;const game=()=>new MotorGranja({ahora:()=>now,azar:()=>.1});
const act=(m,a)=>{const r=m.actuar(a);assert.ok(r.ok,r.mensaje);return r;};
const action=(m,id,tipo)=>({tipo:'correo',accion:{id,tipo},xJugador:C.posicionBuzon(m.estado).x,zJugador:C.posicionBuzon(m.estado).z});
const record=(m,id)=>m.estado.correo.cartas.find(r=>r.id===id);
function fail(m,a){m.actualizar();const before=structuredClone(m.estado);assert.equal(m.actuar(a).ok,false);assert.deepEqual(m.estado,before);}
function test(n,f){try{f();checks++;console.log('OK '+n);}catch(e){failures++;console.error('FAIL '+n+': '+String(e.stack).replace(/data:text\/javascript;base64,[A-Za-z0-9+/=]+/g,'[modulo]'));}}
const sleep=m=>{m.estado.zona='granja';m.estado.servicio=null;m.estado.interior=null;const d=m.estado.jornada.diasCompletados;act(m,{tipo:'dormir',jornada:d,edificioId:'casa_inicial',xJugador:-5,zJugador:-.5});act(m,{tipo:'continuar_dia',jornada:d+1});};
test('Trece cartas con objetos existentes y bienvenida inicial',()=>{const m=game();assert.equal(C.CARTAS.length,13);assert.equal(new Set(C.CARTAS.map(c=>c.id)).size,13);for(const c of C.CARTAS)for(const p of c.objetos)assert.ok(I.articuloValido(p.articulo));assert.deepEqual(m.estado.correo,C.crearCorreo());assert.equal(validarEstado(m.estado),null);});
test('V5 migra sin correo y conserva inventario y jornada',()=>{const m=game(),s=structuredClone(m.estado);delete s.correo;assert.ok(m.cargarJSON(JSON.stringify(s)).ok);assert.deepEqual(m.estado.correo,C.crearCorreo());assert.deepEqual(m.estado.inventario,s.inventario);assert.deepEqual(m.estado.jornada,s.jornada);});
test('Tiempo real no entrega cartas ni avanza calendario',()=>{const m=game();now+=3*86400000;m.actualizar();assert.equal(m.estado.jornada.diasCompletados,0);assert.equal(m.estado.correo.cartas.length,1);});
test('Dormir entrega primera mañana una sola vez',()=>{const m=game();sleep(m);assert.equal(record(m,'primera_manana').recibidaDia,1);sleep(m);assert.equal(m.estado.correo.cartas.filter(c=>c.id==='primera_manana').length,1);assert.equal(validarEstado(m.estado),null);});
test('Leer cerca cuenta una vez y no produce recompensa',()=>{const m=game(),n=m.estado.monedas;act(m,action(m,'bienvenida','leer'));act(m,action(m,'bienvenida','leer'));assert.equal(m.estado.estadisticas.cartas_leidas,1);assert.equal(m.estado.monedas,n);fail(m,action(m,'bienvenida','reclamar'));});
test('Remoto, desconocido, interior y otra zona se rechazan',()=>{const m=game();fail(m,{...action(m,'bienvenida','leer'),xJugador:100});fail(m,action(m,'falsa','leer'));m.estado.zona='pueblo';fail(m,action(m,'bienvenida','leer'));m.estado.zona='granja';m.estado.interior='casa_inicial';fail(m,action(m,'bienvenida','leer'));});
test('Recompensa requiere leer y se conserva al recargar',()=>{const m=game();sleep(m);fail(m,action(m,'primera_manana','reclamar'));act(m,action(m,'primera_manana','leer'));const n=m.estado.inventario.heno??0;act(m,action(m,'primera_manana','reclamar'));assert.equal(m.estado.inventario.heno,n+3);assert.ok(m.cargarJSON(m.exportar()).ok);fail(m,action(m,'primera_manana','reclamar'));assert.equal(m.estado.estadisticas.adjuntos_correo,1);});
test('Mochila llena conserva adjunto hasta liberar casilla',()=>{const m=game();sleep(m);act(m,action(m,'primera_manana','leer'));m.estado.casillasInventario=m.estado.casillasInventario.map(()=>({articulo:'piedra',cantidad:999}));m.estado.inventario=I.resumirCasillas(m.estado.casillasInventario);fail(m,action(m,'primera_manana','reclamar'));assert.equal(record(m,'primera_manana').reclamadaDia,null);m.estado.casillasInventario[0]=null;m.estado.inventario=I.resumirCasillas(m.estado.casillasInventario);act(m,action(m,'primera_manana','reclamar'));assert.equal(m.estado.inventario.heno,3);});
test('Hitos llegan en próxima jornada, no antes',()=>{const m=game();for(const id of ['cosechar','pescar','consentir','escenas_sociales','obras_terminadas','ingresos_envio','limpiar'])m.estado.estadisticas[id]=1;m.actualizar();assert.equal(m.estado.correo.cartas.length,1);sleep(m);for(const id of ['primeras_semillas','primer_pez','corral_cuidado','un_recuerdo','primera_obra','envio_cobrado'])assert.ok(record(m,id));assert.equal(record(m,'herramientas'),undefined);sleep(m);assert.ok(record(m,'herramientas'));});
test('Dinero se cobra una vez y saldo lleno conserva carta',()=>{const m=game();m.estado.estadisticas.cosechar=1;sleep(m);act(m,action(m,'primeras_semillas','leer'));m.estado.monedas=1e9;fail(m,action(m,'primeras_semillas','reclamar'));m.estado.monedas=20;act(m,action(m,'primeras_semillas','reclamar'));assert.equal(m.estado.monedas,45);fail(m,action(m,'primeras_semillas','reclamar'));});
test('Estaciones entregan cartas al cierre exacto',()=>{const m=game();for(let i=0;i<84;i++)sleep(m);for(const [id,d] of [['verano',28],['otono',56],['invierno',84]])assert.equal(record(m,id).recibidaDia,d);assert.equal(validarEstado(m.estado),null);});
test('Buzón sigue posición y cuatro giros de cabaña',()=>{const m=game(),b=m.estado.edificios.find(b=>b.id==='casa_inicial'),p=C.posicionBuzon(m.estado);b.x+=10;b.z+=12;const q=C.posicionBuzon(m.estado);assert.ok(Math.abs(q.x-p.x-10)<1e-9);assert.ok(Math.abs(q.z-p.z-12)<1e-9);const positions=[];for(let giro=0;giro<4;giro++){b.giro=giro;const r=C.posicionBuzon(m.estado);assert.ok(Number.isFinite(r.x)&&Number.isFinite(r.z));assert.ok(C.cercaBuzon(m.estado,r.x,r.z));positions.push(JSON.stringify(r));}assert.equal(new Set(positions).size,4);});
test('Importaciones corruptas no reemplazan partida',()=>{const m=game();for(const mutate of [s=>s.correo=null,s=>s.correo.cartas.push({...s.correo.cartas[0]}),s=>s.correo.cartas[0].id='falsa',s=>s.correo.cartas[0].recibidaDia=1,s=>s.correo.cartas[0].leidaDia=2,s=>s.correo.cartas[0].reclamadaDia=0,s=>s.correo.cartas=[]]){const s=structuredClone(m.estado);mutate(s);const before=structuredClone(m.estado);assert.equal(m.cargarJSON(JSON.stringify(s)).ok,false);assert.deepEqual(m.estado,before);}});
test('Interfaz oculta carta nueva remota y permite consultar leídas',()=>{const m=game();assert.equal(UI.pendientesCorreo(m.estado),1);let html=UI.renderCorreo(m.estado,100,100);assert.ok(html.includes('disabled'));assert.ok(!html.includes(C.CARTAS[0].texto));act(m,action(m,'bienvenida','leer'));html=UI.renderCorreo(m.estado,100,100);assert.ok(html.includes(C.CARTAS[0].texto));assert.equal(UI.pendientesCorreo(m.estado),0);sleep(m);act(m,action(m,'primera_manana','leer'));assert.equal(UI.pendientesCorreo(m.estado),1);act(m,action(m,'primera_manana','reclamar'));assert.equal(UI.pendientesCorreo(m.estado),0);});
console.log(JSON.stringify({checks,failures}));if(failures)process.exitCode=1;
