import assert from 'node:assert/strict';
import {transform} from 'esbuild';
import {readFile} from 'node:fs/promises';
const modules=new Map();
async function compile(url){if(modules.has(url.href))return modules.get(url.href);let {code}=await transform(await readFile(url,'utf8'),{loader:'ts',format:'esm',target:'es2022'});for(const m of [...code.matchAll(/from (["'])([^"']+)\1/g)]){const dep=m[2].startsWith('./')?await compile(new URL(m[2]+'.ts',url)):import.meta.resolve(m[2]);code=code.replace(m[0],'from '+JSON.stringify(dep));}const result='data:text/javascript;base64,'+Buffer.from(code).toString('base64');modules.set(url.href,result);return result;}
const load=f=>compile(new URL('../../src/granja-v3/'+f+'.ts',import.meta.url)).then(s=>import(s));
const {MotorGranja,validarEstado}=await load('motor'),{SALIDAS,dentroDeZona,rutaCaminando,salidaCercana,esSenderoGranja}=await load('caminos-mundo');
const {crearPaisaje,aguaEn,huecoEn,paisajeValido}=await load('paisaje'),{tiempoCosecha}=await load('agricultura');
const {crearCultivo,reconciliarCultivo,avanzarCultivoDia}=await load('cuidados'),{paisajeGranja,señalesSalidas}=await load('paisaje-render');
let now=1_800_000_000_000,checks=0,failures=0;const game=()=>new MotorGranja({ahora:()=>now,azar:()=>.5});
function test(n,f){try{f();checks++;console.log('OK '+n);}catch(e){failures++;console.error('FAIL '+n+': '+e.stack);}}
function act(m,a){const r=m.actuar(a);assert.equal(r.ok,true,r.mensaje);return r;}
function fail(m,a){const before=structuredClone(m.estado),r=m.actuar(a);assert.equal(r.ok,false,r.mensaje);assert.deepEqual(m.estado,before);return r;}

test('Una sola parcela inicial; estanques, huecos y escombros del resto sin bloquear accesos',()=>{const m=game(),s=m.estado;assert.deepEqual(s.sectorIds,[0]);assert.equal(s.paisaje.estanques.length,3);assert.equal(s.paisaje.huecos.length,13);assert.ok(s.obstaculos.filter(o=>!o.zona&&o.sectorId!==0).length>650);assert.ok(s.obstaculos.some(o=>o.gigante));assert.equal(validarEstado(s),null);for(const o of s.obstaculos.filter(o=>!o.zona)){assert.equal(aguaEn(s.paisaje,o.x,o.z),false);assert.equal(huecoEn(s.paisaje,o.x,o.z),undefined);assert.equal(esSenderoGranja(o.x,o.z),false);}for(const r of SALIDAS.filter(s=>s.desde==='granja'))assert.equal(m.celdaLibre(r.x,r.z),false);});
test('El grafo une las seis zonas; llegadas seguras y regreso por el sendero opuesto',()=>{for(const r of SALIDAS){assert.ok(dentroDeZona(r.desde,r.x+.5,r.z+.5));assert.ok(dentroDeZona(r.hacia,r.llegada.x,r.llegada.z));assert.ok(SALIDAS.some(s=>s.desde===r.hacia&&s.hacia===r.desde));assert.equal(salidaCercana(r.desde,r.x+.5,r.z+.5).id,r.id);}const ruta=rutaCaminando('pueblo','bosque_ancestral');assert.deepEqual(ruta.map(r=>r.hacia),['granja','bosque','bosque_ancestral']);assert.deepEqual(rutaCaminando('granja','granja'),[]);assert.equal(dentroDeZona('bosque',0,0),false);});
test('Cruzar exige el sendero de la zona, proximidad, exterior y desbloqueo',()=>{const m=game();fail(m,{tipo:'viajar',zona:'pueblo',ruta:'granja_pueblo',xJugador:0,zJugador:0});fail(m,{tipo:'viajar',zona:'pueblo',ruta:'bosque_granja',xJugador:9.5,zJugador:4.5});fail(m,{tipo:'viajar',zona:'pueblo',ruta:'granja_pueblo',xJugador:NaN,zJugador:4.5});fail(m,{tipo:'viajar',zona:'mina',ruta:'granja_mina',xJugador:.5,zJugador:-6.5});const r=act(m,{tipo:'viajar',zona:'pueblo',ruta:'granja_pueblo',xJugador:9.5,zJugador:4.5});assert.deepEqual(r.posicionZona,{x:58.5,z:12.5});assert.deepEqual(m.estado.posicionExterior,{zona:'pueblo',x:58.5,z:12.5});m.estado.jornada.minutos=600;act(m,{tipo:'entrar_servicio',servicio:'semillas'});fail(m,{tipo:'viajar',zona:'granja',ruta:'pueblo_granja',xJugador:55.5,zJugador:12.5});act(m,{tipo:'salir_servicio'});act(m,{tipo:'viajar',zona:'granja',ruta:'pueblo_granja',xJugador:55.5,zJugador:12.5});assert.equal(m.estado.zona,'granja');});
test('Estanques y huecos no aceptan labrado, edificios ni máquinas antes de recuperar suelo',()=>{const m=game();for(const p of [{x:-5,z:5},{x:7,z:6}]){assert.equal(m.celdaLibre(p.x,p.z),false);fail(m,{tipo:'labrar',...p});fail(m,{tipo:'construir',articulo:'banco',...p});}assert.ok(aguaEn(m.estado.paisaje,-5,5));const s=structuredClone(m.estado);s.edificios.push({id:'banco_agua',articulo:'banco',x:-5,z:5,giro:0,clima:'templado',pasto:0,ultimoPastoAt:now});assert.match(validarEstado(s),/terreno disponible/);});
test('Rellenar exige propiedad, cercanía y cinco piedras; paga una vez y permite labrar y guardar',()=>{const m=game(),h=m.estado.paisaje.huecos[0],piedra=m.estado.inventario.piedra;fail(m,{tipo:'rellenar_hueco',id:h.id,xJugador:0,zJugador:0});fail(m,{tipo:'rellenar_hueco',id:'hueco_1',xJugador:-16.5,zJugador:5.5});act(m,{tipo:'rellenar_hueco',id:h.id,xJugador:h.x+.5,zJugador:h.z+1.5});assert.equal(m.estado.inventario.piedra,piedra-5);assert.equal(m.estado.paisaje.huecos.find(n=>n.id===h.id).relleno,true);assert.equal(m.celdaLibre(h.x,h.z),true);fail(m,{tipo:'rellenar_hueco',id:h.id,xJugador:h.x+.5,zJugador:h.z+1.5});act(m,{tipo:'labrar',x:h.x,z:h.z});const n=game();assert.equal(n.cargarJSON(m.exportar()).ok,true);assert.equal(n.estado.paisaje.huecos[0].relleno,true);assert.equal(n.estado.parcelas[0].x,h.x);});
test('Árbol grande requiere hierro, recibe varios golpes y suelta recursos finitos una vez',()=>{const m=game(),o=m.estado.obstaculos.find(o=>o.sectorId===0&&o.gigante);assert.ok(o);act(m,{tipo:'herramienta',herramienta:'hacha'});fail(m,{tipo:'golpear',obstaculoId:o.id,xJugador:o.x+1.5,zJugador:o.z+.5});m.estado.nivelesHerramienta.hacha=2;for(let i=0;i<8;i++){now+=1100;act(m,{tipo:'golpear',obstaculoId:o.id,xJugador:o.x+1.5,zJugador:o.z+.5});}assert.equal(m.estado.obstaculos.some(n=>n.id===o.id),false);assert.equal(m.estado.drops.filter(d=>d.articulo==='madera').reduce((a,d)=>a+d.cantidad,0),20);assert.equal(m.estado.drops.filter(d=>d.articulo==='madera_ancestral').reduce((a,d)=>a+d.cantidad,0),3);const drops=structuredClone(m.estado.drops);now+=1100;assert.equal(m.actuar({tipo:'golpear',obstaculoId:o.id,xJugador:o.x+1.5,zJugador:o.z+.5}).ok,false);assert.deepEqual(m.estado.drops,drops);});
test('Guardar restaura coordenadas exteriores; partidas anteriores conservan su terreno',()=>{const m=game();m.registrarPosicion(.5,3.5);m.registrarPosicion(Infinity,0);assert.deepEqual(m.estado.posicionExterior,{zona:'granja',x:.5,z:3.5});const n=game();assert.equal(n.cargarJSON(m.exportar()).ok,true);assert.deepEqual(n.estado.posicionExterior,m.estado.posicionExterior);const antiguo=structuredClone(m.estado);delete antiguo.paisaje;delete antiguo.posicionExterior;assert.equal(n.cargarJSON(JSON.stringify(antiguo)).ok,true);assert.equal(n.estado.paisaje,undefined);});
test('Importación rechaza radios falsos, huecos repetidos y coordenadas de otra zona',()=>{const m=game();for(const cambiar of [s=>s.paisaje.estanques[0].radioX='2',s=>s.paisaje.huecos[1].x=s.paisaje.huecos[0].x,s=>s.posicionExterior={zona:'pueblo',x:0,z:0}]){const s=structuredClone(m.estado);if(cambiar.toString().includes('huecos'))s.paisaje.huecos[1].z=s.paisaje.huecos[0].z;cambiar(s);assert.equal(m.cargarJSON(JSON.stringify(s)).ok,false);}assert.equal(paisajeValido(crearPaisaje()),true);});
test('Cultivos muestran días restantes; horas reales no cambian el progreso',()=>{
 const paso=1_800_000;let c=crearCultivo(4*paso,now,false);
 assert.match(tiempoCosecha(c),/4 días de crecimiento/);assert.match(tiempoCosecha(c),/Necesita agua/);
 c={...c,lastWateredAt:now};c=reconciliarCultivo(c,now+4*3_600_000);assert.match(tiempoCosecha(c),/4 días de crecimiento/);
 for(let dia=0;dia<4;dia++)c=avanzarCultivoDia(c,paso,now+4*3_600_000);
 assert.match(tiempoCosecha(c),/cosechar/);
 const seco=reconciliarCultivo(crearCultivo(4*paso,now,false),now+48*3_600_000);assert.match(tiempoCosecha(seco),/seco/);
});

test('Agua, agujeros y señales generan geometría válida y compactada',()=>{for(const g of [paisajeGranja(crearPaisaje()),señalesSalidas('granja')]){let vertices=0;g.traverse(o=>{if(o.geometry){o.geometry.computeBoundingBox();assert.ok(Number.isFinite(o.geometry.boundingBox.min.x));vertices+=o.geometry.attributes.position.count;o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose());}});assert.ok(vertices>100);assert.ok(g.children.length<20);}});
console.log(JSON.stringify({suite:'mundo-senderos-terreno',checks,failures}));if(failures)process.exitCode=1;
