import assert from 'node:assert/strict';import {transform} from 'esbuild';import {readFile} from 'node:fs/promises';
const modules=new Map();async function compile(url){if(modules.has(url.href))return modules.get(url.href);let {code}=await transform(await readFile(url,'utf8'),{loader:'ts',format:'esm',target:'es2022'});for(const m of [...code.matchAll(/from (["'])([^"']+)\1/g)]){const dep=m[2].startsWith('./')?await compile(new URL(m[2]+'.ts',url)):import.meta.resolve(m[2]);code=code.replace(m[0],'from '+JSON.stringify(dep));}const result='data:text/javascript;base64,'+Buffer.from(code).toString('base64');modules.set(url.href,result);return result;}
const load=f=>compile(new URL('../../src/granja-v3/'+f+'.ts',import.meta.url)).then(s=>import(s));
const {MotorGranja,validarEstado,migrarEstado}=await load('motor'),{crearJornada,fechaValle,INICIO_DIA,FIN_DIA,CRECIMIENTO_NOCHE_MS}=await load('jornada'),{crearCultivo}=await load('cuidados'),{crearCampo,duracionCampo}=await load('agricultura'),{CULTIVOS}=await load('catalogo'),{guardarPartida,CLAVE_PARTIDA,CLAVE_ULTIMA_NOCHE}=await load('guardado');
let now=1_800_000_000_000,checks=0,failures=0;const game=()=>new MotorGranja({ahora:()=>now});
function test(n,f){try{f();checks++;console.log('OK '+n);}catch(e){failures++;console.error('FAIL '+n+': '+e.stack);}}
function act(m,a){const r=m.actuar(a);assert.equal(r.ok,true,r.mensaje);return r;}
function fail(m,a){const before=structuredClone(m.estado),r=m.actuar(a);assert.equal(r.ok,false,r.mensaje);assert.deepEqual(m.estado,before);}
const sleep=m=>act(m,{tipo:'dormir',jornada:m.estado.jornada.diasCompletados,edificioId:'casa_inicial',xJugador:-5,zJugador:-.5});
const campoRegado=dia=>({...crearCampo(),riegoDia:dia});
const duracion=id=>duracionCampo(CULTIVOS.find(c=>c.id===id),crearCampo());
const morning=m=>act(m,{tipo:'continuar_dia',jornada:m.estado.jornada.diasCompletados});
test('La partida comienza a las 06:00 y el calendario solo recibe tiempo de juego explícito',()=>{const m=game();assert.deepEqual(m.calendario(),{dia:1,estacion:'primavera',ano:1,hora:6,minuto:0,finDelDia:false});now+=90*24*3_600_000;m.actualizar();assert.equal(m.calendario().dia,1);assert.equal(m.calendario().estacion,'primavera');assert.equal(m.calendario().hora,6);for(let i=0;i<30;i++)m.avanzarJornada(5);assert.equal(m.calendario().hora,7);assert.equal(m.calendario().minuto,40);});
test('Una jornada larga se detiene a las 02:00 sin gastar días ni estaciones',()=>{const m=game();for(let i=0;i<1000;i++)m.avanzarJornada(5);assert.equal(m.estado.jornada.minutos,FIN_DIA);assert.equal(m.calendario().dia,1);assert.equal(m.calendario().hora,2);m.avanzarJornada(NaN);m.avanzarJornada(-4);assert.equal(m.estado.jornada.minutos,FIN_DIA);});
test('Dormir recupera, cierra exactamente un día y conserva resumen y mañana durante recarga',()=>{const m=game();m.estado.vida=20;m.estado.energia=3;m.estado.estadisticas.plantar=4;m.estado.monedas-=20;const r=sleep(m);assert.equal(m.estado.vida,100);assert.equal(m.estado.energia,100);assert.equal(m.calendario().dia,2);assert.equal(m.estado.jornada.minutos,INICIO_DIA);assert.equal(r.resumenJornada.actividades.plantar,4);assert.equal(r.resumenJornada.monedasFin-r.resumenJornada.monedasInicio,-20);assert.equal(m.estado.jornada.resumenPendiente,true);m.avanzarJornada(5);assert.equal(m.estado.jornada.minutos,INICIO_DIA);const n=game();assert.equal(n.cargarJSON(m.exportar()).ok,true);assert.deepEqual(n.estado.jornada,m.estado.jornada);morning(n);n.avanzarJornada(5);assert.ok(n.estado.jornada.minutos>INICIO_DIA);});
test('Doble clic, token anterior y resumen pendiente no duplican día ni crecimiento',()=>{const m=game();sleep(m);fail(m,{tipo:'dormir',jornada:0,edificioId:'casa_inicial',xJugador:-5,zJugador:-.5});fail(m,{tipo:'reclamar',misionId:'hogar'});morning(m);fail(m,{tipo:'dormir',jornada:0,edificioId:'casa_inicial',xJugador:-5,zJugador:-.5});fail(m,{tipo:'continuar_dia',jornada:1});assert.equal(m.estado.jornada.diasCompletados,1);});
test('Dormir exige la cabaña y proximidad; el refugio, el pueblo y coordenadas falsas no sirven',()=>{const m=game();for(const a of [{edificioId:'corral_inicial',xJugador:-5,zJugador:-.5},{edificioId:'casa_inicial',xJugador:0,zJugador:0},{edificioId:'casa_inicial',xJugador:Infinity,zJugador:-.5}])fail(m,{tipo:'dormir',jornada:0,...a});act(m,{tipo:'viajar',zona:'pueblo'});fail(m,{tipo:'dormir',jornada:0,edificioId:'casa_inicial',xJugador:-5,zJugador:-.5});});
test('Temporadas y años cambian solo al cerrar los días 28 y 112',()=>{const m=game();m.estado.jornada=crearJornada(m.estado.monedas,{},27);sleep(m);assert.deepEqual(fechaValle(m.estado.jornada.diasCompletados),{dia:1,estacion:'verano',ano:1});morning(m);m.estado.jornada=crearJornada(m.estado.monedas,{},111);sleep(m);assert.deepEqual(fechaValle(m.estado.jornada.diasCompletados),{dia:1,estacion:'primavera',ano:2});});
test('La noche avanza cultivos hidratados, deja secos intactos y conserva maduros decorativos',()=>{const m=game();m.estado.parcelas=[{x:0,z:3,cultivo:'fresa',campo:campoRegado(m.estado.jornada.diasCompletados),cuidado:crearCultivo(duracion('fresa'),now,true)},{x:0,z:4,cultivo:'fresa',campo:crearCampo(),cuidado:crearCultivo(duracion('fresa'),now,false)},{x:0,z:5,cultivo:'fresa',campo:crearCampo(),cuidado:{...crearCultivo(duracion('fresa'),now,true),status:'maduro',grownMs:duracion('fresa'),maturedAt:now}}];const wateredAt=m.estado.parcelas[0].cuidado.lastWateredAt;const r=sleep(m);assert.equal(r.resumenJornada.cultivosAvanzados,1);assert.equal(m.estado.parcelas[0].cuidado.grownMs,CRECIMIENTO_NOCHE_MS);assert.equal(m.estado.parcelas[0].cuidado.lastWateredAt,wateredAt);assert.equal(m.estado.parcelas[1].cuidado.grownMs,0);assert.equal(m.estado.parcelas[2].cuidado.status,'maduro');assert.equal(validarEstado(m.estado),null);});
test('Madurar durante la noche usa la fecha real sin fabricar horas de riego o cuidado',()=>{const m=game();const c=crearCultivo(duracion('zanahoria'),now,true);c.grownMs=c.growthMs-60_000;m.estado.parcelas.push({x:0,z:3,cultivo:'zanahoria',campo:campoRegado(m.estado.jornada.diasCompletados),cuidado:c});const antes=structuredClone(m.estado.animales);sleep(m);assert.equal(m.estado.parcelas[0].cuidado.status,'maduro');assert.equal(m.estado.parcelas[0].cuidado.maturedAt,now);for(let i=0;i<antes.length;i++){const {rutina,...animal}=m.estado.animales[i];assert.deepEqual(animal,{...antes[i],edadDias:antes[i].edadDias+1});assert.equal(rutina.lugar,'refugio');}assert.equal(m.estado.ultimoTiempo,now);assert.equal(validarEstado(m.estado),null);});
test('Muchas noches no suplantan 48 horas reales de deterioro o contratos',()=>{const m=game();m.estado.jornada=crearJornada(m.estado.monedas,{},84);m.estado.parcelas=[{x:0,z:3,cultivo:'fresa',campo:crearCampo(),cuidado:crearCultivo(duracion('fresa'),now,false)}];for(let i=0;i<30;i++){sleep(m);morning(m);}assert.equal(m.estado.parcelas[0].cuidado.status,'creciendo');assert.ok(m.estado.parcelas[0].cuidado.grownMs<=2*CRECIMIENTO_NOCHE_MS);now+=48*3_600_000;m.actualizar();assert.equal(m.estado.parcelas[0].cuidado.status,'arruinado');assert.equal(m.estado.jornada.diasCompletados,114);});
test('El resumen de la siguiente noche incluye solo sus actividades sin repetir recompensas',()=>{const m=game();m.estado.estadisticas.cosechar=3;sleep(m);morning(m);m.estado.estadisticas.cosechar=4;sleep(m);assert.equal(m.estado.jornada.ultimaNoche.actividades.cosechar,1);assert.equal(m.estado.jornada.ultimaNoche.id,2);assert.equal(m.estado.monedas,420);});
test('Migración conserva estación del último guardado sin incluir la ausencia posterior',()=>{const m=game(),s=structuredClone(m.estado);delete s.jornada;s.inicioTiempo=now-35*1_800_000-900_000;const v=migrarEstado(s);assert.equal(v.jornada.diasCompletados,35);assert.equal(v.jornada.minutos,960);now+=60*24*3_600_000;const n=game();assert.equal(n.cargarJSON(JSON.stringify(s)).ok,true);assert.deepEqual(fechaValle(n.estado.jornada.diasCompletados),{dia:8,estacion:'verano',ano:1});});
test('Importación rechaza fechas nocturnas incoherentes, relojes falsos y contadores inválidos',()=>{const m=game();sleep(m);for(const edit of [s=>s.jornada.minutos=Infinity,s=>s.jornada.diasCompletados=-1,s=>s.jornada.ultimaNoche.id=9,s=>s.jornada.ultimaNoche.fechaSiguiente.dia=8,s=>s.jornada.ultimaNoche.guardadoAt=now+1,s=>s.jornada.contadoresInicio.plantar=-1]){const s=structuredClone(m.estado);edit(s);assert.equal(m.cargarJSON(JSON.stringify(s)).ok,false);}assert.equal(validarEstado(m.estado),null);});
test('Horas jugando y 47 horas desconectado no dan progreso; el riego del día solo vale una noche',()=>{
 const m=game(),p={x:0,z:3,cultivo:'zanahoria',campo:campoRegado(0),cuidado:crearCultivo(duracion('zanahoria'),now,true)};m.estado.parcelas.push(p);
 for(let i=0;i<500;i++)m.avanzarJornada(5);assert.equal(p.cuidado.grownMs,0);
 now+=47*3_600_000;m.actualizar();assert.equal(p.cuidado.grownMs,0);assert.equal(p.cuidado.status,'creciendo');assert.equal(m.calendario().dia,1);
 sleep(m);assert.equal(p.cuidado.grownMs,CRECIMIENTO_NOCHE_MS);morning(m);sleep(m);assert.equal(p.cuidado.grownMs,CRECIMIENTO_NOCHE_MS);morning(m);
 act(m,{tipo:'herramienta',herramienta:'regadera'});act(m,{tipo:'regar',x:p.x,z:p.z});sleep(m);assert.equal(p.cuidado.grownMs,2*CRECIMIENTO_NOCHE_MS);
});
test('Aspersores riegan cada noche sin exigir que pasen horas reales; no crecen fuera del juego',()=>{
 const m=game(),p={x:0,z:3,cultivo:'fresa',campo:crearCampo(),cuidado:crearCultivo(duracion('fresa'),now,false)};m.estado.parcelas.push(p);
 m.estado.produccion.estructuras.push({id:'aspersor_dia',articulo:'aspersor_cobre',zona:'granja',x:1,z:3});
 for(let i=0;i<8;i++){sleep(m);assert.equal(p.cuidado.grownMs,(i+1)*CRECIMIENTO_NOCHE_MS);morning(m);}
 assert.equal(p.cuidado.status,'maduro');assert.equal(m.estado.ultimoTiempo,now);assert.equal(validarEstado(m.estado),null);
});
test('Crías conservan edad y tamaño tras ausencias largas, maduran solo al dormir y no mueren',()=>{
 const m=game(),a=m.estado.animales[0];a.edadDias=0;a.nacimiento=now;
 now+=30*24*3_600_000;m.actualizar();assert.equal(a.edadDias,0);assert.equal(m.resumenAnimal(a).adulto,false);assert.equal(a.productos,0);
 assert.equal(m.estado.animales.length,2);assert.equal(m.resumenAnimal(a).enfermo,true);
 sleep(m);assert.equal(a.edadDias,1);assert.equal(m.resumenAnimal(a).adulto,true);assert.equal(m.resumenAnimal(a).enfermo,true);
});
test('Migración convierte progreso una sola vez y conserva madurez, abono y edad del último guardado',()=>{
 const m=game(),s=structuredClone(m.estado);s.jornada.version=1;
 for(const a of s.animales)delete a.edadDias;
 s.parcelas=[{x:0,z:3,cultivo:'fresa',campo:{fertilizante:2,cosechas:0,ciclo:'inicial',semilla:83},cuidado:{...crearCultivo(10*3_600_000,now,true),grownMs:5*3_600_000}}];
 const v=migrarEstado(s);assert.equal(v.jornada.version,2);assert.equal(v.parcelas[0].cuidado.grownMs,duracion('fresa')/2);assert.equal(v.parcelas[0].campo.riegoDia,0);assert.equal(v.animales[0].edadDias,2);
 assert.equal(validarEstado(v),null);assert.deepEqual(migrarEstado(v),v);
 now+=24*3_600_000;const n=game();assert.equal(n.cargarJSON(JSON.stringify(s)).ok,true);assert.equal(n.estado.animales[0].edadDias,2);assert.equal(n.estado.parcelas[0].cuidado.grownMs,duracion('fresa')/2);
 const maduro=structuredClone(s);maduro.parcelas[0].cuidado={...maduro.parcelas[0].cuidado,status:'maduro',grownMs:10*3_600_000,maturedAt:s.ultimoTiempo};assert.equal(validarEstado(migrarEstado(maduro)),null);
 const malo=structuredClone(s);malo.parcelas[0].cuidado.grownMs=11*3_600_000;assert.notEqual(validarEstado(migrarEstado(malo)),null);
});
test('Importación no permite edad negativa ni riego de una jornada futura',()=>{
 const m=game();m.estado.parcelas=[{x:0,z:3,cultivo:'fresa',campo:crearCampo(),cuidado:crearCultivo(duracion('fresa'),now,false)}];
 for(const editar of [s=>s.animales[0].edadDias=-1,s=>s.parcelas[0].campo.riegoDia=9]){const s=structuredClone(m.estado);editar(s);assert.equal(m.cargarJSON(JSON.stringify(s)).ok,false);}
});
test('Copia nocturna preserva el guardado y revierte la escritura si falta espacio',()=>{const datos=new Map([[CLAVE_PARTIDA,'ayer'],[CLAVE_ULTIMA_NOCHE,'copia-ayer']]);let falla=true;const storage={getItem:k=>datos.get(k)??null,removeItem:k=>datos.delete(k),setItem:(k,v)=>{if(falla&&k===CLAVE_ULTIMA_NOCHE)throw Error('QuotaExceeded');datos.set(k,v);}};assert.throws(()=>guardarPartida(storage,'hoy',true));assert.equal(datos.get(CLAVE_PARTIDA),'ayer');assert.equal(datos.get(CLAVE_ULTIMA_NOCHE),'copia-ayer');falla=false;guardarPartida(storage,'hoy',true);assert.equal(datos.get(CLAVE_PARTIDA),'hoy');assert.equal(datos.get(CLAVE_ULTIMA_NOCHE),'hoy');guardarPartida(storage,'durante-el-dia');assert.equal(datos.get(CLAVE_ULTIMA_NOCHE),'hoy');});
console.log(JSON.stringify({suite:'jornada-sueno-guardado',checks,failures}));if(failures)process.exitCode=1;
