import assert from 'node:assert/strict';import {transform} from 'esbuild';import {readFile} from 'node:fs/promises';
const modules=new Map();async function compile(url){if(modules.has(url.href))return modules.get(url.href);let {code}=await transform(await readFile(url,'utf8'),{loader:'ts',format:'esm',target:'es2022'});for(const m of [...code.matchAll(/from (["'])([^"']+)\1/g)]){const dep=m[2].startsWith('./')?await compile(new URL(m[2]+'.ts',url)):import.meta.resolve(m[2]);code=code.replace(m[0],'from '+JSON.stringify(dep));}const result='data:text/javascript;base64,'+Buffer.from(code).toString('base64');modules.set(url.href,result);return result;}
const load=f=>compile(new URL('../../src/granja-v3/'+f+'.ts',import.meta.url)).then(s=>import(s));
const {MotorGranja,validarEstado}=await load('motor'),{FRUTALES}=await load('frutales-datos'),{crearFrutal}=await load('frutales'),{cambiarCantidad,resumirCasillas}=await load('inventario'),{crearJornada,CRECIMIENTO_NOCHE_MS}=await load('jornada'),{OBJETOS,RECETAS}=await load('objetos');
let now=1_800_000_000_000,checks=0,failures=0;const game=()=>new MotorGranja({ahora:()=>now});
function test(n,f){try{f();checks++;console.log('OK '+n);}catch(e){failures++;console.error('FAIL '+n+': '+String(e.stack).replace(/data:text\/javascript;base64,[A-Za-z0-9+/=]+/g,'[módulo]'));}}
const act=(m,a)=>{const r=m.actuar(a);assert.equal(r.ok,true,r.mensaje);return r;};
const fail=(m,a)=>{const s=structuredClone(m.estado),r=m.actuar(a);assert.equal(r.ok,false,r.mensaje);assert.deepEqual(m.estado,s);};
const give=(m,id,n)=>{const s=cambiarCantidad(m.estado.casillasInventario,id,n);assert.ok(s);m.estado.casillasInventario=s;m.estado.inventario=resumirCasillas(s);};
const sleep=m=>act(m,{tipo:'dormir',jornada:m.estado.jornada.diasCompletados,edificioId:'casa_inicial',xJugador:-5,zJugador:-.5});
const morning=m=>act(m,{tipo:'continuar_dia',jornada:m.estado.jornada.diasCompletados});
const plant=(m,tipo='naranjo',x=0,z=3)=>{give(m,'planton_'+tipo,1);act(m,{tipo:'plantar_frutal',frutal:tipo,x,z,xJugador:x+.5,zJugador:z+1.5});return m.estado.frutales.at(-1);};
const water=(m,x=0,z=3)=>{act(m,{tipo:'herramienta',herramienta:'regadera'});act(m,{tipo:'regar',x,z});};
const greenhouse=m=>{give(m,'creacion_invernadero',1);m.estado.obstaculos=m.estado.obstaculos.filter(o=>!(o.x>=-3&&o.x<2&&o.z>=0&&o.z<4));act(m,{tipo:'construir',articulo:'invernadero',x:-3,z:0});return m.estado.invernaderos[0].edificioId;};
const enter=(m,id)=>act(m,{tipo:'entrar',edificioId:id,xJugador:-.5,zJugador:4.5});
const seed=(m,id='tomate',x=-3,z=-2)=>{act(m,{tipo:'herramienta',herramienta:'azada'});act(m,{tipo:'labrar',x,z});give(m,'semilla_'+id,1);act(m,{tipo:'plantar',cultivo:id,x,z});return m.parcelasActuales().at(-1);};
const mature=f=>{f.cuidado.status='maduro';f.cuidado.grownMs=f.cuidado.growthMs;f.cuidado.maturedAt=now;};
test('Ocho frutales tienen plantón obtenible, fruto y receta sin duplicar IDs',()=>{assert.equal(FRUTALES.length,8);for(const f of FRUTALES){assert.ok(OBJETOS[f.planton]);assert.ok(OBJETOS[f.producto]);assert.ok(RECETAS.find(r=>r.id==='mermelada_'+f.producto));}assert.equal(new Set(RECETAS.map(r=>r.id)).size,RECETAS.length);assert.equal(validarEstado(game().estado),null);});
test('Plantones solo se compran en la tienda; compra llena o remota es atómica',()=>{const m=game();fail(m,{tipo:'comprar_objeto',articulo:'planton_manzano'});act(m,{tipo:'viajar',zona:'pueblo'});m.estado.jornada.minutos=600;act(m,{tipo:'entrar_servicio',servicio:'semillas'});act(m,{tipo:'comprar_objeto',articulo:'planton_manzano'});assert.equal(m.estado.monedas,320);assert.equal(m.estado.inventario.planton_manzano,1);});
test('Plantar consume un plantón, reserva el tronco y requiere espacio y proximidad',()=>{const m=game();plant(m);assert.equal(m.estado.inventario.planton_naranjo??0,0);assert.equal(m.celdaLibre(0,3),false);give(m,'planton_manzano',1);for(const a of [{x:0,z:3},{x:2,z:3},{x:0,z:30},{x:NaN,z:3}])fail(m,{tipo:'plantar_frutal',frutal:'manzano',xJugador:.5,zJugador:4.5,...a});assert.equal(validarEstado(m.estado),null);});
test('Horas reales y reloj activo no hacen crecer árboles ni producen fruta',()=>{const m=game();plant(m);water(m);for(let i=0;i<100;i++)m.avanzarJornada(5);now+=24*3600000;m.actualizar();assert.equal(m.estado.frutales[0].cuidado.grownMs,0);assert.equal(m.estado.frutales[0].frutos,0);assert.equal(m.estado.jornada.diasCompletados,0);});
test('Frutales crecen una noche regada, se detienen sin agua o con espacio ocupado',()=>{const m=game();plant(m);water(m);sleep(m);morning(m);assert.equal(m.estado.frutales[0].cuidado.grownMs,CRECIMIENTO_NOCHE_MS);sleep(m);morning(m);assert.equal(m.estado.frutales[0].cuidado.grownMs,CRECIMIENTO_NOCHE_MS);m.estado.jornada=crearJornada(m.estado.monedas,{},84);act(m,{tipo:'herramienta',herramienta:'azada'});act(m,{tipo:'labrar',x:1,z:3});water(m);sleep(m);morning(m);assert.equal(m.estado.frutales[0].cuidado.grownMs,CRECIMIENTO_NOCHE_MS);});
test('Madurez en 28 noches regadas; fruta posterior limitada a tres y fuera de temporada se conserva',()=>{const m=game();plant(m);for(let i=0;i<28;i++){water(m);sleep(m);morning(m);}assert.equal(m.estado.frutales[0].cuidado.status,'maduro');assert.equal(m.estado.frutales[0].frutos,0);for(let i=0;i<6;i++){sleep(m);morning(m);}assert.equal(m.estado.frutales[0].frutos,3);m.estado.jornada=crearJornada(m.estado.monedas,{},56);sleep(m);morning(m);assert.equal(m.estado.frutales[0].frutos,3);now+=120*24*3600000;m.actualizar();assert.equal(m.estado.frutales[0].cuidado.status,'maduro');assert.equal(m.estado.frutales[0].frutos,3);assert.equal(validarEstado(m.estado),null);});
test('Sequía de 48 h arruina plantones, la lluvia no los revive y no adelanta madurez',()=>{const m=game();plant(m);now+=48*3600000;m.actualizar();assert.equal(m.estado.frutales[0].cuidado.status,'arruinado');m.estado.jornada=crearJornada(m.estado.monedas,{},2);m.avanzarJornada(1);assert.equal(m.estado.frutales[0].cuidado.status,'arruinado');assert.equal(m.estado.frutales[0].cuidado.grownMs,0);});
test('Fruta se recoge por proximidad una sola vez y puede enviarse; mochila llena conserva árbol',()=>{const m=game(),f=plant(m);mature(f);f.frutos=3;f.fructificaciones=3;const slots=structuredClone(m.estado.casillasInventario);m.estado.casillasInventario=Array.from({length:24},()=>({articulo:'piedra',cantidad:999}));m.estado.inventario=resumirCasillas(m.estado.casillasInventario);fail(m,{tipo:'recoger_frutal',id:f.id,xJugador:.5,zJugador:4.5});m.estado.casillasInventario=slots;m.estado.inventario=resumirCasillas(slots);fail(m,{tipo:'recoger_frutal',id:f.id,xJugador:80,zJugador:80});act(m,{tipo:'recoger_frutal',id:f.id,xJugador:.5,zJugador:4.5});assert.equal(m.estado.inventario.naranja,3);fail(m,{tipo:'recoger_frutal',id:f.id,xJugador:.5,zJugador:4.5});const i=m.estado.casillasInventario.findIndex(p=>p?.articulo==='naranja');act(m,{tipo:'envio',edificioId:'envio_inicial',sentido:'depositar',casilla:i,cantidad:3,xJugador:-7.5,zJugador:1.5});assert.equal(sleep(m).resumenJornada.envios.total,90);});
test('Tala por golpes conserva daño, genera madera y deja libre la celda',()=>{const m=game();plant(m);act(m,{tipo:'herramienta',herramienta:'hacha'});for(let i=0;i<4;i++){now+=500;act(m,{tipo:'golpear_frutal',id:m.estado.frutales[0].id,xJugador:.5,zJugador:4.5});}assert.equal(m.estado.frutales.length,0);assert.ok(m.estado.drops.some(d=>d.articulo==='madera'&&d.cantidad===2));assert.equal(m.celdaLibre(0,3),true);});
test('Invernadero construible crea recinto propio; entrar exige puerta y permite azada en bancales',()=>{const m=game(),id=greenhouse(m);fail(m,{tipo:'entrar',edificioId:id});fail(m,{tipo:'entrar',edificioId:id,xJugador:80,zJugador:80});enter(m,id);const p=seed(m);assert.equal(m.estado.parcelas.length,0);assert.equal(m.estado.invernaderos[0].parcelas.length,1);assert.equal(p.cultivo,'tomate');fail(m,{tipo:'labrar',x:0,z:0});assert.equal(validarEstado(m.estado),null);});
test('Interior permite fuera de temporada; estar cerca en exterior ya no anula estaciones',()=>{const m=game(),id=greenhouse(m);m.estado.jornada=crearJornada(m.estado.monedas,{},84);act(m,{tipo:'herramienta',herramienta:'azada'});act(m,{tipo:'labrar',x:0,z:5});give(m,'semilla_tomate',2);fail(m,{tipo:'plantar',cultivo:'tomate',x:0,z:5});enter(m,id);seed(m);act(m,{tipo:'herramienta',herramienta:'azada'});act(m,{tipo:'labrar',x:-3,z:-1});give(m,'semilla_tomate_fuego',1);fail(m,{tipo:'plantar',cultivo:'tomate_fuego',x:-3,z:-1});});
test('Riego, abono, rebrote y crecimiento nocturno funcionan dentro sin tocar exterior',()=>{const m=game(),id=greenhouse(m);enter(m,id);const p=seed(m);give(m,'fertilizante',1);act(m,{tipo:'fertilizar',x:-3,z:-2,articulo:'fertilizante'});assert.equal(p.campo.fertilizante,1);water(m,-3,-2);act(m,{tipo:'salir'});sleep(m);morning(m);assert.equal(m.estado.invernaderos[0].parcelas[0].cuidado.grownMs,CRECIMIENTO_NOCHE_MS);enter(m,id);assert.equal(m.parcelasActuales()[0].campo.riegoDia,0);for(let i=0;i<10&&m.parcelasActuales()[0].cuidado.status!=='maduro';i++){water(m,-3,-2);act(m,{tipo:'salir'});sleep(m);morning(m);enter(m,id);}assert.equal(m.parcelasActuales()[0].cuidado.status,'maduro');act(m,{tipo:'herramienta',herramienta:'mano'});act(m,{tipo:'cosechar',x:-3,z:-2});assert.equal(m.parcelasActuales()[0].campo.ciclo,'rebrote');assert.equal(m.parcelasActuales()[0].campo.fertilizante,1);assert.equal(m.parcelasActuales()[0].cuidado.grownMs,0);assert.equal(validarEstado(m.estado),null);});
test('Lluvia no atraviesa techo; riego instalado cuesta una vez y no da crecimiento ausente',()=>{const m=game(),id=greenhouse(m);m.estado.jornada=crearJornada(m.estado.monedas,{},2);enter(m,id);seed(m);m.avanzarJornada(1);assert.equal(m.parcelasActuales()[0].campo.riegoDia,null);give(m,'lingote_hierro',3);give(m,'vidrio',6);act(m,{tipo:'instalar_riego_invernadero',edificioId:id});assert.equal(m.estado.monedas,120);fail(m,{tipo:'instalar_riego_invernadero',edificioId:id});now+=12*3600000;m.actualizar();assert.equal(m.parcelasActuales()[0].cuidado.grownMs,0);assert.equal(m.parcelasActuales()[0].campo.riegoDia,2);act(m,{tipo:'salir'});sleep(m);assert.equal(m.estado.invernaderos[0].parcelas[0].cuidado.grownMs,CRECIMIENTO_NOCHE_MS);});
test('Frutales dentro producen en invierno y parcelas/árboles se conservan al trasladar edificio',()=>{const m=game(),id=greenhouse(m);m.estado.jornada=crearJornada(m.estado.monedas,{},84);enter(m,id);const f=plant(m,'cerezo',-6,-4);mature(f);seed(m);act(m,{tipo:'salir'});sleep(m);morning(m);assert.equal(m.estado.frutales[0].frutos,1);const antes=structuredClone(m.estado.invernaderos[0]);fail(m,{tipo:'retirar_edificio',edificioId:id});m.estado.obstaculos=m.estado.obstaculos.filter(o=>!(o.x>=2&&o.x<7&&o.z>=3&&o.z<7));act(m,{tipo:'mover',edificioId:id,x:2,z:3});assert.deepEqual(m.estado.invernaderos[0],antes);assert.equal(m.estado.frutales[0].edificioId,id);assert.equal(validarEstado(m.estado),null);});
test('Recarga y migración mantienen cultivos interiores; ornamentos no se convierten en productivos',()=>{const m=game(),id=greenhouse(m);enter(m,id);seed(m);const old=m.exportar(),n=game();assert.equal(n.cargarJSON(old).ok,true);assert.equal(n.estado.interior,id);assert.deepEqual(n.estado.invernaderos,m.estado.invernaderos);const s=structuredClone(m.estado);delete s.frutales;delete s.invernaderos;s.interior=null;const c=game();assert.equal(c.cargarJSON(JSON.stringify(s)).ok,true);assert.equal(c.estado.invernaderos.length,1);assert.equal(c.estado.frutales.length,0);assert.ok(c.estado.invernaderos[0].parcelas.length===0);});
test('Importación inválida rechaza recintos huérfanos, plantas fuera de bancal y frutas falsas',()=>{const m=game(),id=greenhouse(m);enter(m,id);plant(m,'cerezo',-6,-4);seed(m);for(const mutate of [s=>s.invernaderos[0].edificioId='falso',s=>s.invernaderos[0].riegoAutomatico='si',s=>s.invernaderos[0].parcelas[0].x=0,s=>s.frutales[0].frutos=4,s=>s.frutales[0].edificioId='falso',s=>s.frutales[0].cuidado.growthMs=10,s=>s.frutales.push(structuredClone(s.frutales[0]))]){const s=structuredClone(m.estado);mutate(s);assert.equal(m.cargarJSON(JSON.stringify(s)).ok,false);}});

test('Riego permanente conserva plantas después de 80 días ausentes sin crecer ni avanzar estaciones',()=>{const m=game(),id=greenhouse(m);enter(m,id);seed(m);plant(m,'cerezo',-6,-4);give(m,'lingote_hierro',3);give(m,'vidrio',6);act(m,{tipo:'instalar_riego_invernadero',edificioId:id});const dia=m.estado.jornada.diasCompletados;now+=80*24*3600000;m.actualizar();for(const c of [m.parcelasActuales()[0].cuidado,m.frutalesActuales()[0].cuidado]){assert.equal(c.status,'creciendo');assert.equal(c.grownMs,0);}assert.equal(m.estado.jornada.diasCompletados,dia);assert.equal(validarEstado(m.estado),null);});
test('Aspersor exterior cuida frutales jóvenes durante ausencia sin adelantar su crecimiento',()=>{const m=game();plant(m);give(m,'aspersor_cobre',1);act(m,{tipo:'produccion',accion:{tipo:'colocar_estructura',articulo:'aspersor_cobre',zona:'granja',x:1,z:3},xJugador:1.5,zJugador:4.5});now+=80*24*3600000;m.actualizar();assert.equal(m.estado.frutales[0].cuidado.status,'creciendo');assert.equal(m.estado.frutales[0].cuidado.grownMs,0);assert.equal(validarEstado(m.estado),null);});
test('Restaurar una ruina exige materiales y espacio; un rechazo conserva ruina y mochila',()=>{const m=game();m.estado.obstaculos=m.estado.obstaculos.filter(o=>!(o.x>=-3&&o.x<2&&o.z>=0&&o.z<4));m.estado.obstaculos.push({id:'ruina_prueba',tipo:'ruina',x:-3,z:0,sectorId:0,hp:1,hpMax:1,regeneraEn:null});const a={tipo:'restaurar_invernadero',obstaculoId:'ruina_prueba',xJugador:-2.5,zJugador:.5};fail(m,a);give(m,'madera',30);give(m,'cristal',15);give(m,'hierro',5);act(m,a);assert.equal(m.estado.obstaculos.some(o=>o.id==='ruina_prueba'),false);assert.equal(m.estado.invernaderos.length,1);assert.equal(validarEstado(m.estado),null);});
test('Talar frutal interior con mochila llena no pierde madera, fruta ni progreso del último golpe',()=>{const m=game(),id=greenhouse(m);enter(m,id);const f=plant(m,'cerezo',-6,-4);mature(f);f.frutos=2;f.fructificaciones=2;act(m,{tipo:'herramienta',herramienta:'hacha'});for(let i=0;i<11;i++){now+=500;act(m,{tipo:'golpear_frutal',id:f.id,xJugador:-5.5,zJugador:-2.5});}m.estado.casillasInventario=Array.from({length:24},()=>({articulo:'piedra',cantidad:999}));m.estado.inventario=resumirCasillas(m.estado.casillasInventario);now+=500;m.actualizar();fail(m,{tipo:'golpear_frutal',id:f.id,xJugador:-5.5,zJugador:-2.5});assert.equal(m.estado.frutales[0].golpes,11);assert.equal(m.estado.frutales[0].frutos,2);});


test('Fruta recogida alimenta una conserva: reserva exacta, recarga y salida sin duplicar',()=>{const m=game(),f=plant(m);mature(f);f.frutos=3;f.fructificaciones=3;act(m,{tipo:'recoger_frutal',id:f.id,xJugador:.5,zJugador:4.5});give(m,'prensa',1);give(m,'azucar',1);act(m,{tipo:'produccion',accion:{tipo:'colocar_maquina',articulo:'prensa',zona:'granja',x:1,z:3},xJugador:1.5,zJugador:4.5});const id=m.estado.produccion.maquinas[0].id;act(m,{tipo:'produccion',accion:{tipo:'encolar_receta',id,recetaId:'mermelada_naranja',cantidad:1},xJugador:1.5,zJugador:4.5});assert.equal(m.estado.inventario.naranja??0,0);assert.equal(m.estado.inventario.azucar??0,0);const n=game();assert.equal(n.cargarJSON(m.exportar()).ok,true);now+=60*1000;n.actualizar();assert.equal(n.estado.produccion.maquinas[0].salida.filter(Boolean)[0].articulo,'mermelada_naranja');assert.equal(n.estado.produccion.maquinas[0].salida.filter(Boolean)[0].cantidad,1);assert.equal(n.estado.jornada.diasCompletados,0);assert.equal(n.estado.frutales[0].frutos,0);assert.equal(validarEstado(n.estado),null);});
test('Dos invernaderos conservan bancales y riego por identidad, sin recoger árboles remotos',()=>{const m=game(),primero=greenhouse(m);give(m,'creacion_invernadero',1);m.estado.obstaculos=m.estado.obstaculos.filter(o=>!(o.x>=2&&o.x<7&&o.z>=3&&o.z<7));act(m,{tipo:'construir',articulo:'invernadero',x:2,z:3});const segundo=m.estado.invernaderos[1].edificioId;enter(m,primero);seed(m);water(m,-3,-2);const f=plant(m,'cerezo',-6,-4);act(m,{tipo:'salir'});act(m,{tipo:'entrar',edificioId:segundo,xJugador:4.5,zJugador:7.5});seed(m);assert.equal(m.parcelasActuales().length,1);fail(m,{tipo:'recoger_frutal',id:f.id,xJugador:-5.5,zJugador:-2.5});act(m,{tipo:'salir'});sleep(m);morning(m);assert.equal(m.estado.invernaderos[0].parcelas[0].cuidado.grownMs,CRECIMIENTO_NOCHE_MS);assert.equal(m.estado.invernaderos[1].parcelas[0].cuidado.grownMs,0);assert.equal(validarEstado(m.estado),null);});

console.log(JSON.stringify({suite:'huerto-invernadero-jornadas',checks,failures}));if(failures)process.exitCode=1;
