// Escenas en la cocina: mesa del comedor en el medio (sillas en x −0,2 y 1,4; y −0,5), nevera al fondo
// (1,15; 1,0), estufa al fondo a la izquierda (−1,95; 1,15) y la puerta a la derecha (2,2; 1,35).
import type { Escena } from './tipos';

/** Altura del cuerpo sentado en la silla del comedor y de la mesa (para dejar cosas encima). */
export const SILLA = 0.34;
export const MESA = 0.74;

export const COCINA: Escena[] = [
  {
    id: 'cocinar-juntos',
    nombre: 'Cocinando juntos',
    descripcion: 'Cocinan en la estufa: uno prueba la sopa, «¡le falta sal!», cae harina por todos lados y terminan dándose de comer.',
    precio: 30,
    lugar: 'cocina',
    dur: 13,
    inicio: { A: [-1.95, 0.75, 180], B: [-1.1, 0.75, 180] },
    guion: [
      { t: 0, A: { pasos: [{ dur: 2.4, pose: 'frotar_a', pose2: 'frotar_b', ritmo: 2, cara: 'concentrado' }] }, B: { pasos: [{ dur: 2.4, pose: 'reponer', cara: 'feliz' }] }, camara: 'general', sub: 'Hoy cocinamos los dos.' },
      { t: 2.5, A: { rot: 'otro', pasos: [{ dur: 1.4, pose: 'comer_a', cara: 'concentrado' }] }, dice: ['A', 'Prueba, amor…'], camara: 'dos' },
      { t: 3.9, B: { rot: 'otro', pasos: [{ dur: 0.6, pose: 'comer_a', cara: 'beso' }, { dur: 1.2, pose: 'pensando', cara: 'concentrado', mov: [{ tipo: 'cabeza', eje: 'ladeo', grados: 10, frec: 0.8 }] }] }, sonido: 'duda' },
      { t: 5.7, B: { pasos: [{ dur: 1.2, pose: 'senalar_a', cara: 'presumido' }] }, dice: ['B', '¡Le falta sal!'], fx: [['B', { tipo: 'foco' }]] },
      { t: 7.0, B: { pasos: [{ dur: 0.6, pose: 'lanzar', cara: 'carcajada', suave: 30 }] }, particulas: ['crema', 'A'], sonido: 'pop', sub: '…y un puñado de harina.' },
      { t: 7.6, A: { pasos: [{ dur: 1.6, pose: 'boca_abierta', cara: 'sorprendido', mov: [{ tipo: 'temblor', amp: 0.01, frec: 10 }] }] }, fx: [['A', { tipo: 'polvo' }], ['A', { tipo: 'signo', c: '!?' }]], camara: 'caraA' },
      { t: 9.2, A: { pasos: [{ dur: 0.6, pose: 'lanzar', cara: 'carcajada', suave: 30 }] }, particulas: ['crema', 'B'], sonido: 'pop', camara: 'dos', sub: '' },
      { t: 9.9, A: { pasos: [{ dur: 1.4, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, B: { pasos: [{ dur: 1.4, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, fx: [['A', { tipo: 'risa' }], ['B', { tipo: 'risa' }]], sonido: 'carcajada' },
      { t: 11.4, A: { pasos: [{ dur: 1.6, pose: 'comer_a', cara: 'feliz' }] }, B: { pasos: [{ dur: 1.6, pose: 'comer_b', cara: 'feliz' }] }, fx: [['A', { tipo: 'corazones', n: 5 }]], sub: 'Quedó horrible. Y fue la mejor cena.' },
    ],
  },
  {
    id: 'ultimo-chocolate',
    nombre: 'El último chocolate',
    descripcion: 'Los dos abren la nevera al tiempo por el último chocolate: persecución alrededor de la mesa… y lo parten a la mitad.',
    precio: 30,
    lugar: 'cocina',
    dur: 13,
    inicio: { A: [0.3, 0.9, 180], B: [2.2, 1.35, -90] },
    guion: [
      { t: 0, camara: 'general', A: { ir: [1.0, 1.0], vel: 0.8, rot: 180 }, sub: 'Antojo de medianoche…' },
      { t: 1.4, A: { prop: 'chocolate', rot: 0, pasos: [{ dur: 1.2, pose: 'trofeo', cara: 'presumido' }] }, fx: [['A', { tipo: 'brillo' }]], sonido: 'tin', dice: ['A', '¡El último!'] },
      { t: 2.2, B: { ir: [1.6, 0.9], vel: 1.4, rot: 'otro', pasos: [{ dur: 1, pose: 'boca_abierta', cara: 'sorprendido' }] }, dice: ['B', '¡ESE ES MÍO!'], camara: 'dos' },
      { t: 3.6, A: { ir: [-0.8, -0.4], vel: 2.0, pasos: [{ dur: 4, cara: 'carcajada' }] }, sonido: 'huida' },
      { t: 3.9, B: { ir: [0.6, 0.3], vel: 1.9, pasos: [{ dur: 4, cara: 'enojado' }] } },
      { t: 5.0, A: { ir: [0.6, -1.4], vel: 2.0 }, B: { ir: [-0.8, -0.3], vel: 1.9 }, dice: ['A', '¡Jajaja, no me alcanzas!'], camara: 'general' },
      { t: 6.2, A: { ir: [2.0, -0.6], vel: 2.0 }, B: { ir: [0.6, -1.4], vel: 1.9 } },
      { t: 7.4, A: { rot: 'otro', pasos: [{ dur: 1.6, pose: 'impaciente_a', cara: 'nervioso' }] }, B: { ir: [1.5, -0.9], vel: 1.4, rot: 'otro', pasos: [{ dur: 1.6, pose: 'jarras', cara: 'enojado' }] }, fx: [['A', { tipo: 'gotita' }]], dice: ['B', 'Acorralado…'], camara: 'dos' },
      { t: 9.0, A: { pasos: [{ dur: 1.2, pose: 'regalo', cara: 'feliz' }] }, dice: ['A', '¿Mitad y mitad?'] },
      { t: 10.2, B: { prop: 'chocolate', pasos: [{ dur: 1.2, pose: 'regalo', cara: 'feliz' }] }, A: { prop: 'chocolate' }, sonido: 'tin', fx: [['B', { tipo: 'corazones', n: 4 }]], camara: 'dos' },
      { t: 11.4, A: { pasos: [{ dur: 1.5, pose: 'comer_a', pose2: 'comer_b', ritmo: 2, cara: 'feliz' }] }, B: { pasos: [{ dur: 1.5, pose: 'comer_a', pose2: 'comer_b', ritmo: 2, cara: 'feliz' }] }, sub: 'Compartido sabe mejor.' },
    ],
  },
  {
    id: 'helado-robado',
    nombre: 'El helado robado',
    descripcion: 'Uno disfruta su helado en la mesa; el otro se lo roba de un mordisco… y le da congelamiento cerebral.',
    precio: 25,
    lugar: 'cocina',
    dur: 11,
    inicio: { A: [-0.2, -0.5, 90], B: [1.8, 0.4, -120] },
    props: { A: 'helado' },
    guion: [
      { t: 0, A: { alto: SILLA, pasos: [{ dur: 3, pose: 'comer_sentado_a', pose2: 'comer_sentado_b', ritmo: 1.2, cara: 'feliz' }] }, camara: 'general', sub: 'Mmm… helado.' },
      { t: 1.4, B: { ir: [0.3, -0.95], vel: 0.5, rot: 'otro', pasos: [{ dur: 2.6, pose: 'frotar_manos_a', pose2: 'frotar_manos_b', ritmo: 3, cara: 'presumido' }] }, fx: [['B', { tipo: 'brillo' }]] },
      { t: 3.2, A: { pasos: [{ dur: 1.2, pose: 'sentado', cara: 'feliz' }] }, camara: 'dos' },
      { t: 4.2, B: { pasos: [{ dur: 0.8, pose: 'comer_a', cara: 'beso', mov: [{ tipo: 'acercarse', cuanto: 0.6 }] }] }, sonido: 'pop', dice: ['B', '¡ÑAM!'] },
      { t: 5.0, A: { pasos: [{ dur: 1.4, pose: 'boca_abierta', cara: 'enojado' }] }, dice: ['A', '¡¿Mi helado?!'], fx: [['A', { tipo: 'vena', dur: 1.2 }]], sub: '' },
      { t: 6.4, B: { pasos: [{ dur: 2, pose: 'llorar_a', cara: 'llorando', mov: [{ tipo: 'temblor', amp: 0.015, frec: 14 }] }] }, fx: [['B', { tipo: 'rayos' }], ['B', { tipo: 'signo', c: '!' }]], sonido: 'wawa', dice: ['B', '¡Ay, el cerebro! ¡Se me congeló!'], camara: 'B' },
      { t: 8.4, A: { pasos: [{ dur: 1.4, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, sonido: 'carcajada', fx: [['A', { tipo: 'risa', texto: 'JA JA' }]], dice: ['A', 'Karma instantáneo.'], camara: 'dos' },
      { t: 9.8, A: { pasos: [{ dur: 1.2, pose: 'acariciar', cara: 'feliz' }] }, B: { pasos: [{ dur: 1.2, pose: 'recibir_caricia', cara: 'puchero' }] }, sub: 'Aún así, le compartió.' },
    ],
  },
  {
    id: 'desayuno-sorpresa',
    nombre: 'Desayuno sorpresa',
    descripcion: 'Uno prepara el desayuno con flores y café; el otro llega medio dormido y se despierta de golpe de la emoción.',
    precio: 30,
    lugar: 'cocina',
    dur: 12,
    inicio: { A: [-1.4, 0.8, 180], B: [2.2, 1.35, -90] },
    guion: [
      { t: 0, A: { pasos: [{ dur: 2, pose: 'frotar_a', pose2: 'frotar_b', ritmo: 2, cara: 'concentrado' }] }, fx: [['A', { tipo: 'notas', dur: 2 }]], camara: 'general', sub: 'Muy temprano en la cocina…' },
      { t: 2.0, A: { prop: 'taza', ir: [1.0, -0.95], vel: 0.9, rot: 0 } },
      { t: 3.6, A: { prop: null, pasos: [{ dur: 0.7, pose: 'reponer', cara: 'feliz' }] }, objeto: { id: 'taza', prop: 'taza', en: [0.95, -0.5, MESA] } },
      { t: 4.3, objeto: { id: 'ramo', prop: 'ramo', en: [0.45, -0.5, MESA] }, A: { pasos: [{ dur: 0.8, pose: 'jarras', cara: 'presumido' }] }, sonido: 'tin' },
      { t: 5.2, B: { ir: [1.8, -0.1], vel: 0.45, pasos: [{ dur: 2.2, pose: 'bostezo', cara: 'bostezo' }] }, sonido: 'bostezo', fx: [['B', { tipo: 'zzz', dur: 1.6 }]], sub: '' },
      { t: 7.4, B: { rot: 'otro', pasos: [{ dur: 0.4, pose: 'boca_abierta', cara: 'sorprendido', mov: [{ tipo: 'salto', alto: 0.12 }] }] }, fx: [['B', { tipo: 'signo', c: '!' }]], sonido: 'sorpresa', camara: 'B' },
      { t: 7.9, B: { pasos: [{ dur: 1.4, pose: 'celebrar', cara: 'carcajada', mov: [{ tipo: 'rebote', alto: 0.12, frec: 3 }] }] }, dice: ['B', '¿Todo esto para mí?'], fx: [['B', { tipo: 'corazones', n: 6 }]] },
      { t: 9.4, B: { ir: [1.35, -0.85], vel: 1.4, rot: 'otro' }, A: { rot: 'otro' }, camara: 'dos' },
      { t: 10.4, A: { coreo: 'abrazo' }, B: { coreo: 'abrazo' }, sonido: 'abrazo', sub: 'Los buenos días más dulces.' },
    ],
  },
  {
    id: 'guerra-crema',
    nombre: 'Guerra de crema',
    descripcion: 'Un pastel en la mesa, un dedo con crema en la nariz… y se desata la guerra de crema en la cocina.',
    precio: 35,
    lugar: 'cocina',
    dur: 12,
    inicio: { A: [0.1, -1.1, 30], B: [1.2, -1.1, -30] },
    guion: [
      { t: 0, objeto: { id: 'pastel', prop: 'pastel', en: [0.6, -0.5, MESA] }, camara: 'general', sub: 'El pastel quedó precioso…' },
      { t: 1.2, A: { rot: 'otro', pasos: [{ dur: 1, pose: 'senalar_a', cara: 'presumido', mov: [{ tipo: 'acercarse', cuanto: 0.6 }] }] }, particulas: ['crema', 'B'], sonido: 'pop', dice: ['A', '¡Boop!'], camara: 'dos' },
      { t: 2.3, B: { pasos: [{ dur: 1.4, pose: 'boca_abierta', cara: 'sorprendido' }] }, fx: [['B', { tipo: 'signo', c: '!?' }]], sub: '' },
      { t: 3.7, B: { rot: 180, pasos: [{ dur: 0.6, pose: 'reponer', cara: 'enojado' }] }, objeto: { id: 'pastel', quitar: true } },
      { t: 4.3, B: { prop: 'pastel', rot: 'otro', pasos: [{ dur: 0.8, pose: 'trofeo', cara: 'presumido' }] }, dice: ['B', 'Tú te lo buscaste…'] },
      { t: 5.1, B: { prop: null, pasos: [{ dur: 0.5, pose: 'lanzar', cara: 'carcajada', suave: 32 }] }, particulas: ['crema', 'A'], sonido: 'splash', temblor: 0.3, camara: 'caraA' },
      { t: 5.7, A: { pasos: [{ dur: 1.4, pose: 'boca_abierta', cara: 'sorprendido', mov: [{ tipo: 'temblor', amp: 0.01, frec: 10 }] }] }, fx: [['A', { tipo: 'gotita' }]] },
      { t: 7.2, A: { pasos: [{ dur: 2.2, pose: 'agitar_a', pose2: 'lanzar', ritmo: 2.4, cara: 'carcajada' }] }, B: { pasos: [{ dur: 2.2, pose: 'agitar_a', pose2: 'lanzar', ritmo: 2.2, cara: 'carcajada' }] }, particulas: ['crema', [0.6, -1.0]], sonido: 'splash', camara: 'general', sub: '¡Guerra!' },
      { t: 8.2, particulas: ['crema', [0.9, -1.1]], sonido: 'splash' },
      { t: 9.5, A: { pasos: [{ dur: 2.4, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, B: { pasos: [{ dur: 2.4, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, fx: [['A', { tipo: 'risa' }], ['B', { tipo: 'risa' }]], sonido: 'carcajada', camara: 'dos', sub: 'Nadie se comió el pastel. Valió la pena.' },
    ],
  },
  {
    id: 'cena-romantica',
    nombre: 'Cena romántica',
    descripcion: 'Una cena a la luz de las velas en el comedor: brindis, miradas… y los dos comiendo del mismo espagueti.',
    precio: 45,
    lugar: 'cocina',
    dur: 13,
    inicio: { A: [-0.2, -0.5, 90], B: [1.4, -0.5, -90] },
    guion: [
      { t: 0, A: { alto: SILLA, pasos: [{ dur: 2.5, pose: 'sentado', cara: 'feliz' }] }, B: { alto: SILLA, pasos: [{ dur: 2.5, pose: 'sentado', cara: 'feliz' }] }, objeto: { id: 'ramo', prop: 'ramo', en: [0.6, -0.3, MESA] }, camara: 'general', sub: 'Cena para dos.' },
      { t: 0.6, sonido: 'musiquita', fx: [['A', { tipo: 'notas', dur: 3 }]] },
      { t: 2.5, A: { prop: 'taza', pasos: [{ dur: 1.5, pose: 'trofeo', cara: 'feliz' }] }, B: { prop: 'taza', pasos: [{ dur: 1.5, pose: 'trofeo', cara: 'feliz' }] }, dice: ['A', 'Por nosotros.'], camara: 'dos' },
      { t: 4.0, sonido: 'tin', dice: ['B', 'Salud, mi amor.'], fx: [['A', { tipo: 'chispa' }]] },
      { t: 5.2, A: { prop: null, pasos: [{ dur: 2.5, pose: 'comer_sentado_a', pose2: 'comer_sentado_b', ritmo: 1, cara: 'feliz' }] }, B: { prop: null, pasos: [{ dur: 2.5, pose: 'comer_sentado_a', pose2: 'comer_sentado_b', ritmo: 1, cara: 'feliz' }] }, sub: 'El mismo espagueti…' },
      { t: 7.8, A: { pasos: [{ dur: 1, pose: 'comer_a', cara: 'sorprendido', mov: [{ tipo: 'acercarse', cuanto: 0.35 }] }] }, B: { pasos: [{ dur: 1, pose: 'comer_a', cara: 'sorprendido', mov: [{ tipo: 'acercarse', cuanto: 0.35 }] }] }, camara: 'dos', sub: '…¿el mismo espagueti?' },
      { t: 8.8, A: { pasos: [{ dur: 1.6, pose: 'beso', cara: 'beso', mov: [{ tipo: 'acercarse', cuanto: 0.4 }] }] }, B: { pasos: [{ dur: 1.6, pose: 'beso', cara: 'beso', mov: [{ tipo: 'acercarse', cuanto: 0.4 }] }] }, sonido: 'beso', fx: [['A', { tipo: 'corazones', n: 8 }], ['B', { tipo: 'sonrojo', dur: 2.5 }]], sub: '' },
      { t: 10.6, A: { pasos: [{ dur: 2, pose: 'sentado_feliz', cara: 'carcajada' }] }, B: { pasos: [{ dur: 2, pose: 'sentado_feliz', cara: 'carcajada' }] }, fx: [['A', { tipo: 'risa', texto: 'ji ji' }]], sub: 'Como en la película, pero mejor.' },
    ],
  },
];
