// Escenas en el cuarto: cama al fondo con la cabecera contra la pared (acostados en x −0,4 y 0,6; y 0,7),
// clóset a la izquierda (−1,55; −0,8) y la puerta a la derecha (2,3; 1,35).
import type { Escena } from './tipos';

/** Altura del cuerpo acostado en la cama y sentado en el borde. */
export const CAMA = 0.78;
export const BORDE = 0.5;

export const CUARTO: Escena[] = [
  {
    id: 'guerra-almohadas',
    nombre: 'Guerra de almohadas',
    descripcion: 'Un almohadazo por sorpresa y empieza la guerra: plumas por todo el cuarto hasta que caen rendidos en la cama.',
    precio: 45,
    lugar: 'cuarto',
    dur: 13,
    inicio: { A: [-0.9, -0.7, 60], B: [0.9, -0.7, -60] },
    props: { A: 'almohada', B: 'almohada' },
    guion: [
      { t: 0, camara: 'general', sub: 'Hora de dormir… o eso creían.' },
      { t: 0.8, A: { pasos: [{ dur: 1.2, pose: 'frotar_manos_a', pose2: 'frotar_manos_b', ritmo: 3, cara: 'presumido' }] }, fx: [['A', { tipo: 'brillo' }]] },
      { t: 2.0, A: { pasos: [{ dur: 0.35, pose: 'preparar_salto', cara: 'carcajada', mov: [{ tipo: 'acercarse', cuanto: 0.7 }] }, { dur: 0.6, pose: 'lanzar', cara: 'carcajada', suave: 30, mov: [{ tipo: 'acercarse', cuanto: 0.7 }] }] }, camara: 'dos' },
      { t: 2.6, B: { pasos: [{ dur: 0.9, pose: 'boca_abierta', cara: 'sorprendido', mov: [{ tipo: 'temblor', amp: 0.02, frec: 12 }] }] }, particulas: ['plumas', 'B'], sonido: 'almohadazo', fx: [['B', { tipo: 'rayos' }]], temblor: 0.2 },
      { t: 3.5, B: { pasos: [{ dur: 0.8, pose: 'enojo_a', cara: 'enojado' }] }, dice: ['B', '¡Ah, sí! ¿GUERRA?'], fx: [['B', { tipo: 'vena', dur: 1 }]] },
      { t: 4.4, B: { pasos: [{ dur: 0.5, pose: 'preparar_salto', cara: 'carcajada', mov: [{ tipo: 'acercarse', cuanto: 0.7 }] }, { dur: 0.6, pose: 'lanzar', cara: 'carcajada', suave: 30, mov: [{ tipo: 'acercarse', cuanto: 0.7 }] }] } },
      { t: 5.0, A: { pasos: [{ dur: 0.8, pose: 'encogerse', cara: 'carcajada', mov: [{ tipo: 'temblor', amp: 0.02, frec: 12 }] }] }, particulas: ['plumas', 'A'], sonido: 'almohadazo', temblor: 0.25 },
      { t: 5.9, A: { pasos: [{ dur: 2.2, pose: 'agitar_a', pose2: 'lanzar', ritmo: 2.2, cara: 'carcajada', sonidoRitmo: 'almohadazo', mov: [{ tipo: 'acercarse', cuanto: 0.6 }] }] }, B: { pasos: [{ dur: 2.2, pose: 'agitar_a', pose2: 'lanzar', ritmo: 2.4, cara: 'carcajada', mov: [{ tipo: 'acercarse', cuanto: 0.6 }] }] }, particulas: ['plumas', [0, -0.7]], sub: '¡PAF! ¡PUF! ¡PAF!', camara: 'general' },
      { t: 7.0, particulas: ['plumas', [0.2, -0.4]], fx: [['A', { tipo: 'risa', texto: 'JA JA' }], ['B', { tipo: 'risa', texto: 'JI JI' }]], sonido: 'carcajada' },
      { t: 8.2, A: { prop: null, ir: [-0.4, 0.7], vel: 1.2, rot: 0 }, B: { prop: null, ir: [0.6, 0.7], vel: 1.2, rot: 0 }, sub: '' },
      { t: 9.6, A: { alto: 0.78, acostado: true, pasos: [{ dur: 3.4, pose: 'tirado', cara: 'carcajada' }] }, B: { alto: 0.78, acostado: true, pasos: [{ dur: 3.4, pose: 'tirado', cara: 'carcajada' }] }, sonido: 'plaf', particulas: ['plumas', [0.1, 0.5]], camara: 'dos' },
      { t: 11.0, fx: [['A', { tipo: 'corazones', n: 4 }], ['B', { tipo: 'corazones', n: 4 }]], sub: 'Empate técnico. Y el cuarto lleno de plumas.' },
    ],
  },
  {
    // (el id viene de cuando era «La propuesta»: así no se pierde en las compras guardadas; la propuesta es un
    //  recuerdo de Cien Puertas y no se repite aquí)
    id: 'la-propuesta',
    nombre: 'Baile lento',
    descripcion: 'Pétalos por todo el cuarto, una flor y un baile lento sin música… hasta que uno pisa al otro.',
    precio: 100,
    lugar: 'cuarto',
    dur: 15,
    inicio: { A: [1.4, -0.9, -60], B: [-0.6, -0.4, 30] },
    props: { A: 'ramo' },
    guion: [
      { t: 0, camara: 'general', B: { pasos: [{ dur: 2, pose: 'pensando', cara: 'aburrido' }] }, sub: 'Una noche especial…' },
      { t: 1.0, A: { ir: [0.4, -0.55], vel: 0.6, rot: 'otro', pasos: [{ dur: 2.2, cara: 'nervioso' }] }, fx: [['A', { tipo: 'gotita' }]] },
      { t: 2.8, A: { pasos: [{ dur: 1.4, pose: 'regalo', cara: 'feliz' }] }, B: { rot: 'otro', pasos: [{ dur: 1.4, pose: 'boca_abierta', cara: 'sorprendido' }] }, dice: ['B', '¿Y esas flores?'], camara: 'dos' },
      { t: 4.2, A: { prop: null }, B: { prop: 'ramo', pasos: [{ dur: 1.6, pose: 'regalo', cara: 'feliz' }] }, fx: [['B', { tipo: 'sonrojo', dur: 2 }]] },
      { t: 5.6, A: { pasos: [{ dur: 1.4, pose: 'reverencia', cara: 'guino' }] }, particulas: ['petalos', [0, -0.3]], sonido: 'musiquita', camara: 'dos', dice: ['A', '¿Me concede este baile?'] },
      { t: 7.4, A: { pasos: [{ dur: 3, pose: 'abrazo', cara: 'feliz', mov: [{ tipo: 'acercarse', cuanto: 1 }, { tipo: 'mirar', a: 'otro' }, { tipo: 'balanceo', grados: 7, frec: 0.6 }] }] }, B: { prop: null, pasos: [{ dur: 3, pose: 'abrazo', cara: 'feliz', mov: [{ tipo: 'acercarse', cuanto: 1 }, { tipo: 'mirar', a: 'otro' }, { tipo: 'balanceo', grados: 7, frec: 0.6 }] }] }, camara: 'dos', sub: 'Sin música… pero con ritmo.' },
      { t: 10.4, B: { pasos: [{ dur: 1, pose: 'boca_abierta', cara: 'sorprendido', mov: [{ tipo: 'salto', alto: 0.2 }] }] }, dice: ['B', '¡Auch, mi pie!'], sonido: 'sorpresa', fx: [['B', { tipo: 'signo', c: '!' }]], sub: '' },
      { t: 11.6, A: { pasos: [{ dur: 1.6, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, B: { pasos: [{ dur: 1.6, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, sonido: 'carcajada', fx: [['A', { tipo: 'risa' }], ['B', { tipo: 'risa' }]] },
      { t: 13.2, A: { pasos: [{ dur: 1.6, pose: 'beso', cara: 'beso' }] }, B: { pasos: [{ dur: 1.6, pose: 'beso', cara: 'beso' }] }, sonido: 'beso', fx: [['A', { tipo: 'corazones', n: 8 }]], sub: 'Con pisotones y todo, te elegiría en todas las vidas.' },
    ],
  },
  {
    id: 'despertar-besos',
    nombre: 'Despertar a besos',
    descripcion: 'Suena la alarma; uno no se quiere levantar y el otro lo despierta a besos hasta que se ríe.',
    precio: 25,
    lugar: 'cuarto',
    dur: 12,
    inicio: { A: [-0.4, 0.7, 0], B: [0.6, 0.7, 0] },
    guion: [
      { t: 0, A: { alto: CAMA, acostado: true, pasos: [{ dur: 5, pose: 'dormido', cara: 'dormido' }] }, B: { alto: CAMA, acostado: true, pasos: [{ dur: 2, pose: 'dormido', cara: 'dormido' }] }, camara: 'general', fx: [['A', { tipo: 'zzz', dur: 4 }], ['B', { tipo: 'zzz', dur: 1.8 }]], sub: 'Seis de la mañana…' },
      { t: 1.8, sonido: 'tictac', fx: [['B', { tipo: 'reloj' }]], sub: '¡RIIIING!' },
      { t: 2.4, B: { acostado: false, pasos: [{ dur: 1.4, pose: 'bostezo', cara: 'bostezo' }] }, sonido: 'bostezo', sub: '' },
      { t: 3.6, B: { rot: -50, pasos: [{ dur: 1, pose: 'inclinado', cara: 'feliz' }] }, dice: ['B', 'Amor… arriba, que es tarde.'], camara: 'dos' },
      { t: 4.8, A: { pasos: [{ dur: 1.6, pose: 'dormido', cara: 'puchero', mov: [{ tipo: 'cabeza', eje: 'no', grados: 12, frec: 1.5 }] }] }, dice: ['A', 'Cinco minutitos más…'] },
      { t: 6.4, B: { pasos: [{ dur: 1, pose: 'beso', cara: 'beso' }] }, sonido: 'beso', fx: [['A', { tipo: 'beso' }]], camara: 'caraA' },
      { t: 7.4, B: { pasos: [{ dur: 1, pose: 'beso', cara: 'beso' }] }, sonido: 'beso', fx: [['A', { tipo: 'corazones', n: 3 }]] },
      { t: 8.4, A: { pasos: [{ dur: 1.6, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, B: { pasos: [{ dur: 1.2, pose: 'beso', cara: 'beso' }] }, sonido: 'risita', fx: [['A', { tipo: 'sonrojo', dur: 2 }]], camara: 'dos' },
      { t: 10.0, A: { acostado: false, pasos: [{ dur: 1.8, pose: 'abrazo_der', cara: 'feliz' }] }, B: { pasos: [{ dur: 1.8, pose: 'abrazo_izq', cara: 'feliz' }] }, dice: ['A', 'Así sí me levanto.'], sub: 'La mejor alarma del mundo.' },
    ],
  },
  {
    id: 'carta-de-amor',
    nombre: 'La carta',
    descripcion: 'Uno deja una carta en la almohada; el otro la lee y termina llorando de amor.',
    precio: 30,
    lugar: 'cuarto',
    dur: 13,
    inicio: { A: [2.3, 1.35, -90], B: [-0.7, -1.3, 0] },
    props: { A: 'carta' },
    guion: [
      { t: 0, camara: 'general', sub: 'Una sorpresa escondida…' },
      { t: 0.4, A: { ir: [1.9, 0.9], vel: 0.55, pasos: [{ dur: 2.6, cara: 'presumido' }] }, fx: [['A', { tipo: 'signo', c: '♪' }]], sonido: 'pasos' },
      { t: 3.0, A: { prop: null, pasos: [{ dur: 0.8, pose: 'reponer', cara: 'feliz' }] }, objeto: { id: 'carta', prop: 'carta', en: [0.6, 1.3, 0.62] } },
      { t: 3.9, A: { ir: [2.3, 1.35], vel: 1.4 }, dice: ['A', 'Shhh…'] },
      { t: 4.9, A: { en: [2.9, 1.35] }, B: { ir: [0.9, 0.2], vel: 0.9, rot: 180 }, sub: '' },
      { t: 6.4, objeto: { id: 'carta', quitar: true }, B: { prop: 'carta', rot: 0, pasos: [{ dur: 1.2, pose: 'boca_abierta', cara: 'sorprendido' }] }, fx: [['B', { tipo: 'signo', c: '!' }]], camara: 'B' },
      { t: 7.6, B: { pasos: [{ dur: 2.4, pose: 'regalo', cara: 'concentrado', mov: [{ tipo: 'cabeza', eje: 'ladeo', grados: 6, frec: 0.5 }] }] }, sub: '«Gracias por cada día a tu lado…»' },
      { t: 10.0, B: { pasos: [{ dur: 1.6, pose: 'regalo', cara: 'llorando', mov: [{ tipo: 'temblor', amp: 0.005, frec: 10 }] }] }, fx: [['B', { tipo: 'lagrimas', dur: 1.8, risa: true }]], sub: '«…te amo más que ayer.»', camara: 'caraB' },
      { t: 10.4, A: { en: [2.3, 1.35], ir: [1.6, 0.1], vel: 1, rot: 'otro' } },
      { t: 11.6, A: 'abrazo', B: { prop: null, coreo: 'abrazo' }, sonido: 'abrazo', fx: [['B', { tipo: 'corazones', n: 8 }]], camara: 'dos', sub: '' },
    ],
  },
  {
    id: 'cuento-dormir',
    nombre: 'Cuento para dormir',
    descripcion: 'Uno lee un cuento en la cama con voces chistosas; el otro se duerme… y al final el que lee también.',
    precio: 25,
    lugar: 'cuarto',
    dur: 13,
    inicio: { A: [-0.4, 0.7, 0], B: [0.6, 0.7, 0] },
    props: { A: 'libro' },
    guion: [
      { t: 0, A: { alto: CAMA, acostado: false, pasos: [{ dur: 3, pose: 'sentado', cara: 'concentrado' }] }, B: { alto: CAMA, acostado: true, pasos: [{ dur: 5, pose: 'dormido', cara: 'feliz' }] }, camara: 'dos', sub: 'Érase una vez…' },
      { t: 1.4, dice: ['A', '…una princesa que ganaba TODOS los juegos…'] },
      { t: 3.4, A: { pasos: [{ dur: 1.6, pose: 'enojo_a', cara: 'enojado', mov: [{ tipo: 'inflarse', cuanto: 0.06 }] }] }, dice: ['A', '«¡GRRR! Soy el dragón perdedor»'], sonido: 'enojo' },
      { t: 5.0, B: { pasos: [{ dur: 1.2, pose: 'dormido', cara: 'carcajada' }] }, fx: [['B', { tipo: 'risa', texto: 'ji ji' }]], sonido: 'risita' },
      { t: 6.2, A: { pasos: [{ dur: 2, pose: 'sentado', cara: 'feliz' }] }, B: { pasos: [{ dur: 5, pose: 'dormido', cara: 'dormido' }] }, fx: [['B', { tipo: 'zzz', dur: 5 }]], dice: ['A', '…y vivieron felices…'], camara: 'caraB' },
      { t: 8.4, A: { pasos: [{ dur: 1.2, pose: 'bostezo', cara: 'bostezo' }] }, sonido: 'bostezo', camara: 'dos' },
      { t: 9.8, A: { prop: null, acostado: true, pasos: [{ dur: 3, pose: 'dormido', cara: 'dormido' }] }, objeto: { id: 'libro', prop: 'libro', en: [-0.3, 0.2, 0.82] }, fx: [['A', { tipo: 'zzz', dur: 3 }]] },
      { t: 11.0, sub: '…para siempre. Zzz…', fx: [['A', { tipo: 'corazones', n: 3 }], ['B', { tipo: 'corazones', n: 3 }]] },
    ],
  },
  {
    id: 'monstruo-cama',
    nombre: 'El monstruo de la cama',
    descripcion: 'Un ruido raro en la noche, uno se esconde bajo la cobija y el otro sale a enfrentar al «monstruo»… que es el peluche.',
    precio: 30,
    lugar: 'cuarto',
    dur: 13,
    inicio: { A: [-0.4, 0.7, 0], B: [0.6, 0.7, 0] },
    guion: [
      { t: 0, A: { alto: CAMA, acostado: true, pasos: [{ dur: 2, pose: 'dormido', cara: 'dormido' }] }, B: { alto: CAMA, acostado: true, pasos: [{ dur: 2, pose: 'dormido', cara: 'dormido' }] }, camara: 'general', sub: 'Medianoche…' },
      { t: 1.6, sonido: 'wawa', temblor: 0.3, sub: '¡CRRRAC!' },
      { t: 2.2, B: { acostado: false, pasos: [{ dur: 2.6, pose: 'encogerse', cara: 'nervioso', mov: [{ tipo: 'temblor', amp: 0.012, frec: 14 }] }] }, fx: [['B', { tipo: 'gotita' }], ['B', { tipo: 'signo', c: '!?' }]], dice: ['B', '¿Oíste eso?'], camara: 'dos', sub: '' },
      { t: 3.6, A: { acostado: false, pasos: [{ dur: 1.2, pose: 'sentado', cara: 'sorprendido' }] }, dice: ['A', 'Tranquila… yo voy.'] },
      { t: 4.9, A: { alto: 0, prop: 'lupa', ir: [-1.3, -0.3], vel: 0.5, pasos: [{ dur: 3, pose: 'inclinado', cara: 'nervioso' }] }, B: { pasos: [{ dur: 5, pose: 'encogerse', cara: 'nervioso' }] }, camara: 'A', sub: 'Paso… a paso…' },
      { t: 7.6, sonido: 'sorpresa', A: { pasos: [{ dur: 0.4, pose: 'boca_abierta', cara: 'sorprendido', mov: [{ tipo: 'salto', alto: 0.35 }] }] }, fx: [['A', { tipo: 'rayos' }]], objeto: { id: 'osito', prop: 'peluche', en: [-1.9, -0.6, 0.05] }, temblor: 0.3, sub: '¡¡AAAH!!' },
      { t: 8.4, A: { prop: 'peluche', pasos: [{ dur: 1.6, pose: 'trofeo', cara: 'presumido', mov: [{ tipo: 'inflarse', cuanto: 0.06 }] }] }, objeto: { id: 'osito', quitar: true }, dice: ['A', '…era el osito.'], sub: '', camara: 'dos' },
      { t: 10.0, B: { pasos: [{ dur: 1.8, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, fx: [['B', { tipo: 'risa', texto: 'JA JA JA' }]], sonido: 'carcajada', dice: ['B', '¡Mi héroe!'] },
      { t: 11.4, A: { ir: [-0.4, 0.2], vel: 1.2, rot: 0, pasos: [{ dur: 1.4, cara: 'puchero' }] }, fx: [['A', { tipo: 'sonrojo', dur: 1.4 }]], sub: 'El monstruo más tierno de la casa.' },
    ],
  },
  {
    id: 'desfile-closet',
    nombre: 'Desfile del clóset',
    descripcion: 'Uno se prueba sombreros frente al clóset y desfila como modelo; el otro califica con aplausos y fotos.',
    precio: 30,
    lugar: 'cuarto',
    dur: 13,
    inicio: { A: [-1.45, -0.8, -90], B: [1.3, -0.4, -60] },
    guion: [
      { t: 0, camara: 'general', A: { pasos: [{ dur: 1.4, pose: 'reponer', cara: 'concentrado' }] }, sub: 'Desfile de modas, temporada casa.' },
      { t: 1.4, A: { prop: 'sombrero', rot: 0, pasos: [{ dur: 1.2, pose: 'jarras', cara: 'presumido' }] }, sonido: 'pop' },
      { t: 2.6, A: { ir: [0.2, -1.2], vel: 0.7, pasos: [{ dur: 2.2, pose: 'presumir_a', cara: 'presumido', mov: [{ tipo: 'balanceo', grados: 8, frec: 1.6 }] }] }, sonido: 'musiquita', camara: 'A' },
      { t: 4.8, A: { rot: 'camara', pasos: [{ dur: 1.2, pose: 'musculo', cara: 'guino' }] }, B: { prop: 'camara' }, flash: true, dice: ['B', '¡Divino!'] },
      { t: 6.0, A: { rot: 'camara', pasos: [{ dur: 1.4, pose: 'presumir_b', cara: 'presumido', mov: [{ tipo: 'giro', vueltas: 1 }] }] }, flash: true, camara: 'dos' },
      { t: 7.6, A: { prop: 'corona', pasos: [{ dur: 1.4, pose: 'corona', cara: 'presumido' }] }, sonido: 'tada', fx: [['A', { tipo: 'brillo' }]], sub: 'Cambio de vestuario: ¡REALEZA!' },
      { t: 9.0, B: { prop: null, pasos: [{ dur: 1.8, pose: 'aplauso_a', pose2: 'aplauso_b', ritmo: 3, cara: 'carcajada', sonidoRitmo: 'palmada' }] }, dice: ['B', '¡Diez de diez!'], sub: '' },
      { t: 10.8, A: { pasos: [{ dur: 1.4, pose: 'reverencia', cara: 'feliz' }] }, fx: [['A', { tipo: 'estrellas', n: 6 }], ['B', { tipo: 'corazones', n: 4 }]], sub: 'La modelo más linda (y más chistosa).' },
    ],
  },
  {
    id: 'lado-de-la-cama',
    nombre: 'La guerra del lado de la cama',
    descripcion: 'Los dos se acuestan y se empujan por espacio y por la cobija… hasta que terminan en el medio, abrazados.',
    precio: 25,
    lugar: 'cuarto',
    dur: 12,
    inicio: { A: [-0.4, 0.7, 0], B: [0.6, 0.7, 0] },
    guion: [
      { t: 0, A: { alto: CAMA, acostado: true, pasos: [{ dur: 2, pose: 'dormido', cara: 'feliz' }] }, B: { alto: CAMA, acostado: true, pasos: [{ dur: 2, pose: 'dormido', cara: 'feliz' }] }, camara: 'dos', sub: 'Buenas noches, amor.' },
      { t: 1.8, A: { ir: [-0.05, 0.7], vel: 0.4, pasos: [{ dur: 1.4, pose: 'dormido', cara: 'presumido' }] }, B: { pasos: [{ dur: 1.4, pose: 'dormido', cara: 'sorprendido' }] }, sub: 'Un poquito más acá…' },
      { t: 3.2, B: { ir: [0.3, 0.7], vel: 0.4, pasos: [{ dur: 1.6, pose: 'enojo_a', cara: 'enojado' }] }, A: { ir: [-0.6, 0.7], vel: 0.5, pasos: [{ dur: 1.4, pose: 'dormido', cara: 'sorprendido' }] }, dice: ['B', '¡Ese es MI lado!'], sonido: 'hmph', sub: '' },
      { t: 4.8, A: { ir: [-0.2, 0.7], vel: 0.6, pasos: [{ dur: 1.4, pose: 'enojo_a', cara: 'enojado', mov: [{ tipo: 'temblor', amp: 0.01, frec: 12 }] }] }, B: { ir: [0.6, 0.7], vel: 0.5, pasos: [{ dur: 1.4, pose: 'dormido', cara: 'sorprendido' }] }, fx: [['A', { tipo: 'humo', dur: 1 }]], sonido: 'agitar' },
      { t: 6.2, B: { ir: [0.95, 0.7], vel: 0.3, pasos: [{ dur: 1.4, pose: 'dormido', cara: 'puchero' }] }, dice: ['B', 'Y la cobija también es mía…'], fx: [['A', { tipo: 'signo', c: '!?' }]] },
      { t: 7.6, A: { pasos: [{ dur: 1.2, pose: 'dormido', cara: 'guino' }] }, dice: ['A', 'Bueno… entonces ven acá.'], camara: 'caraA' },
      { t: 8.8, A: { ir: [0.05, 0.7], vel: 0.5, pasos: [{ dur: 3, pose: 'abrazo_der', cara: 'dormido' }] }, B: { ir: [0.4, 0.7], vel: 0.5, pasos: [{ dur: 3, pose: 'abrazo_izq', cara: 'dormido' }] }, fx: [['A', { tipo: 'corazones', n: 5 }], ['B', { tipo: 'zzz', dur: 2.5 }]], camara: 'dos', sub: 'Al final, el lado favorito es el del medio.' },
    ],
  },
  {
    // (el id viene de cuando discutían el nombre de la bebé, que es de Cien Puertas: así no se pierde en las
    //  compras guardadas)
    id: 'nombres-bebe',
    nombre: '¿Qué pedimos?',
    descripcion: 'Acostados mirando el techo, discuten qué pedir de comida: «Pizza»… «¡Arepas!».',
    precio: 35,
    lugar: 'cuarto',
    dur: 14,
    inicio: { A: [-0.4, 0.7, 0], B: [0.6, 0.7, 0] },
    guion: [
      { t: 0, A: { alto: CAMA, acostado: true, pasos: [{ dur: 3, pose: 'pensando', cara: 'feliz' }] }, B: { alto: CAMA, acostado: true, pasos: [{ dur: 3, pose: 'pensando', cara: 'feliz' }] }, camara: 'dos', sub: 'Domingo, sin ganas de cocinar…' },
      { t: 1.2, dice: ['B', '¿Y si pedimos algo de comer?'], fx: [['B', { tipo: 'foco' }]] },
      { t: 3.4, A: { pasos: [{ dur: 1.4, pose: 'senalar_arriba', cara: 'presumido' }] }, dice: ['A', 'Pizza.'], fx: [['A', { tipo: 'brillo' }]] },
      { t: 5.2, B: { pasos: [{ dur: 1.4, pose: 'enojo_a', cara: 'puchero', mov: [{ tipo: 'cabeza', eje: 'no', grados: 12, frec: 2 }] }] }, dice: ['B', 'No, no… ¡Arepas!'], sonido: 'hmph' },
      { t: 7.0, A: { pasos: [{ dur: 1.2, pose: 'brazos_cruzados', cara: 'puchero' }] }, dice: ['A', 'Pizza.'], camara: 'caraA' },
      { t: 8.2, B: { pasos: [{ dur: 1.2, pose: 'brazos_cruzados', cara: 'enojado' }] }, dice: ['B', 'AREPAS.'], camara: 'caraB', fx: [['B', { tipo: 'vena', dur: 1.2 }]] },
      { t: 9.6, A: { pasos: [{ dur: 1.6, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, B: { pasos: [{ dur: 1.6, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, sonido: 'carcajada', fx: [['A', { tipo: 'risa' }], ['B', { tipo: 'risa' }]], camara: 'dos' },
      { t: 11.4, A: { pasos: [{ dur: 2.4, pose: 'abrazo_der', cara: 'feliz' }] }, B: { pasos: [{ dur: 2.4, pose: 'abrazo_izq', cara: 'feliz' }] }, fx: [['A', { tipo: 'corazones', n: 6 }], ['B', { tipo: 'estrellas', n: 5 }]], sub: 'Al final pidieron las dos.' },
    ],
  },
];
