// Escenas en el escenario grande (piso redondo con telón; el juego queda chiquito en una esquina).
// El centro es (0, 0); el telón va por detrás (y positivo) y la cámara mira de frente.
import type { Escena } from './tipos';

export const GRANDE: Escena[] = [
  {
    id: 'te-dejo-ganar',
    nombre: 'Te dejo ganar',
    descripcion: 'El que va ganando ve al otro triste y finge perder con un drama exagerado… hasta que lo descubren.',
    precio: 20,
    lugar: 'grande',
    dur: 11,
    inicio: { A: [-0.8, 0, 30], B: [0.8, 0, -30] },
    guion: [
      { t: 0, B: { pasos: [{ dur: 2.2, pose: 'triste', cara: 'triste', mov: [{ tipo: 'hundirse', cuanto: 0.1 }] }] }, fx: [['B', { tipo: 'nube', dur: 2 }]], camara: 'dos', sub: 'Alguien va perdiendo…' },
      { t: 1.8, A: { rot: 'otro', pasos: [{ dur: 1.2, pose: 'pensando', cara: 'concentrado' }] }, fx: [['A', { tipo: 'foco' }]], sonido: 'idea' },
      { t: 3.0, A: { pasos: [{ dur: 0.4, pose: 'boca_abierta', cara: 'sorprendido' }, { dur: 2, pose: 'tirado', cara: 'llorando', mov: [{ tipo: 'caer' }] }] }, dice: ['A', '¡Oh no! ¡Me ganaste! ¡Soy un desastre!'], sonido: 'desmayo', fx: [['A', { tipo: 'mareo', dur: 1.8 }]], camara: 'A', sub: '' },
      { t: 5.4, B: { pasos: [{ dur: 1.2, pose: 'celebrar', cara: 'carcajada', mov: [{ tipo: 'salto', alto: 0.3 }] }] }, fx: [['B', { tipo: 'confeti', n: 24 }]], sonido: 'fanfarria', camara: 'dos' },
      { t: 6.8, B: { pasos: [{ dur: 1.4, pose: 'jarras', cara: 'enojado' }] }, fx: [['B', { tipo: 'signo', c: '…' }]], dice: ['B', 'Un momento… ¿me estás dejando ganar?'] },
      { t: 8.2, A: { pasos: [{ dur: 1.2, pose: 'encogerse', cara: 'nervioso' }] }, fx: [['A', { tipo: 'gotita' }]], dice: ['A', '¿Yo? Nooo…'], camara: 'caraA' },
      { t: 9.4, A: 'abrazo', B: 'abrazo', sonido: 'abrazo', fx: [['B', { tipo: 'corazones', n: 6 }]], camara: 'dos', sub: 'Perder por amor también es ganar.' },
    ],
  },
  {
    id: 'baile-victoria',
    nombre: 'El baile de la victoria',
    descripcion: 'El ganador se manda un baile épico con confeti; el otro se resiste… y termina bailando también.',
    precio: 30,
    lugar: 'grande',
    dur: 12,
    inicio: { A: [-0.6, 0.1, 15], B: [1.0, -0.1, -30] },
    guion: [
      { t: 0, A: { pasos: [{ dur: 3.2, pose: 'baile_a', pose2: 'baile_b', ritmo: 2, cara: 'carcajada', mov: [{ tipo: 'rebote', alto: 0.12, frec: 4 }, { tipo: 'balanceo', grados: 10, frec: 2 }] }] }, sonido: 'musiquita', fx: [['A', { tipo: 'notas', dur: 3 }]], camara: 'A', sub: '¡Hora del baile de la victoria!' },
      { t: 1.4, B: { pasos: [{ dur: 2.6, pose: 'brazos_cruzados', cara: 'aburrido' }] }, dice: ['B', 'Ay, no…'] },
      { t: 3.2, A: { pasos: [{ dur: 1.2, pose: 'salto', cara: 'carcajada', mov: [{ tipo: 'giro', vueltas: 1 }, { tipo: 'salto', alto: 0.3 }] }] }, fx: [['A', { tipo: 'confeti', n: 30 }]], sonido: 'tada', camara: 'general', sub: '' },
      { t: 4.4, A: { ir: [0.4, 0.1], vel: 0.8, rot: 'otro', pasos: [{ dur: 1.4, pose: 'regalo', cara: 'guino' }] }, dice: ['A', 'Ven, baila conmigo.'] },
      { t: 5.9, B: { pasos: [{ dur: 1, pose: 'brazos_cruzados', cara: 'puchero', mov: [{ tipo: 'cabeza', eje: 'no', grados: 12, frec: 2 }] }] }, camara: 'dos' },
      { t: 6.9, B: { pasos: [{ dur: 0.8, pose: 'reposo', cara: 'guino', mov: [{ tipo: 'balanceo', grados: 6, frec: 2 }] }] }, fx: [['B', { tipo: 'signo', c: '♪' }]], sub: 'Un pasito…' },
      { t: 7.7, A: { pasos: [{ dur: 4, pose: 'baile_a', pose2: 'baile_b', ritmo: 2, cara: 'carcajada', mov: [{ tipo: 'rebote', alto: 0.1, frec: 4 }] }] }, B: { pasos: [{ dur: 4, pose: 'baile_b', pose2: 'baile_a', ritmo: 2, cara: 'carcajada', mov: [{ tipo: 'rebote', alto: 0.1, frec: 4 }] }] }, fx: [['A', { tipo: 'confeti', n: 30, pantalla: true }]], sonido: 'musiquita', camara: 'general', sub: '…¡y a bailar los dos!' },
    ],
  },
  {
    id: 'puchero-chocolate',
    nombre: 'El puchero y el chocolate',
    descripcion: 'El que perdió hace el puchero más grande del mundo; el otro le ofrece un chocolate… y se le pasa todo.',
    precio: 25,
    lugar: 'grande',
    dur: 11,
    inicio: { A: [-0.7, 0, 20], B: [0.8, 0, -30] },
    props: { B: 'chocolate' },
    guion: [
      { t: 0, A: { pasos: [{ dur: 3, pose: 'puchero', cara: 'puchero', mov: [{ tipo: 'hundirse', cuanto: 0.12 }, { tipo: 'mirar', a: 'lejos' }] }] }, sonido: 'puchero', camara: 'caraA', sub: 'El puchero más grande del mundo.' },
      { t: 1.8, fx: [['A', { tipo: 'nube', dur: 2 }]] },
      { t: 3.0, B: { ir: [0.1, -0.1], vel: 0.7, rot: 'otro' }, camara: 'dos', sub: '' },
      { t: 4.0, B: { pasos: [{ dur: 1.4, pose: 'regalo', cara: 'feliz' }] }, dice: ['B', '¿Un chocolatico?'] },
      { t: 5.4, A: { pasos: [{ dur: 1.2, pose: 'brazos_cruzados', cara: 'puchero', mov: [{ tipo: 'cabeza', eje: 'no', grados: 10, frec: 2 }] }] }, dice: ['A', 'No quiero nada.'], sonido: 'hmph' },
      { t: 6.6, B: { pasos: [{ dur: 1.2, pose: 'comer_a', cara: 'beso' }] }, dice: ['B', 'Bueno, me lo como yo…'] },
      { t: 7.6, A: { pasos: [{ dur: 0.5, pose: 'boca_abierta', cara: 'sorprendido', mov: [{ tipo: 'acercarse', cuanto: 0.7 }] }] }, B: { prop: null }, sonido: 'sorpresa', dice: ['A', '¡NO! ¡Dame!'] },
      { t: 8.3, A: { prop: 'chocolate', pasos: [{ dur: 1.4, pose: 'comer_a', pose2: 'comer_b', ritmo: 2, cara: 'feliz' }] }, fx: [['A', { tipo: 'corazones', n: 5 }]], camara: 'caraA' },
      { t: 9.8, B: 'senalar_reir', A: { pasos: [{ dur: 1.2, pose: 'comer_a', cara: 'guino' }] }, camara: 'dos', sub: 'Remedio infalible.' },
    ],
  },
  {
    id: 'me-rindo-sorpresa',
    nombre: 'Me rindo… ¡sorpresa!',
    descripcion: 'El que pierde saca la bandera blanca y trae un pastel de «felicitaciones»… que termina en la cara del ganador.',
    precio: 30,
    lugar: 'grande',
    dur: 12,
    inicio: { A: [-1.2, 0.2, 30], B: [0.9, 0, -20] },
    props: { A: 'bandera' },
    guion: [
      { t: 0, A: { pasos: [{ dur: 2.2, pose: 'bandera', cara: 'triste', mov: [{ tipo: 'hueso', hueso: 'mano.L', eje: 'z', grados: 20, frec: 1.5 }] }] }, camara: 'general', sub: 'Bandera blanca…' },
      { t: 1.2, dice: ['A', 'Me rindo. Ganaste, mi amor.'] },
      { t: 2.6, B: { pasos: [{ dur: 1.6, pose: 'presumir_a', cara: 'presumido', mov: [{ tipo: 'inflarse', cuanto: 0.06 }] }] }, fx: [['B', { tipo: 'brillo' }]], dice: ['B', 'Lo sé, lo sé.'] },
      { t: 4.2, A: { prop: 'pastel', ir: [0.2, 0], vel: 0.7, rot: 'otro', pasos: [{ dur: 2, pose: 'regalo', cara: 'feliz' }] }, sonido: 'tin', sub: 'Un pastel de felicitaciones…', camara: 'dos' },
      { t: 6.2, B: { pasos: [{ dur: 1, pose: 'inclinado', cara: 'feliz' }] }, dice: ['B', 'Aww, qué lindo…'], sub: '' },
      { t: 7.2, A: { prop: null, pasos: [{ dur: 0.5, pose: 'lanzar', cara: 'carcajada', suave: 32, mov: [{ tipo: 'acercarse', cuanto: 0.5 }] }] }, particulas: ['crema', 'B'], sonido: 'splash', temblor: 0.35, camara: 'caraB' },
      { t: 7.8, B: { pasos: [{ dur: 1.8, pose: 'boca_abierta', cara: 'sorprendido', mov: [{ tipo: 'temblor', amp: 0.008, frec: 10 }] }] }, fx: [['B', { tipo: 'gotita' }]], sub: '¡PLAF!' },
      { t: 9.6, A: 'senalar_reir', fx: [['A', { tipo: 'risa', texto: 'JA JA JA' }]], camara: 'dos', sub: '' },
      { t: 10.6, B: { pasos: [{ dur: 1.4, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, dice: ['B', 'Esta me la pagas…'], fx: [['B', { tipo: 'corazones', n: 3 }]] },
    ],
  },
  {
    id: 'trampa-descubierta',
    nombre: 'Trampa descubierta',
    descripcion: 'Uno esconde dados de más; el otro lo investiga con lupa, lo descubre… y empieza la persecución.',
    precio: 30,
    lugar: 'grande',
    dur: 12,
    inicio: { A: [-0.5, 0, 20], B: [1.1, 0.1, -40] },
    guion: [
      { t: 0, A: { pasos: [{ dur: 2.2, pose: 'soplar', cara: 'guino' }] }, fx: [['A', { tipo: 'notas', dur: 2 }]], sonido: 'musiquita', camara: 'A', sub: 'Silbando… muy inocente.' },
      { t: 2.0, B: { prop: 'lupa', ir: [0.35, -0.2], vel: 0.5, rot: 'otro', pasos: [{ dur: 2.4, pose: 'inclinado', cara: 'concentrado' }] }, fx: [['B', { tipo: 'signo', c: '?' }]], camara: 'dos', sub: '' },
      { t: 4.4, B: { pasos: [{ dur: 1, pose: 'inclinado', cara: 'enojado' }] }, dice: ['B', 'Mmm… ¿y eso en tu bolsillo?'] },
      { t: 5.4, A: { prop: 'dados', pasos: [{ dur: 1.2, pose: 'encogerse', cara: 'nervioso' }] }, sonido: 'sorpresa', fx: [['A', { tipo: 'gotita' }], ['B', { tipo: 'signo', c: '!' }]], camara: 'caraA' },
      { t: 6.6, B: { prop: null, pasos: [{ dur: 1, pose: 'senalar_a', cara: 'enojado' }] }, fx: [['B', { tipo: 'vena', dur: 1.2 }]], dice: ['B', '¡TRAMPOSO!'], camara: 'dos' },
      { t: 7.6, A: { prop: null, ir: [-2.2, 0.8], vel: 2.2, pasos: [{ dur: 3, cara: 'carcajada' }] }, sonido: 'huida', camara: 'general' },
      { t: 7.9, B: { ir: [-1.4, 0.4], vel: 2.0, pasos: [{ dur: 3, cara: 'enojado' }] }, dice: ['B', '¡Vuelve acá!'] },
      { t: 9.2, A: { ir: [1.8, 0.6], vel: 2.2 }, B: { ir: [0.6, 0.2], vel: 2.0 } },
      { t: 10.6, A: { ir: [0.3, -0.3], vel: 1.8, rot: 'otro' }, B: { ir: [0.9, -0.2], vel: 1.4, rot: 'otro' } },
      { t: 11.3, A: { pasos: [{ dur: 0.8, pose: 'suplicar', cara: 'puchero' }] }, sub: '¿Perdón…?', fx: [['A', { tipo: 'corazones', n: 3 }]] },
    ],
  },
  {
    id: 'ninja-dados',
    nombre: 'Ninja de los dados',
    descripcion: 'Uno se vuelve ninja: pose de karate, lanza los dados por el aire… y los atrapa todos. O casi.',
    precio: 25,
    lugar: 'grande',
    dur: 11,
    inicio: { A: [-0.3, 0, 10], B: [1.2, 0.2, -40] },
    props: { A: 'dados' },
    guion: [
      { t: 0, A: { pasos: [{ dur: 1.6, pose: 'puno_a', cara: 'concentrado', mov: [{ tipo: 'estirar', cuanto: -0.05 }] }] }, camara: 'A', sub: 'El maestro ninja de los dados.' },
      { t: 1.6, A: { pasos: [{ dur: 0.6, pose: 'puno_b', cara: 'enojado', suave: 30, mov: [{ tipo: 'giro', vueltas: 1 }] }] }, sonido: 'agitar', dice: ['A', '¡HIIIAAA!'] },
      { t: 2.4, A: { prop: null, pasos: [{ dur: 0.5, pose: 'lanzar', cara: 'carcajada', suave: 32 }] }, objeto: { id: 'dado1', prop: 'dados', en: [-0.3, 0, 1.2], volar: [-0.2, 0.2, 2.6] }, sonido: 'boing', camara: 'general', sub: '' },
      { t: 3.0, A: { pasos: [{ dur: 1.6, pose: 'salto', cara: 'concentrado', mov: [{ tipo: 'salto', alto: 0.45 }] }] } },
      { t: 4.2, objeto: { id: 'dado1', volar: [-0.25, 0, 0.02] } },
      { t: 4.8, A: { pasos: [{ dur: 1.2, pose: 'musculo', cara: 'presumido' }] }, B: { pasos: [{ dur: 1.2, pose: 'aplauso_a', pose2: 'aplauso_b', ritmo: 3, cara: 'feliz', sonidoRitmo: 'palmada' }] }, dice: ['B', '¡Wow!'], camara: 'dos' },
      { t: 6.2, sonido: 'plaf', temblor: 0.25, A: { pasos: [{ dur: 0.3, pose: 'boca_abierta', cara: 'sorprendido' }, { dur: 1.8, pose: 'tirado', cara: 'llorando', mov: [{ tipo: 'caer' }] }] }, fx: [['A', { tipo: 'estrellas', n: 6 }], ['A', { tipo: 'mareo', dur: 1.6 }]], sub: '…el dado le cayó en la cabeza.', camara: 'A' },
      { t: 8.4, B: 'senalar_reir', fx: [['B', { tipo: 'risa', texto: 'JA JA' }]], camara: 'dos', sub: '' },
      { t: 9.6, B: { ir: [0.25, 0], vel: 1.2, rot: 'otro', pasos: [{ dur: 1.2, pose: 'acariciar', cara: 'feliz' }] }, objeto: { id: 'dado1', quitar: true }, sub: 'Ninja herido, ninja consentido.' },
    ],
  },
  {
    id: 'mago',
    nombre: 'El gran mago',
    descripcion: 'Con sombrero de mago, uno hace aparecer un osito, flores… y un corazón gigante para el otro.',
    precio: 35,
    lugar: 'grande',
    dur: 13,
    inicio: { A: [-0.5, 0.1, 15], B: [1.0, -0.1, -30] },
    props: { A: 'sombrero' },
    guion: [
      { t: 0, A: { pasos: [{ dur: 1.6, pose: 'reverencia', cara: 'presumido' }] }, sonido: 'fanfarria', camara: 'general', sub: '¡Damas y caballeros… el Gran Mago!' },
      { t: 1.8, A: { pasos: [{ dur: 1.4, pose: 'frotar_manos_a', pose2: 'frotar_manos_b', ritmo: 3, cara: 'concentrado' }] }, fx: [['A', { tipo: 'chispa' }]], sub: 'Abracadabra…', camara: 'A' },
      { t: 3.2, A: { prop: 'peluche', pasos: [{ dur: 1.2, pose: 'trofeo', cara: 'carcajada' }] }, flash: true, sonido: 'tada', fx: [['A', { tipo: 'estrellas', n: 8 }]], sub: '' },
      { t: 4.4, B: { pasos: [{ dur: 1.2, pose: 'aplauso_a', pose2: 'aplauso_b', ritmo: 3, cara: 'carcajada', sonidoRitmo: 'palmada' }] }, dice: ['B', '¡Otro, otro!'], camara: 'dos' },
      { t: 5.8, A: { prop: 'ramo', pasos: [{ dur: 1.2, pose: 'regalo', cara: 'guino' }] }, flash: true, sonido: 'tada', particulas: ['petalos', 'A'] },
      { t: 7.2, B: { pasos: [{ dur: 1.4, pose: 'boca_abierta', cara: 'sorprendido' }] }, fx: [['B', { tipo: 'sonrojo', dur: 2 }]] },
      { t: 8.6, A: { prop: null, pasos: [{ dur: 1.8, pose: 'senalar_arriba', cara: 'presumido' }] }, sub: 'Y para el gran final…', camara: 'general' },
      { t: 9.6, flash: true, particulas: ['corazones', [0.2, 0]], fx: [['A', { tipo: 'confeti', n: 30, pantalla: true }], ['B', { tipo: 'corazones', n: 12 }]], sonido: 'fanfarria', sub: '¡Un amor infinito!' },
      { t: 11.2, A: 'abrazo', B: 'abrazo', sonido: 'abrazo', camara: 'dos' },
    ],
  },
  {
    id: 'boxeo-de-mentiras',
    nombre: 'Boxeo de mentiras',
    descripcion: 'Round uno: se ponen en guardia, un golpecito de pluma… y el otro cae en cámara lenta como en las películas.',
    precio: 30,
    lugar: 'grande',
    dur: 13,
    inicio: { A: [-0.9, 0, 70], B: [0.9, 0, -70] },
    guion: [
      { t: 0, sonido: 'tin', sub: '¡Round uno!', camara: 'general' },
      { t: 0.6, A: { pasos: [{ dur: 2.4, pose: 'puno_a', pose2: 'puno_b', ritmo: 1.5, cara: 'enojado', mov: [{ tipo: 'rebote', alto: 0.06, frec: 3 }] }] }, B: { pasos: [{ dur: 2.4, pose: 'puno_a', pose2: 'puno_b', ritmo: 1.5, cara: 'enojado', mov: [{ tipo: 'rebote', alto: 0.06, frec: 3 }] }] }, dice: ['A', '¡Ven, pues!'] },
      { t: 3.0, B: { ir: [0.3, 0], vel: 1.2, rot: 'otro' }, A: { ir: [-0.3, 0], vel: 1.2, rot: 'otro' }, camara: 'dos', sub: '' },
      { t: 4.2, B: { pasos: [{ dur: 0.6, pose: 'puno_b', cara: 'concentrado', suave: 30 }] }, sonido: 'pop', sub: '(golpecito de pluma)' },
      { t: 4.9, A: { pasos: [{ dur: 3.2, pose: 'tirado', cara: 'sorprendido', mov: [{ tipo: 'caer' }, { tipo: 'giro', vueltas: 0.5 }] }] }, fx: [['A', { tipo: 'estrellas', n: 8 }]], sonido: 'desmayo', camara: 'A', sub: 'N o o o o o o…' },
      { t: 8.0, sonido: 'plaf', temblor: 0.3, fx: [['A', { tipo: 'polvo' }], ['A', { tipo: 'mareo', dur: 2 }]], sub: '' },
      { t: 8.6, B: { pasos: [{ dur: 1.6, pose: 'contar_a', pose2: 'contar_b', ritmo: 1.5, cara: 'concentrado', sonidoRitmo: 'tic' }] }, sub: 'Uno… dos… tres…', camara: 'dos' },
      { t: 10.2, B: { pasos: [{ dur: 1.2, pose: 'celebrar', cara: 'carcajada', mov: [{ tipo: 'salto', alto: 0.25 }] }] }, fx: [['B', { tipo: 'confeti', n: 24 }]], sonido: 'fanfarria', sub: '¡K.O.!' },
      { t: 11.4, A: { pasos: [{ dur: 1.4, pose: 'tirado', cara: 'guino' }] }, dice: ['A', '…un besito y me levanto.'], fx: [['A', { tipo: 'corazones', n: 3 }]] },
    ],
  },
  {
    id: 'carrera-en-el-sitio',
    nombre: 'La gran carrera',
    descripcion: 'Una carrera a toda velocidad… sin moverse del sitio. Final de foto: ¡empate!',
    precio: 20,
    lugar: 'grande',
    dur: 11,
    inicio: { A: [-0.5, 0, 0], B: [0.5, 0, 0] },
    guion: [
      { t: 0, A: { pasos: [{ dur: 2, pose: 'preparar_salto', cara: 'concentrado', mov: [{ tipo: 'estirar', cuanto: -0.08 }] }] }, B: { pasos: [{ dur: 2, pose: 'preparar_salto', cara: 'concentrado', mov: [{ tipo: 'estirar', cuanto: -0.08 }] }] }, camara: 'dos', sub: 'En sus marcas… listos…' },
      { t: 2.0, sonido: 'tin', sub: '¡FUERA!' },
      { t: 2.2, A: { pasos: [{ dur: 4.4, pose: 'caminar_a', pose2: 'caminar_b', ritmo: 6, cara: 'enojado', mov: [{ tipo: 'rebote', alto: 0.08, frec: 6 }] }] }, B: { pasos: [{ dur: 4.4, pose: 'caminar_a', pose2: 'caminar_b', ritmo: 6.4, cara: 'enojado', mov: [{ tipo: 'rebote', alto: 0.08, frec: 6 }] }] }, fx: [['A', { tipo: 'polvo' }], ['B', { tipo: 'polvo' }]], sonido: 'pasos', camara: 'general' },
      { t: 3.6, sub: 'Van cabeza a cabeza…', fx: [['A', { tipo: 'gotita' }]] },
      { t: 5.0, sub: '¡Última curva!', fx: [['B', { tipo: 'gotita' }], ['A', { tipo: 'humo', dur: 1 }]] },
      { t: 6.6, flash: true, A: { pasos: [{ dur: 1.4, pose: 'puno_a', cara: 'carcajada', mov: [{ tipo: 'salto', alto: 0.2 }] }] }, B: { pasos: [{ dur: 1.4, pose: 'puno_a', cara: 'carcajada', mov: [{ tipo: 'salto', alto: 0.2 }] }] }, sub: 'Foto final…' },
      { t: 8.2, sub: '¡EMPATE!', sonido: 'fanfarria', fx: [['A', { tipo: 'confeti', n: 30, pantalla: true }]], camara: 'dos' },
      { t: 9.2, A: { pasos: [{ dur: 1.6, pose: 'tirado', cara: 'carcajada', mov: [{ tipo: 'caer' }] }] }, B: { pasos: [{ dur: 1.6, pose: 'tirado', cara: 'carcajada', mov: [{ tipo: 'caer' }] }] }, sonido: 'plaf', fx: [['A', { tipo: 'risa' }], ['B', { tipo: 'risa' }]] },
    ],
  },
  {
    id: 'piedra-papel-tijera',
    nombre: 'Piedra, papel o tijera',
    descripcion: 'Un desempate a piedra, papel o tijera con suspenso de final de mundial.',
    precio: 20,
    lugar: 'grande',
    dur: 11,
    inicio: { A: [-0.5, 0, 60], B: [0.5, 0, -60] },
    guion: [
      { t: 0, camara: 'dos', sub: 'Desempate oficial.' },
      { t: 0.6, A: { pasos: [{ dur: 2.4, pose: 'contar_a', pose2: 'contar_b', ritmo: 1.25, cara: 'concentrado', sonidoRitmo: 'tic' }] }, B: { pasos: [{ dur: 2.4, pose: 'contar_a', pose2: 'contar_b', ritmo: 1.25, cara: 'concentrado' }] }, sub: 'Piedra… papel… o…' },
      { t: 3.0, A: { pasos: [{ dur: 2, pose: 'puno_a', cara: 'presumido' }] }, B: { pasos: [{ dur: 2, pose: 'saludo_a', cara: 'presumido' }] }, sonido: 'tin', sub: '¡TIJERA!', camara: 'general' },
      { t: 3.6, sub: 'Piedra contra papel…', fx: [['A', { tipo: 'signo', c: '!?' }]] },
      { t: 5.0, B: { pasos: [{ dur: 1.6, pose: 'celebrar', cara: 'carcajada', mov: [{ tipo: 'salto', alto: 0.3 }] }] }, fx: [['B', { tipo: 'confeti', n: 24 }]], sonido: 'fanfarria', sub: '' },
      { t: 5.4, A: { pasos: [{ dur: 2, pose: 'rodillas_a', pose2: 'rodillas_b', ritmo: 1, cara: 'llorando', mov: [{ tipo: 'hundirse', cuanto: 0.2 }] }] }, fx: [['A', { tipo: 'lagrimas', dur: 2 }]], sonido: 'llanto', dice: ['A', '¡¿POR QUÉ?!'], camara: 'A' },
      { t: 7.6, A: { pasos: [{ dur: 1.2, pose: 'senalar_a', cara: 'puchero' }] }, dice: ['A', '¿Dos de tres?'], camara: 'dos' },
      { t: 8.8, B: { pasos: [{ dur: 1.4, pose: 'jarras', cara: 'guino' }] }, dice: ['B', 'Tres de cinco, y me das un beso.'], fx: [['B', { tipo: 'corazones', n: 4 }]] },
      { t: 10.0, A: { pasos: [{ dur: 1, pose: 'beso', cara: 'beso', mov: [{ tipo: 'acercarse', cuanto: 1 }] }] }, sonido: 'beso', fx: [['B', { tipo: 'sonrojo', dur: 1.2 }]] },
    ],
  },
  {
    id: 'estatua',
    nombre: '¡Estatua!',
    descripcion: 'Bailan con música y cuando para… ¡estatua! Poses imposibles hasta que uno no aguanta la risa.',
    precio: 20,
    lugar: 'grande',
    dur: 12,
    inicio: { A: [-0.7, 0, 20], B: [0.7, 0, -20] },
    guion: [
      { t: 0, A: { pasos: [{ dur: 2.6, pose: 'baile_a', pose2: 'baile_b', ritmo: 2, cara: 'carcajada', mov: [{ tipo: 'rebote', alto: 0.1, frec: 4 }] }] }, B: { pasos: [{ dur: 2.6, pose: 'baile_b', pose2: 'baile_a', ritmo: 2, cara: 'carcajada', mov: [{ tipo: 'rebote', alto: 0.1, frec: 4 }] }] }, sonido: 'musiquita', camara: 'general', sub: '♪ A bailar… ♪' },
      { t: 2.6, A: { pasos: [{ dur: 2.4, pose: 'salto', cara: 'sorprendido', mov: [{ tipo: 'estirar', cuanto: 0.08 }] }] }, B: { pasos: [{ dur: 2.4, pose: 'musculo', cara: 'presumido' }] }, sub: '¡ESTATUA!', sonido: 'tin', camara: 'dos' },
      { t: 3.6, fx: [['A', { tipo: 'gotita' }]], camara: 'caraA' },
      { t: 5.0, A: { pasos: [{ dur: 2.2, pose: 'baile_a', pose2: 'baile_b', ritmo: 2, cara: 'carcajada', mov: [{ tipo: 'rebote', alto: 0.1, frec: 4 }] }] }, B: { pasos: [{ dur: 2.2, pose: 'baile_a', pose2: 'baile_b', ritmo: 2, cara: 'carcajada', mov: [{ tipo: 'rebote', alto: 0.1, frec: 4 }] }] }, sonido: 'musiquita', camara: 'general', sub: '♪ Otra vez… ♪' },
      { t: 7.2, A: { pasos: [{ dur: 2.4, pose: 'reverencia', cara: 'concentrado' }] }, B: { pasos: [{ dur: 2.4, pose: 'senalar_arriba', cara: 'guino', mov: [{ tipo: 'estirar', cuanto: 0.06 }] }] }, sub: '¡ESTATUA!', sonido: 'tin', camara: 'dos' },
      { t: 8.4, A: { pasos: [{ dur: 1.2, pose: 'reverencia', cara: 'carcajada', mov: [{ tipo: 'temblor', amp: 0.012, frec: 12 }] }] }, fx: [['A', { tipo: 'risa', texto: 'pfff' }]], camara: 'caraA' },
      { t: 9.6, A: { pasos: [{ dur: 2.2, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, B: 'senalar_reir', sonido: 'carcajada', dice: ['B', '¡Te moviste! ¡Perdiste!'], camara: 'dos', sub: '' },
    ],
  },
  {
    id: 'telenovela',
    nombre: 'Telenovela',
    descripcion: 'Drama de telenovela: «¡Me traicionaste… con el Parchís!». Lágrimas, desmayo y reconciliación de capítulo final.',
    precio: 35,
    lugar: 'grande',
    dur: 14,
    inicio: { A: [-0.8, 0, 40], B: [0.9, 0.1, -60] },
    props: { A: 'panuelo' },
    guion: [
      { t: 0, sonido: 'sorpresa', sub: 'Capítulo 327: «La traición»', camara: 'general' },
      { t: 1.0, A: { pasos: [{ dur: 1.8, pose: 'llorar_a', pose2: 'llorar_b', ritmo: 1, cara: 'llorando' }] }, fx: [['A', { tipo: 'lagrimas', dur: 1.8 }]], dice: ['A', '¡Me traicionaste…!'], camara: 'caraA', sub: '' },
      { t: 2.8, A: { pasos: [{ dur: 1.2, pose: 'senalar_a', cara: 'enojado', mov: [{ tipo: 'temblor', amp: 0.008, frec: 12 }] }] }, dice: ['A', '¡…con el PARCHÍS!'], temblor: 0.3, sonido: 'sorpresa' },
      { t: 4.0, B: { pasos: [{ dur: 1.6, pose: 'boca_abierta', cara: 'sorprendido' }] }, dice: ['B', '¡No es lo que parece!'], camara: 'caraB' },
      { t: 5.6, A: { pasos: [{ dur: 0.5, pose: 'boca_abierta', cara: 'sorprendido' }, { dur: 2.4, pose: 'desmayo', cara: 'dormido', mov: [{ tipo: 'caer' }] }] }, sonido: 'desmayo', fx: [['A', { tipo: 'estrellas', n: 5 }]], camara: 'general', sub: '(se desmaya con estilo)' },
      { t: 7.2, B: { ir: [-0.45, -0.1], vel: 1.8, rot: 'otro', pasos: [{ dur: 2, pose: 'rodillas_a', cara: 'llorando' }] }, fx: [['B', { tipo: 'lagrimas', dur: 2 }]], dice: ['B', '¡Mi amor, despierta! ¡Solo eres tú!'], sub: '' },
      { t: 9.4, A: { pasos: [{ dur: 1.4, pose: 'tirado', cara: 'guino' }] }, dice: ['A', '…¿solo yo?'], camara: 'caraA' },
      { t: 10.8, A: { prop: null, coreo: 'abrazo' }, B: { coreo: 'abrazo' }, sonido: 'abrazo', fx: [['A', { tipo: 'corazones', n: 10 }]], camara: 'dos', sub: 'Y vivieron dramáticamente felices.' },
      { t: 12.6, sonido: 'fanfarria', sub: 'FIN… (hasta el próximo Parchís)' },
    ],
  },
  {
    id: 'superheroe',
    nombre: 'Superhéroe',
    descripcion: 'Con capa improvisada, uno vuela al rescate del otro, atrapado por un dado gigante malvado.',
    precio: 35,
    lugar: 'grande',
    dur: 13,
    inicio: { A: [-2.2, 0.6, 60], B: [0.9, 0, -20] },
    props: { A: 'bandera' },
    guion: [
      { t: 0, B: { pasos: [{ dur: 2.6, pose: 'suplicar', cara: 'nervioso', mov: [{ tipo: 'temblor', amp: 0.008, frec: 12 }] }] }, objeto: { id: 'dado', prop: 'dados', en: [1.5, 0.3, 0.02] }, dice: ['B', '¡Auxilio! ¡Un dado malvado!'], camara: 'general', sub: 'Mientras tanto, en la ciudad…' },
      { t: 2.4, A: { pasos: [{ dur: 1.4, pose: 'jarras', cara: 'presumido', mov: [{ tipo: 'inflarse', cuanto: 0.08 }] }] }, fx: [['A', { tipo: 'brillo' }]], sonido: 'fanfarria', dice: ['A', '¡Yo te salvo!'], camara: 'A', sub: '' },
      { t: 3.8, A: { alto: 0.6, ir: [0.3, 0.1], vel: 1.6, pasos: [{ dur: 2, pose: 'senalar_arriba', cara: 'carcajada', mov: [{ tipo: 'balanceo', grados: 10, frec: 1 }] }] }, fx: [['A', { tipo: 'aura', dur: 2 }]], sonido: 'huida', camara: 'general', sub: '¡Es un pájaro! ¡Es un avión!' },
      { t: 5.8, A: { alto: 0, rot: 90, pasos: [{ dur: 0.6, pose: 'puno_b', cara: 'enojado', suave: 30 }] }, objeto: { id: 'dado', volar: [2.8, 1.8, 0.02] }, sonido: 'plaf', temblor: 0.4, fx: [['A', { tipo: 'rayos' }]], sub: '¡POW!' },
      { t: 6.8, B: { pasos: [{ dur: 1.4, pose: 'celebrar', cara: 'carcajada', mov: [{ tipo: 'salto', alto: 0.25 }] }] }, dice: ['B', '¡Mi héroe!'], camara: 'dos', sub: '' },
      { t: 8.2, A: { rot: 'otro', pasos: [{ dur: 1.6, pose: 'musculo', cara: 'presumido' }] }, B: { pasos: [{ dur: 1.6, pose: 'beso_volado_b', cara: 'beso' }] }, fx: [['A', { tipo: 'sonrojo', dur: 1.8 }], ['A', { tipo: 'corazones', n: 6 }]], sonido: 'beso' },
      { t: 10.0, A: 'abrazo', B: 'abrazo', sonido: 'abrazo', sub: 'Salvar el día… y besar a la chica.' },
    ],
  },
  {
    id: 'abrazo-de-oso',
    nombre: 'Abrazo de oso',
    descripcion: 'Uno corre desde lejos y le da al otro un abrazo de oso que lo levanta del piso y lo hace girar.',
    precio: 25,
    lugar: 'grande',
    dur: 10,
    inicio: { A: [-2.2, 0.4, 70], B: [0.8, 0, -40] },
    guion: [
      { t: 0, A: { pasos: [{ dur: 1, pose: 'regalo', cara: 'carcajada' }] }, dice: ['A', '¡¡AMOOOR!!'], camara: 'general', sub: 'Modo oso: activado.' },
      { t: 1.0, A: { ir: [0.2, 0], vel: 2.3, pasos: [{ dur: 1.6, cara: 'carcajada' }] }, sonido: 'huida' },
      { t: 1.4, B: { pasos: [{ dur: 1.2, pose: 'boca_abierta', cara: 'sorprendido' }] }, fx: [['B', { tipo: 'signo', c: '!' }]], sub: '' },
      { t: 2.8, A: { rot: 'otro', coreo: 'abrazo' }, B: { rot: 'otro', coreo: 'abrazo' }, sonido: 'abrazo', temblor: 0.2, camara: 'dos' },
      { t: 3.6, B: { alto: 0.3, pasos: [{ dur: 3, pose: 'abrazo_izq', cara: 'carcajada', mov: [{ tipo: 'giro', vueltas: 1.5 }, { tipo: 'hueso', hueso: 'pie.L', eje: 'x', grados: 30, frec: 3 }] }] }, A: { pasos: [{ dur: 3, pose: 'abrazo_der', cara: 'carcajada', mov: [{ tipo: 'giro', vueltas: 1.5 }] }] }, fx: [['B', { tipo: 'corazones', n: 8 }]], sonido: 'carcajada', sub: '¡Vueltaaaas!' },
      { t: 6.8, B: { alto: 0, pasos: [{ dur: 1.2, pose: 'reposo', cara: 'feliz', mov: [{ tipo: 'balanceo', grados: 8, frec: 1.5 }] }] }, fx: [['B', { tipo: 'mareo', dur: 1.2 }]], sub: '' },
      { t: 8.2, B: { pasos: [{ dur: 1.4, pose: 'beso', cara: 'beso' }] }, sonido: 'beso', fx: [['A', { tipo: 'sonrojo', dur: 1.4 }]], sub: 'Mareada… pero feliz.' },
    ],
  },
  {
    id: 'selfie',
    nombre: 'La selfie perfecta',
    descripcion: 'Intentan la selfie perfecta: ojos cerrados, caras raras, un pájaro imaginario… y a la cuarta, ¡la perfecta!',
    precio: 25,
    lugar: 'grande',
    dur: 12,
    inicio: { A: [-0.3, 0, 10], B: [0.35, 0, -10] },
    props: { A: 'camara' },
    guion: [
      { t: 0, A: { pasos: [{ dur: 1.4, pose: 'trofeo', cara: 'feliz' }] }, camara: 'dos', dice: ['A', '¡Selfie!'] },
      { t: 1.4, flash: true, B: { pasos: [{ dur: 1.4, pose: 'reposo', cara: 'dormido' }] }, sub: 'Foto 1: ojos cerrados.' },
      { t: 2.8, flash: true, A: { pasos: [{ dur: 1.4, pose: 'trofeo', cara: 'bostezo' }] }, B: { pasos: [{ dur: 1.4, pose: 'reposo', cara: 'feliz' }] }, sub: 'Foto 2: bostezo.' },
      { t: 4.2, flash: true, A: { pasos: [{ dur: 1.4, pose: 'trofeo', cara: 'sorprendido' }] }, B: { pasos: [{ dur: 1.4, pose: 'senalar_arriba', cara: 'sorprendido' }] }, fx: [['B', { tipo: 'signo', c: '!?' }]], sub: 'Foto 3: «¡mira, un pájaro!».' },
      { t: 5.8, A: { pasos: [{ dur: 1.2, pose: 'facepalm', cara: 'aburrido' }] }, dice: ['A', 'Una más… concéntrate.'], sub: '' },
      { t: 7.2, A: { pasos: [{ dur: 2, pose: 'trofeo', cara: 'carcajada' }] }, B: { pasos: [{ dur: 2, pose: 'beso_volado_b', cara: 'guino', mov: [{ tipo: 'acercarse', cuanto: 0.5 }] }] }, sub: '3… 2… 1…', camara: 'caraB' },
      { t: 8.6, flash: true, fx: [['A', { tipo: 'estrellas', n: 6 }], ['B', { tipo: 'corazones', n: 6 }]], sonido: 'tada', sub: '¡LA PERFECTA!' },
      { t: 10.0, A: { prop: null, coreo: 'chocar_cinco' }, B: 'chocar_cinco', camara: 'dos', sub: 'Directo al álbum.' },
    ],
  },
  {
    id: 'aplausos-publico',
    nombre: 'Ovación del público',
    descripcion: 'Terminan la partida y un público invisible los ovaciona: reverencias, flores volando y lluvia de confeti.',
    precio: 30,
    lugar: 'grande',
    dur: 11,
    inicio: { A: [-0.45, 0, 0], B: [0.45, 0, 0] },
    guion: [
      { t: 0, camara: 'general', sonido: 'palmada_fuerte', sub: '¡Bravo! ¡Bravo!' },
      { t: 0.8, A: { pasos: [{ dur: 1.6, pose: 'reverencia', cara: 'feliz' }] }, B: { pasos: [{ dur: 1.6, pose: 'reverencia', cara: 'feliz' }] } },
      { t: 2.4, objeto: { id: 'flor1', prop: 'ramo', en: [2.5, -1.5, 1.4], volar: [-0.1, -0.4, 0.02] }, sonido: 'palmada_fuerte', fx: [['A', { tipo: 'confeti', n: 30, pantalla: true }]] },
      { t: 3.2, objeto: { id: 'flor2', prop: 'ramo', en: [-2.5, -1.5, 1.4], volar: [0.2, -0.5, 0.02] } },
      { t: 3.8, A: { pasos: [{ dur: 1.4, pose: 'beso_volado_a', cara: 'beso' }] }, B: { pasos: [{ dur: 1.4, pose: 'saludo_a', pose2: 'saludo_b', ritmo: 2, cara: 'carcajada' }] }, camara: 'dos', sub: '' },
      { t: 5.4, A: { pasos: [{ dur: 1.4, pose: 'regalo', cara: 'feliz' }] }, dice: ['A', '¡Y el aplauso es para ella!'], fx: [['B', { tipo: 'aura', dur: 2 }]] },
      { t: 6.8, B: { pasos: [{ dur: 1.6, pose: 'regalo', cara: 'feliz' }] }, fx: [['B', { tipo: 'sonrojo', dur: 2 }]], dice: ['B', '¡No, para los dos!'] },
      { t: 8.4, A: { pasos: [{ dur: 2.4, pose: 'abrazo_der', cara: 'carcajada' }] }, B: { pasos: [{ dur: 2.4, pose: 'abrazo_izq', cara: 'carcajada' }] }, particulas: ['petalos', [0, 0]], sonido: 'fanfarria', fx: [['A', { tipo: 'confeti', n: 40, pantalla: true }]], sub: 'El mejor equipo del mundo.' },
    ],
  },
  {
    id: 'maraton-de-besos',
    nombre: 'Maratón de besos',
    descripcion: 'Un besito… otro… y otro, cada vez más rápido, hasta batir el récord mundial.',
    precio: 40,
    lugar: 'grande',
    dur: 11,
    inicio: { A: [-0.4, 0, 60], B: [0.4, 0, -60] },
    guion: [
      { t: 0, camara: 'dos', sub: 'Intento de récord mundial…' },
      { t: 0.6, A: { pasos: [{ dur: 0.9, pose: 'beso', cara: 'beso', mov: [{ tipo: 'acercarse', cuanto: 1 }] }] }, sonido: 'beso', fx: [['B', { tipo: 'beso' }]], sub: '1' },
      { t: 1.8, B: { pasos: [{ dur: 0.8, pose: 'beso', cara: 'beso', mov: [{ tipo: 'acercarse', cuanto: 1 }] }] }, sonido: 'beso', fx: [['A', { tipo: 'beso' }]], sub: '2' },
      { t: 2.8, A: { pasos: [{ dur: 0.6, pose: 'beso', cara: 'beso', mov: [{ tipo: 'acercarse', cuanto: 1 }] }] }, sonido: 'beso', sub: '3' },
      { t: 3.5, B: { pasos: [{ dur: 0.5, pose: 'beso', cara: 'beso', mov: [{ tipo: 'acercarse', cuanto: 1 }] }] }, sonido: 'beso', sub: '4', fx: [['A', { tipo: 'corazones', n: 3 }]] },
      { t: 4.1, A: { pasos: [{ dur: 2.8, pose: 'beso', pose2: 'abrazo_der', ritmo: 3, cara: 'beso', mov: [{ tipo: 'acercarse', cuanto: 1 }] }] }, B: { pasos: [{ dur: 2.8, pose: 'beso', pose2: 'abrazo_izq', ritmo: 3, cara: 'beso', mov: [{ tipo: 'acercarse', cuanto: 1 }] }] }, sonido: 'beso', fx: [['A', { tipo: 'corazones', n: 12 }], ['B', { tipo: 'corazones', n: 12 }]], sub: '5, 6, 7, 8, 9…', camara: 'general' },
      { t: 5.2, sonido: 'beso', sub: '…¡20!, ¡30!…' },
      { t: 6.2, sonido: 'beso', sub: '…¡100!' },
      { t: 7.0, flash: true, sonido: 'fanfarria', fx: [['A', { tipo: 'confeti', n: 40, pantalla: true }]], sub: '¡NUEVO RÉCORD MUNDIAL!' },
      { t: 8.2, A: { pasos: [{ dur: 2.4, pose: 'reposo', cara: 'feliz', mov: [{ tipo: 'balanceo', grados: 8, frec: 1.2 }] }] }, B: { pasos: [{ dur: 2.4, pose: 'reposo', cara: 'feliz', mov: [{ tipo: 'balanceo', grados: 8, frec: 1.2 }] }] }, fx: [['A', { tipo: 'sonrojo', dur: 2.4 }], ['B', { tipo: 'sonrojo', dur: 2.4 }], ['A', { tipo: 'mareo', dur: 2 }]], camara: 'dos', sub: 'Mañana lo intentamos romper.' },
    ],
  },
  {
    id: 'hacer-las-paces',
    nombre: 'Hacer las paces',
    descripcion: 'Enojados de espaldas… se miran de reojo, se les escapa la risa y sellan las paces con el meñique.',
    precio: 25,
    lugar: 'grande',
    dur: 12,
    inicio: { A: [-0.5, 0, -110], B: [0.5, 0, 110] },
    guion: [
      { t: 0, A: { pasos: [{ dur: 2.6, pose: 'brazos_cruzados', cara: 'enojado' }] }, B: { pasos: [{ dur: 2.6, pose: 'brazos_cruzados', cara: 'enojado' }] }, sonido: 'hmph', fx: [['A', { tipo: 'humo', dur: 1.6 }], ['B', { tipo: 'humo', dur: 1.6 }]], camara: 'general', sub: 'Silencio incómodo…' },
      { t: 2.6, A: { rot: 30, pasos: [{ dur: 1, pose: 'brazos_cruzados', cara: 'puchero' }] }, camara: 'caraA', sub: '(mira de reojo)' },
      { t: 3.6, A: { rot: -110 }, B: { rot: -30, pasos: [{ dur: 1, pose: 'brazos_cruzados', cara: 'puchero' }] }, camara: 'caraB', sub: '(la otra también)' },
      { t: 4.6, B: { rot: 110 }, sub: '' },
      { t: 5.2, A: { rot: 'otro', pasos: [{ dur: 0.8, pose: 'brazos_cruzados', cara: 'sorprendido' }] }, B: { rot: 'otro', pasos: [{ dur: 0.8, pose: 'brazos_cruzados', cara: 'sorprendido' }] }, camara: 'dos', sub: '…se pillaron.' },
      { t: 6.2, A: { pasos: [{ dur: 1.4, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, B: { pasos: [{ dur: 1.4, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, sonido: 'risita', fx: [['A', { tipo: 'risa', texto: 'pfff' }], ['B', { tipo: 'risa', texto: 'ji ji' }]], sub: '' },
      { t: 7.8, A: { pasos: [{ dur: 1.6, pose: 'chocar_cinco', cara: 'feliz', mov: [{ tipo: 'acercarse', cuanto: 1 }] }] }, B: { pasos: [{ dur: 1.6, pose: 'chocar_cinco', cara: 'feliz', mov: [{ tipo: 'acercarse', cuanto: 1 }] }] }, sonido: 'tin', dice: ['A', '¿Paces?'], fx: [['A', { tipo: 'chispa' }]] },
      { t: 9.4, dice: ['B', 'Paces. Promesa de meñique.'], A: 'abrazo', B: 'abrazo', sonido: 'abrazo', fx: [['A', { tipo: 'corazones', n: 8 }], ['B', { tipo: 'corazones', n: 8 }]], sub: 'Ningún juego vale más que nosotros.' },
    ],
  },
];
