// Escenas en la sala: sofá al fondo (y ≈ 1,35), mesita delante (≈ 0,35; 0,45), tele a la izquierda (x ≈ −1,3).
import type { Escena } from './tipos';

/** Altura del asiento del sofá. */
export const SOFA = 0.48;

export const SALA: Escena[] = [
  {
    id: 'persecucion-beso',
    nombre: 'La persecución del beso',
    descripcion: 'Él la persigue por la sala para darle un beso; ella corre, él se cae y llora… y ella vuelve a consolarlo.',
    precio: 40,
    lugar: 'sala',
    dur: 13.5,
    de: 'el',
    inicio: { A: [-1.5, -0.7, 70], B: [0.5, -0.7, -70] },
    guion: [
      { t: 0, camara: 'general', sub: 'Él tiene muchas ganas de un beso…' },
      { t: 0.4, A: 'beso_volado', dice: ['A', 'Mi amor… ¿un besito?'] },
      { t: 1.6, B: { pasos: [{ dur: 0.5, pose: 'boca_abierta', cara: 'sorprendido', mov: [{ tipo: 'salto', alto: 0.08 }] }] }, dice: ['B', '¡Ni lo sueñes!'], sub: '' },
      { t: 2.1, B: { ir: [1.8, -1.5], vel: 2.3, pasos: [{ dur: 5, cara: 'carcajada' }] }, sonido: 'huida' },
      { t: 2.4, A: { ir: [0.4, -1.0], vel: 1.8, pasos: [{ dur: 4.5, cara: 'beso' }] }, camara: 'dos', dice: ['A', '¡Ven acá!'] },
      { t: 3.4, B: { ir: [1.3, 0.5], vel: 2.3 }, A: { ir: [1.4, -1.3], vel: 1.9 } },
      { t: 4.6, B: { ir: [-0.8, 0.3], vel: 2.3 }, A: { ir: [1.1, 0.3], vel: 1.9 }, dice: ['B', '¡Jajaja, no me alcanzas!'] },
      { t: 6.0, B: { ir: [-1.7, -1.3], vel: 2.3 }, A: { ir: [-0.3, 0.0], vel: 2.0 } },
      {
        t: 6.8,
        A: { pasos: [{ dur: 0.3, pose: 'boca_abierta', cara: 'sorprendido', suave: 30 }, { dur: 1.3, pose: 'tirado', cara: 'llorando', mov: [{ tipo: 'caer' }] }] },
        fx: [['A', { tipo: 'mareo', dur: 1.4 }], ['A', { tipo: 'polvo' }]],
        temblor: 0.35,
        sonido: 'plaf',
        camara: 'A',
      },
      { t: 8.4, A: 'llorar', dice: ['A', '¡Auch! Me caí…'], B: { rot: 'otro' } },
      { t: 9.2, B: { ir: [-0.95, -0.35], vel: 1.2, rot: 'otro', pasos: [{ dur: 1.5, cara: 'triste' }] }, dice: ['B', 'Ay, mi amor…'], camara: 'dos' },
      { t: 10.8, B: { pasos: [{ dur: 1.2, pose: 'acariciar', cara: 'feliz' }] }, A: { pasos: [{ dur: 1.2, pose: 'recibir_caricia', cara: 'puchero' }] } },
      {
        t: 12.0,
        B: { pasos: [{ dur: 1.4, pose: 'beso', cara: 'beso' }] },
        A: { pasos: [{ dur: 1.4, pose: 'recibir_caricia', cara: 'feliz' }] },
        fx: [['A', { tipo: 'corazones', n: 8 }], ['A', { tipo: 'sonrojo', dur: 1.6 }]],
        sonido: 'beso',
        sub: 'Ganó el que perdió.',
      },
    ],
  },
  {
    id: 'berrinche',
    nombre: 'El berrinche',
    descripcion: 'En la sala, el que perdió agarra el tablero y lo tira al piso con todas las fichas; el otro se muere de la risa.',
    precio: 35,
    lugar: 'sala',
    dur: 12,
    inicio: { A: [0.2, -0.3, 0], B: [1.4, -0.6, -60] },
    guion: [
      { t: 0, camara: 'general', objeto: { id: 'tablero', prop: 'tablero', en: [0.35, 0.45, 0.36] }, sub: 'Alguien no sabe perder…' },
      { t: 0.8, A: { pasos: [{ dur: 1, pose: 'triste', cara: 'enojado', mov: [{ tipo: 'temblor', amp: 0.01, frec: 14 }] }] }, fx: [['A', { tipo: 'vena', dur: 2 }]], dice: ['A', '¡No es justo!'] },
      { t: 1.8, A: { rot: 180, pasos: [{ dur: 0.6, pose: 'inclinado', cara: 'enojado' }] }, camara: 'A' },
      { t: 2.4, objeto: { id: 'tablero', quitar: true }, A: { prop: 'tablero', rot: 0, pasos: [{ dur: 0.8, pose: 'trofeo', cara: 'enojado', mov: [{ tipo: 'estirar', cuanto: 0.06 }] }] }, sub: '' },
      { t: 3.2, A: { prop: null, pasos: [{ dur: 0.5, pose: 'lanzar', cara: 'enojado', suave: 34 }] }, objeto: { id: 'tablero2', prop: 'tablero', en: [0.2, -0.3, 1.2], volar: [0.9, -1.3, 0.02] }, particulas: ['fichas', [0.5, -0.8]], sonido: 'enojo', camara: 'dos' },
      { t: 4.0, A: 'enojo', fx: [['A', { tipo: 'humo', dur: 1.5 }]] },
      { t: 4.3, B: 'senalar_reir', dice: ['B', '¡JAJAJA! ¿En serio?'] },
      { t: 6.4, A: { rot: 'otro', pasos: [{ dur: 1.4, pose: 'brazos_cruzados', cara: 'puchero', mov: [{ tipo: 'mirar', a: 'lejos' }] }] }, dice: ['A', 'Hmph. Hiciste trampa.'] },
      { t: 8.0, B: { ir: [0.75, -0.45], vel: 1.2, rot: 'otro' }, dice: ['B', 'Ay, ven acá, pataletudo…'] },
      { t: 9.4, A: 'abrazo', B: 'abrazo', camara: 'dos', sub: '…pero sí sabe querer.' },
      { t: 11.2, A: { pasos: [{ dur: 0.8, pose: 'reposo', cara: 'puchero' }] }, dice: ['A', '…igual fue trampa'] },
    ],
  },
  {
    id: 'serenata',
    nombre: 'Serenata',
    descripcion: 'Él saca la guitarra y le canta en la sala; ella, sentada en el sofá, se derrite entre corazones.',
    precio: 45,
    lugar: 'sala',
    dur: 13,
    de: 'el',
    inicio: { A: [1.9, -1.0, -45], B: [-0.2, 1.45, 0] },
    props: { A: 'guitarra' },
    guion: [
      { t: 0, B: { alto: SOFA, pasos: [{ dur: 3, pose: 'sentado', cara: 'normal' }] }, camara: 'general', sub: 'Una noche cualquiera, en la sala…' },
      { t: 0.8, A: { ir: [0.2, 0.1], vel: 0.9, rot: 'otro' }, sonido: 'guitarra' },
      { t: 2.8, A: { pasos: [{ dur: 5, pose: 'agitar_a', pose2: 'agitar_b', ritmo: 1.6, cara: 'feliz', mov: [{ tipo: 'balanceo', grados: 6, frec: 0.8 }] }] }, fx: [['A', { tipo: 'notas', dur: 5 }]], sonido: 'musiquita', sub: '♪ Eres mi pilar, mi hogar… ♪', camara: 'dos' },
      { t: 4.0, B: { pasos: [{ dur: 3, pose: 'sentado_feliz', cara: 'feliz' }] }, fx: [['B', { tipo: 'sonrojo', dur: 3 }]] },
      { t: 5.6, sonido: 'guitarra', camara: 'caraB', fx: [['B', { tipo: 'corazones', n: 6 }]] },
      { t: 7.2, sub: '♪ …te busqué en Transformice y te encontré en la vida ♪', camara: 'A', sonido: 'musiquita' },
      { t: 9.2, A: { prop: null, pasos: [{ dur: 1.2, pose: 'reverencia', cara: 'guino' }] }, sub: '', camara: 'dos' },
      { t: 9.6, B: { alto: 0, pasos: [{ dur: 1.4, pose: 'aplauso_a', pose2: 'aplauso_b', ritmo: 3, cara: 'carcajada', sonidoRitmo: 'palmada' }] }, dice: ['B', '¡Otra, otra!'] },
      { t: 11.0, B: { ir: [0.05, 0.05], vel: 1.4 }, fx: [['B', { tipo: 'corazones', n: 10 }]] },
      { t: 11.8, A: 'abrazo', B: 'abrazo', sonido: 'abrazo' },
    ],
  },
  {
    id: 'cosquillas',
    nombre: 'Ataque de cosquillas',
    descripcion: 'Uno se acerca por la espalda en puntitas… ¡cosquillas! Terminan los dos en el piso muertos de risa.',
    precio: 25,
    lugar: 'sala',
    dur: 11,
    inicio: { A: [-1.6, -1.2, 45], B: [0.5, -0.5, 60] },
    guion: [
      { t: 0, camara: 'general', B: { pasos: [{ dur: 3, pose: 'pensando', cara: 'concentrado' }] }, sub: 'Shhh…' },
      { t: 0.6, A: { ir: [0.05, -0.75], vel: 0.55, pasos: [{ dur: 3.4, pose: 'frotar_manos_a', pose2: 'frotar_manos_b', ritmo: 3, cara: 'presumido' }] }, sonido: 'risita' },
      { t: 3.2, camara: 'dos', sub: '' },
      { t: 3.7, A: { pasos: [{ dur: 2.6, pose: 'frotar_a', pose2: 'frotar_b', ritmo: 6, cara: 'carcajada' }] }, B: { pasos: [{ dur: 0.3, pose: 'boca_abierta', cara: 'sorprendido', mov: [{ tipo: 'salto', alto: 0.1 }] }, { dur: 2.3, pose: 'risita_a', pose2: 'risita_b', ritmo: 5, cara: 'carcajada', mov: [{ tipo: 'temblor', amp: 0.015, frec: 12 }] }] }, fx: [['B', { tipo: 'risa', texto: 'JA JA JA' }], ['B', { tipo: 'lagrimas', dur: 2.2, risa: true }]], sonido: 'carcajada', dice: ['B', '¡NO, NO, ahí noooo!'] },
      { t: 6.3, B: { pasos: [{ dur: 2.5, pose: 'tirado', cara: 'carcajada', mov: [{ tipo: 'caer' }] }] }, temblor: 0.2, sonido: 'plaf', camara: 'B' },
      { t: 6.8, A: { pasos: [{ dur: 0.4, pose: 'boca_abierta', cara: 'sorprendido' }, { dur: 2.2, pose: 'tirado', cara: 'carcajada', mov: [{ tipo: 'caer' }] }] }, fx: [['A', { tipo: 'risa', texto: 'ja ja' }]], sonido: 'carcajada' },
      { t: 8.6, camara: 'dos', sub: 'Los dos tirados en la alfombra, sin aire de tanto reír.' },
      { t: 9.6, A: 'celebrar', B: 'celebrar', fx: [['A', { tipo: 'corazones', n: 5 }]] },
    ],
  },
  {
    id: 'foto-campeones',
    nombre: 'Foto de campeones',
    descripcion: 'Posan con el trofeo en la sala, ¡flash!, y la foto les queda de recuerdo.',
    precio: 35,
    lugar: 'sala',
    dur: 10,
    inicio: { A: [-0.2, -0.6, 20], B: [0.8, -0.6, -20] },
    props: { A: 'trofeo' },
    guion: [
      { t: 0, camara: 'dos', sub: 'Una para el álbum…' },
      { t: 0.6, A: { pasos: [{ dur: 1.6, pose: 'presumir_a', cara: 'presumido' }] }, B: { pasos: [{ dur: 1.6, pose: 'jarras', cara: 'guino' }] }, dice: ['B', '¡Digan wiskiii!'] },
      { t: 2.3, A: { rot: 'camara', pasos: [{ dur: 1.3, pose: 'trofeo', cara: 'carcajada' }] }, B: { rot: 'camara', pasos: [{ dur: 1.3, pose: 'pulgares_a', cara: 'guino' }] }, sub: '3… 2… 1…' },
      { t: 3.6, flash: true, sub: '' },
      { t: 4.3, A: { pasos: [{ dur: 1.2, pose: 'musculo', cara: 'presumido' }] }, B: { pasos: [{ dur: 1.2, pose: 'beso_volado_b', cara: 'beso' }] }, dice: ['A', '¡Otra más!'] },
      { t: 5.6, flash: true },
      { t: 6.3, A: { pasos: [{ dur: 1.4, pose: 'abrazo_der', cara: 'feliz' }] }, B: { pasos: [{ dur: 1.4, pose: 'abrazo_izq', cara: 'feliz' }] }, camara: 'dos' },
      { t: 7.6, flash: true, fx: [['A', { tipo: 'estrellas', n: 6 }], ['B', { tipo: 'corazones', n: 6 }]], sonido: 'tada', sub: 'Campeones… y enamorados.' },
    ],
  },
  {
    id: 'peli-palomitas',
    nombre: 'Película de miedo',
    descripcion: 'Ven una peli de terror en el sofá con palomitas; en el susto las palomitas vuelan y terminan abrazados.',
    precio: 40,
    lugar: 'sala',
    dur: 13,
    inicio: { A: [-0.2, 1.45, 0], B: [0.8, 1.45, 0] },
    props: { A: 'palomitas' },
    guion: [
      { t: 0, A: { alto: SOFA, pasos: [{ dur: 4, pose: 'sentado', cara: 'concentrado' }] }, B: { alto: SOFA, pasos: [{ dur: 4, pose: 'sentado', cara: 'nervioso' }] }, camara: 'general', sub: 'Viernes de película de terror…' },
      { t: 2, camara: 'dos', dice: ['B', 'Yo no tengo miedo, ¿eh?'] },
      { t: 4.2, B: { pasos: [{ dur: 2, pose: 'sentado', cara: 'nervioso', mov: [{ tipo: 'temblor', amp: 0.005, frec: 14 }] }] }, fx: [['B', { tipo: 'gotita' }]], sub: '(música de suspenso)' },
      { t: 6.3, A: { alto: 0.55, pasos: [{ dur: 0.9, pose: 'boca_abierta', cara: 'sorprendido', mov: [{ tipo: 'salto', alto: 0.25 }] }] }, B: { alto: 0.55, pasos: [{ dur: 0.9, pose: 'boca_abierta', cara: 'sorprendido', mov: [{ tipo: 'salto', alto: 0.3 }] }] }, particulas: ['palomitas', 'A'], temblor: 0.4, sonido: 'sorpresa', fx: [['A', { tipo: 'rayos' }], ['B', { tipo: 'rayos' }]], sub: '¡¡BUUU!!' },
      { t: 7.2, A: { alto: SOFA, prop: null, pasos: [{ dur: 2.6, pose: 'abrazo_der', cara: 'nervioso' }] }, B: { alto: SOFA, pasos: [{ dur: 2.6, pose: 'abrazo_izq', cara: 'llorando' }] }, dice: ['B', '¡Apágala, apágala!'], sub: '', camara: 'dos' },
      { t: 9.8, A: { pasos: [{ dur: 2.5, pose: 'sentado_feliz', cara: 'guino' }] }, dice: ['A', '¿No que no tenías miedo?'] },
      { t: 11.2, B: { pasos: [{ dur: 1.6, pose: 'sentado', cara: 'puchero' }] }, fx: [['B', { tipo: 'resoplido' }]], dice: ['B', 'Fue el sonido, no la peli…'] },
    ],
  },
  {
    id: 'siesta-hombro',
    nombre: 'La siesta en el hombro',
    descripcion: 'Uno se queda dormido en el hombro del otro roncando; el otro aguanta quieto… y le pone un sombrero.',
    precio: 25,
    lugar: 'sala',
    dur: 12,
    inicio: { A: [-0.2, 1.45, 0], B: [0.8, 1.45, 0] },
    guion: [
      { t: 0, A: { alto: SOFA, pasos: [{ dur: 2.5, pose: 'sentado', cara: 'aburrido' }] }, B: { alto: SOFA, pasos: [{ dur: 5, pose: 'sentado', cara: 'feliz' }] }, camara: 'general', sub: 'Domingo en la tarde…' },
      { t: 1.5, A: { pasos: [{ dur: 1.4, pose: 'bostezo', cara: 'bostezo' }] }, sonido: 'bostezo' },
      { t: 3.0, A: { pasos: [{ dur: 5.5, pose: 'recibir_caricia', cara: 'dormido', mov: [{ tipo: 'hundirse', cuanto: 0.03 }] }] }, fx: [['A', { tipo: 'zzz', dur: 5 }]], camara: 'dos', sub: 'Zzz… zzz…' },
      { t: 4.5, B: { pasos: [{ dur: 1.6, pose: 'sentado', cara: 'sorprendido' }] }, dice: ['B', '¿Ya? ¿Tan rápido?'] },
      { t: 6.3, B: { pasos: [{ dur: 1.4, pose: 'risita_a', cara: 'guino' }] }, fx: [['B', { tipo: 'brillo' }]], sub: '' },
      { t: 7.6, A: { prop: 'sombrero' }, sonido: 'pop', camara: 'caraA' },
      { t: 8.8, B: { pasos: [{ dur: 1.8, pose: 'risita_a', pose2: 'risita_b', ritmo: 3, cara: 'carcajada' }] }, fx: [['B', { tipo: 'risa', texto: 'ji ji' }]], camara: 'dos' },
      { t: 10.4, A: { pasos: [{ dur: 1.5, pose: 'sentado', cara: 'sorprendido' }] }, dice: ['A', '¿Qué? ¿Qué pasó?'] },
    ],
  },
  {
    id: 'karaoke',
    nombre: 'Karaoke desafinado',
    descripcion: 'Uno canta con el micrófono (terriblemente); el otro se tapa los oídos… y termina cantando con él.',
    precio: 30,
    lugar: 'sala',
    dur: 12,
    inicio: { A: [0.3, -0.4, 10], B: [1.6, -0.9, -40] },
    props: { A: 'microfono' },
    guion: [
      { t: 0, camara: 'general', sub: 'Noche de karaoke…' },
      { t: 0.6, A: { pasos: [{ dur: 3, pose: 'hablar_a', pose2: 'hablar_b', ritmo: 1.5, cara: 'carcajada', mov: [{ tipo: 'balanceo', grados: 8, frec: 1.5 }] }] }, fx: [['A', { tipo: 'notas', dur: 3 }]], sonido: 'otra', sub: '♪ Laaa laaa laaaa ♪' },
      { t: 2.2, B: { pasos: [{ dur: 2.2, pose: 'llorar_a', cara: 'enojado', mov: [{ tipo: 'temblor', amp: 0.008, frec: 12 }] }] }, dice: ['B', '¡Mis oídos!'], camara: 'B' },
      { t: 4.4, A: { pasos: [{ dur: 1.6, pose: 'puno_a', cara: 'carcajada', mov: [{ tipo: 'estirar', cuanto: 0.08 }] }] }, sonido: 'rendirse', sub: '♪ ¡Y ESTE ES MI AMOOOR! ♪', camara: 'A' },
      { t: 6.2, B: { ir: [1.0, -0.6], vel: 1, rot: 'otro', pasos: [{ dur: 1.2, cara: 'guino' }] }, dice: ['B', 'A ver, dame eso…'], camara: 'dos', sub: '' },
      { t: 7.6, A: { prop: null }, B: { prop: 'microfono', pasos: [{ dur: 3, pose: 'hablar_a', pose2: 'hablar_b', ritmo: 1.5, cara: 'feliz', mov: [{ tipo: 'balanceo', grados: 6, frec: 1.5 }] }] }, fx: [['B', { tipo: 'notas', dur: 3 }]], sonido: 'musiquita' },
      { t: 8.2, A: { pasos: [{ dur: 3, pose: 'baile_a', pose2: 'baile_b', ritmo: 2, cara: 'carcajada', mov: [{ tipo: 'balanceo', grados: 8, frec: 2 }] }] }, sub: '♪ …a dúo suena mejor ♪' },
    ],
  },
  {
    id: 'guerra-peluche',
    nombre: 'La guerra del peluche',
    descripcion: 'Los dos quieren el mismo osito: jalan y jalan hasta que se caen… y el osito termina en medio de un abrazo.',
    precio: 25,
    lugar: 'sala',
    dur: 11,
    inicio: { A: [-0.4, -0.6, 90], B: [0.5, -0.6, -90] },
    props: { A: 'peluche' },
    guion: [
      { t: 0, camara: 'dos', dice: ['A', 'Mi osito.'] },
      { t: 1.2, dice: ['B', '¡Es MÍO!'], B: { pasos: [{ dur: 0.8, pose: 'enojo_a', cara: 'enojado' }] } },
      { t: 2.2, A: { pasos: [{ dur: 3, pose: 'regalo', cara: 'enojado', mov: [{ tipo: 'balanceo', grados: 10, frec: 1.6 }, { tipo: 'temblor', amp: 0.01, frec: 14 }] }] }, B: { pasos: [{ dur: 3, pose: 'regalo', cara: 'enojado', mov: [{ tipo: 'balanceo', grados: 10, frec: 1.6 }, { tipo: 'temblor', amp: 0.01, frec: 14 }] }] }, fx: [['A', { tipo: 'vena', dur: 2.6 }], ['B', { tipo: 'vena', dur: 2.6 }]], sonido: 'enojo', sub: 'Jalan… y jalan…' },
      { t: 5.3, A: { prop: null, pasos: [{ dur: 1.8, pose: 'tirado', cara: 'sorprendido', mov: [{ tipo: 'caer' }] }] }, B: { pasos: [{ dur: 1.8, pose: 'tirado', cara: 'sorprendido', mov: [{ tipo: 'caer' }] }] }, objeto: { id: 'osito', prop: 'peluche', en: [0.05, -0.6, 1.0], volar: [0.05, -1.1, 0.02] }, temblor: 0.4, sonido: 'plaf', sub: '', camara: 'general' },
      { t: 7.4, A: { pasos: [{ dur: 1, pose: 'reposo', cara: 'carcajada' }] }, B: { pasos: [{ dur: 1, pose: 'reposo', cara: 'carcajada' }] }, fx: [['A', { tipo: 'risa' }], ['B', { tipo: 'risa' }]], sonido: 'carcajada' },
      { t: 8.6, objeto: { id: 'osito', quitar: true }, A: 'abrazo', B: { prop: 'peluche', coreo: 'abrazo' }, camara: 'dos', sub: 'El osito es de los dos. Como todo.' },
    ],
  },
  {
    id: 'masaje',
    nombre: 'Masaje de hombros',
    descripcion: 'Después de perder, uno se sienta rendido en el sofá y el otro le da un masaje hasta que se derrite.',
    precio: 25,
    lugar: 'sala',
    dur: 11,
    inicio: { A: [1.6, -1.1, -30], B: [0.8, 1.45, 0] },
    guion: [
      { t: 0, B: { alto: SOFA, pasos: [{ dur: 3, pose: 'sentado', cara: 'triste' }] }, camara: 'general', sub: 'Día largo…' },
      { t: 1.2, dice: ['B', 'Estoy muerta…'], A: { ir: [1.05, 0.75], vel: 1, rot: 'otro' } },
      { t: 3.2, A: { pasos: [{ dur: 4.5, pose: 'frotar_a', pose2: 'frotar_b', ritmo: 1.6, cara: 'concentrado' }] }, B: { pasos: [{ dur: 4.5, pose: 'recibir_caricia', cara: 'feliz', mov: [{ tipo: 'hundirse', cuanto: 0.04 }, { tipo: 'balanceo', grados: 3, frec: 0.8 }] }] }, camara: 'dos', sub: 'Un poquito aquí… y aquí…' },
      { t: 5.0, fx: [['B', { tipo: 'corazones', n: 4 }]], dice: ['B', 'Ayyy… qué rico'] },
      { t: 7.8, B: { pasos: [{ dur: 2.2, pose: 'sentado_feliz', cara: 'dormido' }] }, fx: [['B', { tipo: 'zzz', dur: 2 }]], camara: 'caraB', sub: 'Se derritió.' },
      { t: 9.6, A: { pasos: [{ dur: 1.3, pose: 'beso', cara: 'beso' }] }, sonido: 'beso', fx: [['B', { tipo: 'corazones', n: 6 }]], camara: 'dos' },
    ],
  },
  {
    id: 'llegada-casa',
    nombre: 'Por fin en casa',
    descripcion: 'Uno llega cansado por la puerta y el otro corre a recibirlo, lo levanta en un abrazo y dan vueltas.',
    precio: 30,
    lugar: 'sala',
    dur: 11,
    inicio: { A: [-2.1, -1.3, 90], B: [0.8, 1.45, 0] },
    guion: [
      { t: 0, B: { alto: SOFA, pasos: [{ dur: 2, pose: 'sentado', cara: 'aburrido' }] }, camara: 'general', sub: 'Toc, toc…' },
      { t: 0.8, A: { ir: [-1.2, -0.9], vel: 0.7, pasos: [{ dur: 2.2, cara: 'triste' }] }, sonido: 'pasos', dice: ['A', 'Llegué… qué día.'] },
      { t: 2.2, B: { alto: 0, pasos: [{ dur: 0.4, pose: 'boca_abierta', cara: 'sorprendido', mov: [{ tipo: 'salto', alto: 0.1 }] }] }, dice: ['B', '¡MI AMOR!'] },
      { t: 2.8, B: { ir: [-0.6, -0.8], vel: 2.4, pasos: [{ dur: 1.5, cara: 'carcajada' }] }, camara: 'dos' },
      { t: 4.0, A: 'abrazo', B: 'abrazo', sonido: 'abrazo', fx: [['A', { tipo: 'corazones', n: 6 }]] },
      { t: 5.2, A: { pasos: [{ dur: 2.2, pose: 'abrazo_der', cara: 'carcajada', mov: [{ tipo: 'giro', vueltas: 1 }] }] }, B: { pasos: [{ dur: 2.2, pose: 'abrazo_izq', cara: 'carcajada', mov: [{ tipo: 'giro', vueltas: 1 }, { tipo: 'salto', alto: 0.2 }] }] }, sub: '…y todo el cansancio se fue.' },
      { t: 7.8, A: { pasos: [{ dur: 1.5, pose: 'beso', cara: 'beso' }] }, B: { pasos: [{ dur: 1.5, pose: 'beso', cara: 'beso' }] }, sonido: 'beso', fx: [['B', { tipo: 'sonrojo', dur: 2 }]], camara: 'dos' },
      { t: 9.4, sub: 'Hogar es donde estás tú.' },
    ],
  },
  {
    id: 'escondidas',
    nombre: 'A las escondidas',
    descripcion: 'Uno se esconde detrás del sofá y el otro lo busca con una lupa… hasta que lo asusta.',
    precio: 25,
    lugar: 'sala',
    dur: 12,
    inicio: { A: [0.3, -1.2, 0], B: [1.9, 1.5, 180] },
    props: { A: 'lupa' },
    guion: [
      { t: 0, A: { pasos: [{ dur: 2, pose: 'llorar_a', cara: 'concentrado' }] }, camara: 'general', dice: ['A', '…ocho, nueve, ¡DIEZ!'] },
      { t: 2.2, A: { ir: [-1.2, -0.2], vel: 0.6, pasos: [{ dur: 3, pose: 'inclinado', cara: 'concentrado' }] }, sub: '¿Dónde estará?' },
      { t: 4.2, A: { ir: [0.2, 0.1], vel: 0.6, pasos: [{ dur: 2.6, pose: 'inclinado', cara: 'concentrado' }] }, camara: 'A', fx: [['A', { tipo: 'signo', c: '?' }]] },
      { t: 6.4, B: { ir: [1.1, 0.05], vel: 1.6, pasos: [{ dur: 1, cara: 'carcajada' }] }, sub: '' },
      { t: 7.2, B: { pasos: [{ dur: 0.8, pose: 'boca_abierta', cara: 'carcajada', mov: [{ tipo: 'salto', alto: 0.15 }] }] }, dice: ['B', '¡BUU!'], camara: 'dos' },
      { t: 7.5, A: { prop: null, pasos: [{ dur: 0.6, pose: 'boca_abierta', cara: 'sorprendido', mov: [{ tipo: 'salto', alto: 0.3 }] }, { dur: 1.6, pose: 'tirado', cara: 'sorprendido', mov: [{ tipo: 'caer' }] }] }, fx: [['A', { tipo: 'rayos' }]], sonido: 'sorpresa', temblor: 0.3 },
      { t: 9.6, B: 'senalar_reir', fx: [['B', { tipo: 'risa', texto: 'JA JA' }]] },
      { t: 10.8, A: { pasos: [{ dur: 1.2, pose: 'reposo', cara: 'puchero' }] }, dice: ['A', 'La próxima cuento yo…'] },
    ],
  },
];
